### ISSUE TITLE
Carbonite quest error when clicking auto track

### ISSUE THREAD

**Issue by cj1967** [IrcDirk/Carbonite-Classic#1]
Date: 2019-09-16 07:19:15
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite.Quests\NxQuest.lua line 10470:
   attempt to index field 'QuestWin' (a nil value)
Debug:
   [C]: ?
   Carbonite.Quests\NxQuest.lua:10470: TrackOnMap()
   Carbonite.Quests\NxQuest.lua:10336: CalcAutoTrack()
   Carbonite.Quests\NxQuest.lua:9212: UpdateList()
   Carbonite.Quests\NxQuest.lua:9125: func()
   ...\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:57:
      ...\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:50
Locals:

AddOns:
  MoncaiCompare, v7.2.0
  Swatter, v8.2.6377 (SwimmingSeadragon)
  WowheadLooter, v11302
  ACP, v3.5.6 
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.04
  AtlasLootClassic, vv1.1.11
  AucAdvanced, v8.2.6420 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BadBoy, vv1-classic
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  BetterVendorPrice, vv1.08.00-classic
  CallbackHandler10, v
  Carbonite, v@project-version@
  CarboniteQuests, v@project-version@
  ClassicThreatMeter, v1.06
  Coordinates, v2.1.0
  CrapAway, v
  DBMCore, v1.13.9
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.4
  Details, v
  DetailsTinyThreat, v
  Dominos, v8.2.28
  DominosCast, v
  DominosEncounter, v
  DominosProgress, v
  DominosRoll, v
  DungeonFinder, v0.1.4
  Enchantrix, v8.2.6411 (SwimmingSeadragon)
  FarmHud, v8.2-1-classic-release
  GatherMate2, v1.45
  GTFO, v4.49.2
  HandyNotes, vv1.5.6
  HandyNotesDungeonLocationsClassic, v1.02
  Identity2, v4.0.3
  Informant, v8.2.6374 (SwimmingSeadragon)
  LibStub, v
  MapCoords, v0.31c
  MonkeySpeed, vv3.4.0
  Paste, v1.4.10
  Prat30, v3.7.36
  Prat30Libraries, v
  SexyMap, vv3-classic
  SilverDragon, vv11302.0
  SilverDragonClassic, vv11302.0
  SilverRareElites, v1.0.0
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SpeedyAutoLoot, v2.0.18
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TitanClassic, v1.0.7.11302
  TitanClassicAmmo, v1.0.7.11302
  TitanClassicBag, v1.0.7.11302
  TitanClassicClock, v1.0.7.11302
  TitanClassicGold, v1.0.7.11302
  TitanClassicLocation, v1.0.7.11302
  TitanClassicLootType, v1.0.7.11302
  TitanClassicPerformance, v1.0.7.11302
  TitanClassicRepair, v1.0.7.11302
  TitanClassicVolume, v1.0.7.11302
  TitanClassicXP, v1.0.7.11302
  TomCats, v0.0.2
  TomPoints, v11302_05
  TomTom, vv11302-1.0.7
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=858)

**Comment by IrcDirk** [comment]
Fixed.
