### ISSUE TITLE
Problems with Maps.

### ISSUE THREAD

**Issue by wtfaatp** [IrcDirk/Carbonite-Classic#10]
So a couple of things I noticed with maps. I was gonna create separate issues not sure if you would prefer that.

- [ ] 1. Auto-zoom seems to work when it likes not always adjusting. 
- [x] 2. Glitching when entering Cities. Seems to not work @ first install and fine after a while.
- [x] 3. Quest givers don't appear on the map. Quest turn-in seems to work fine.
- [ ] 4. (Possible bug) Instance maps do not load. This might not be possible in Classic, or not implemented yet.
- [x] 5. Hide while in combat doesn't seem to trigger. Wasn't for me at least! (Also having the big map open in combat seems to cause a lot of lag/ stuttering!)
- [x] 6. Waypoint paths not showing properly. This goes along with goto location traction doesn't appear proper it shows a random location along the path.

**Comment by IrcDirk** [comment]
Please, every issue a new thread.

1. Even in BFA it was glitching. Will see what we can do to this but this is not a priority now.
2. Will check that, but there were many fixes on the way, maybe its already fixed.
3. ![Quest dot](https://i.imgur.com/TeaE9fM.png)
4. Didnt test instances and BG yet.
5. Some BFA features might not work here. Will check that in spare time.
6. Dont know what do you mean, please show some screenshot.

**Comment by wtfaatp** [comment]
1. Understandable just letting you know :D (I haven't played since Pandashin)
2. I only had it happen to me on a fresh install so I will also check with updates and let you know.
3. DURKA! I'm a moron! 
4. Okay Thank you..
5. Okay Thnx
6. Fixed in update..

**Comment by IrcDirk** [comment]
5. As description says it hides the large carb map (maximized) when in combat. Tested and it works.

**Comment by IrcDirk** [comment]
2. Sorry no problems on my side. Please discrible this problem more.
