### ISSUE TITLE
Lots of quests not in the database

### ISSUE THREAD

**Issue by Thhughmungus** [IrcDirk/Carbonite-Classic#102]
Hi, I have been using Carbonite for many years now. Recently came back to Classic thinking that it would be just the same with all the quests showing. I'm only a level 17 and lots of quests are not in the database. Thanks for your efforts much appreciated.

**Comment by IrcDirk** [comment]
https://github.com/IrcDirk/Carbonite-Classic/issues/89

**Comment by IrcDirk** [comment]
Quest Database updated from new source. Check now should be better.
