### ISSUE TITLE
Dungeon maps do not seem to display properly

### ISSUE THREAD

**Issue by wiesshund** [IrcDirk/Carbonite-Classic#104]
Even with minimap into main map and set to maximize when in instance
it does not seem to, mostly get a blank void screen, sometimes see a small piece of instance but if you move or touch the map zoom back to void screen.

Not sure if this feature is meant to be in yet or not

**Comment by IrcDirk** [comment]
Duplicate #7. Will work on this in spare time.

**Comment by wiesshund** [comment]
Oh darn sorry, didnt mean to dupe
thought i checked open issues better

**Comment by IrcDirk** [comment]
No problem, this reminded me that i have to get this done.

**Comment by wiesshund** [comment]
by the way, just wanted to say thank you, you have done an awesome job with this for classic

**Comment by IrcDirk** [comment]
trying my best ;) tho got little time for this addon :(

**Comment by romadurr** [comment]
Still having this issue, are there any news?
Thx for your work, I was rly happy when I saw there is Carbonite for classic :)

**Comment by IrcDirk** [comment]
Next month i will have more time. Ill look into this issue.

**Comment by blaadje** [comment]
bump

**Comment by Tenawke** [comment]
Any updates on this?

**Comment by Galenthor** [comment]
I have found this as well, irregardless of who I try to tweak the settings...

**Comment by IrcDirk** [comment]
=> [#7](https://github.com/IrcDirk/Carbonite-Classic/issues/7#issuecomment-1404686840)
