### ISSUE TITLE
Quest tracking text over minimap

### ISSUE THREAD

**Issue by TraceWilson** [IrcDirk/Carbonite-Classic#105]
When tracking a quest, quest track info is displayed over the minimap.  In the attached image, see the yellow text over the minimap.  I've dug through every options page I can find and can't get rid of it.  If I disable watching the quest in the Carbonite quest tracker window the text goes away, but as soon as I select a quest to watch, the text for it shows up over the minimap.

![image](https://user-images.githubusercontent.com/32341397/69674265-1c900600-106a-11ea-97cb-efbd1159636c.png)

**Comment by IrcDirk** [comment]
Becouse that text is not from Carbonite. Try moving Carbonite map to other place. Disable all other addons.
