### ISSUE TITLE
Showing quest givers on the map is too small when you zoom out

### ISSUE THREAD

**Issue by Klala** [IrcDirk/Carbonite-Classic#106]
I know it's not a bug, I just wanted to report this because when I go into new zones I wanna see all the places I can get quests and I don't want to search the map by having to zoom in and then drag the map across the whole zone just to see if I didn't miss anything.
Would love to see an option to have more control over the quest giver's location scale and size!

**Comment by IrcDirk** [comment]
!(screen)[https://i.imgur.com/Q4cJoJn.png]

**Comment by Klala** [comment]
I see, well imo it should be higher that 1 by default.
Say 10-15 should be good.
thanks for the answer tho!
