### ISSUE TITLE
Error after Latest WoW Classic update

### ISSUE THREAD

**Issue by hotluck** [IrcDirk/Carbonite-Classic#111]
Swatter gives me the following error after loading Classic after the latest update -

Date: 2019-12-11 15:29:35
ID: 1
Error occured in: AddOn: Carbonite
Count: 2
Message: Warning: AddOn Carbonite attempted to call a protected function (UNKNOWN()) which may require interaction.
Debug:
   [C]: ?
   [C]: ?
   WIM\Modules\WhisperEngine.lua:746:
      WIM\Modules\WhisperEngine.lua:739
   [C]: ?
   [C]: pcall()
   Carbonite\NxCom.lua:1269: SendChatMessageFixed()
   Carbonite\NxCom.lua:1624: OnUpdate()
   Carbonite\Carbonite.lua:1331: NXOnUpdate()
   [string "*:OnUpdate"]:1:
      [string "*:OnUpdate"]:1
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ArkInventory, v30903
  ArkInventoryRules, v20000
  ArkInventorySearch, v20000
  Armory, vv1.4
  AtlasLootClassic, vv1.4.1
  AtlasLootClassicData, vv1.4.1
  AtlasLootClassicDungeonsAndRaids, vv1.4.1
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BetterVendorPrice, vv1.11.00
  Carbonite, v@project-version@
  CarboniteNotes, v@project-version@
  CarboniteQuests, v@project-version@
  CarboniteSocial, v@project-version@
  CarboniteWarehouse, v@project-version@
  ConROC, v1.13.34
  ConROCHunter, v1.13.11
  Decursive, v2.7.6.6
  Dominos, v8.2.31
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  FishingBuddy, v0.7 Beta 1
  Fizzle, v80205-1
  GatherMate2, v1.45.5
  HandyNotes, vv1.5.9
  HandyNotesDungeonLocationsClassic, v1.03
  HealBot, v1.13.2.10
  HealBotTips, v1.13.2.10
  Informant, v8.2.6374 (SwimmingSeadragon)
  Masque, v8.2.8-Classic
  MissingTradeSkillsList, v1.13.27
  oGlow, v2.2.8
  OmniCC, v8.2.5
  Questie, v5.3.0
  SexyMap, vv4-classic
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SmartQuest, v1.18
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TheGuide, v1.4.2
  TipTac, v19.03.31
  TipTacItemRef, v19.03.31
  TitanClassic, v1.1.4.11302
  TitanClassicAmmo, v1.1.4.11302
  TitanClassicBag, v1.1.4.11302
  TitanClassicClock, v1.1.4.11302
  TitanClassicGold, v1.1.4.11302
  TitanClassicLocation, v1.1.4.11302
  TitanClassicLootType, v1.1.4.11302
  TitanClassicMail, v1.0.0.1
  TitanClassicPerformance, v1.1.4.11302
  TitanClassicReagentTracker, v1.13.2 (1.0.8)
  TitanClassicRegen, v1.1.4.11302
  TitanClassicRepair, v1.1.4.11302
  TitanClassicVolume, v1.1.4.11302
  TitanClassicXP, v1.1.4.11302
  TitanProfession, vv1.2-classic
  TitanReputations, vv1.1-classic
  TitanSkills, v1.7.0
  TitanSocial, v1.13.2
  TomTom, vv11302-1.0.8
  TradeSkillMaster, vv4.8.22
  WhatsTraining, v1.8.7
  WIM, v3.8.4
  ZPerl, v5.8.8
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=a43)

**Comment by IrcDirk** [comment]
Update from this repsitory this should be already fixed.

śr., 11 gru 2019, 16:32 użytkownik Amanda <notifications@github.com>
napisał:

**Comment by tmyrdal** [comment]
Message: [ADDON_ACTION_BLOCKED] AddOn 'Carbonite' tried to call the protected function 'UNKNOWN()'.
Time: Wed Dec 11 23:02:44 2019
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'Carbonite' tried to call the protected function 'UNKNOWN()'.
Interface\AddOns\Misspelled\Misspelled.lua:278: in function <Interface\AddOns\Misspelled\Misspelled.lua:275>
(tail call): ?
Interface\AddOns\WIM\Modules\WhisperEngine.lua:746: in function <Interface\AddOns\WIM\Modules\WhisperEngine.lua:739>
[C]: ?
[C]: in function `pcall'
Interface\AddOns\Carbonite\NxCom.lua:1269: in function `SendChatMessageFixed'
Interface\AddOns\Carbonite\NxCom.lua:1624: in function `OnUpdate'
Interface\AddOns\Carbonite\Carbonite.lua:1331: in function `NXOnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: <none>

**Comment by IrcDirk** [comment]
Read my message above. Its already fixed. Download version from this repo.

śr., 11 gru 2019, 23:07 użytkownik Tom Erik Myrdal <notifications@github.com>
napisał:

**Comment by IrcDirk** [comment]
Sorry that was fixed in Retail not here ;) Not it should work without error.

**Comment by IrcDirk** [comment]
Release pushed to CurseForge and WoWInterface.

**Comment by tmyrdal** [comment]
Message: Interface\AddOns\Carbonite\NxMap.lua:10173: attempt to index local 'map' (a nil value)
Time: Wed Dec 18 06:05:08 2019
Count: 1
Stack: Interface\AddOns\Carbonite\NxMap.lua:10173: attempt to index local 'map' (a nil value)
Interface\AddOns\RecipeRadarClassic\Maps.lua:48: in function `RecipeRadar_Maps_AddVendor'
Interface\AddOns\RecipeRadarClassic\DropDowns.lua:484: in function `RecipeRadar_InitVendorFilters'
...ace\AddOns\RecipeRadarClassic\RecipeRadarClassic.lua:308: in function `RecipeRadar_NewRegion'
...ace\AddOns\RecipeRadarClassic\RecipeRadarClassic.lua:194: in function `RecipeRadar_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals: vendor = <table> {
 Coordinates = <table> {
 }
 Name = "Jessara Cordell"
 Team = "Alliance"
 Recipes = <table> {
 }
 IsFiltered = false
}
region = 1453
continent = 1415
id = 1

**Comment by tmyrdal** [comment]
sorry, I dont have a clue on programing addons, I ust whanted to notify if I can help with something.
Dont kill the messanger lol ':)
