### ISSUE TITLE
Interface Action Failed because of an AddOn

### ISSUE THREAD

**Issue by njohnso** [IrcDirk/Carbonite-Classic#112]
Every time the game starts I get this error.  I finally did a little bit of sleuthing to determine what AddOn was causing the error and unfortunately it was Carbonite.  I ran the following command to start Taint Logging.

/console taintLog 1

Reloaded the interface and waited for the error.  Once the error occurred I exited the game an d opened the Log.  Here is what it held.

[taint.log](https://github.com/IrcDirk/Carbonite-Classic/files/3954576/taint.log)

The error seems to be:
12/12 00:08:01.441  Execution tainted by Carbonite while reading Nx - Interface\AddOns\Carbonite.Quests\NxQuest.lua:1896 QuestOptions()

This is on the Macintosh version of WoW Classic.
Hope this helps!

**Comment by IrcDirk** [comment]
Same as #111. Just update from this repo.
