### ISSUE TITLE
[Battlegrounds] Maps do not show up correctly and do not properly update after leaving.

### ISSUE THREAD

**Issue by gunzbngbng** [IrcDirk/Carbonite-Classic#113]
Two errors. 

Date: 2019-12-12 10:37:30
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite\NxMap.lua line 4355:
   attempt to call global 'GetCurrencyInfo' (a nil value)
Debug:
   Carbonite\NxMap.lua:4355: Update()
   Carbonite\NxMap.lua:3922:
      Carbonite\NxMap.lua:3806
Locals:
self = <table> {
 MiniBlks = 6
 IconScale = 3
 MenuIShowWorld = <table> {
 }
 GIconMenuITogInst = <table> {
 }
 TargetNextUniqueId = 1
 MMScalesC = <table> {
 }
 LOpts = <table> {
 }
 TextFStrs = <table> {
 }
 PlyrLastDir = 0
 Scrolling = false
 Menu = <table> {
 }
 EffScale = 0.748250
 Zone = 1459
 WorldAlpha = Infinite
 StartupShown = true
 ScaleDraw = 4
 BackgndAlphaFade = 1
 MoveLastX = 2216.013171
 PlyrDir = 0
 PlyrSpeedCalcTime = 92406.099000
 MapPosYDraw = -309.062521
 PlyrSpeed = 0
 MapScale = 0.399202
 CurMapBG = true
 PadX = 0
 BGIncNum = 0
 ViewSavedData = <table> {
 }
 MapW = 314.799347
 MMGathererUpdateDelay = 1
 MMAddonFrms = <table> {
 }
 LClickTime = 0
 MouseEnabled = true
 ButAutoScaleOn = <table> {
 }
 MapH = 316.221985
 MMScales = <table> {
 }
 MMArrowName = "Interface\Minimap\MinimapArrow"
 MapPosX = 2216.013171
 BackgndAlphaTarget = 1
 MapsDrawnOrder = <table> {
 }
 BGGrowBars = true
 ArrowScroll = 0.240000
 H = 141
 Tick = 5400
 IconNIFrms = <table> {
 }
 LastDungeonLevel = 0
 BaseScale = 1
 ToolBar = <table> {
 }
 MoveLastY = -309.062521
 MenuIShowHerb = <table> {
 }
 DotPartyScale = 1
 PlyrX = 2216.013171
 QuestAlpha = 0.300000
 CurWorldUpdateOverlayNum = 3
 MMFScale = 1.016634
 Scale = 4
 Targets = <table> {
 }
 BackgndAlpha = 1
 ArrowPulse = 1
 MenuIShowMine = <table> {
 }
 MapId = 1459
 MMOwn = true
 MMModels = <table> {
 }
 Size1 = 1.002338
 ShowUnexplored = false
 PIconMenu = <table> {
 }
 DotRaidScale = 1
 IconFrms = <table> {
 }
 WorldHotspotTipStr = "Eastern Kingdoms, Western Plaguelands (51-58)
"
 StepTime = 0
 PlyrSpeedX = 2216.013171
 PlyrFrm = <unnamed> {
 }
 DebugAdjustScale = 0.100000
 ScaleDrawW = 0.250000
 IconStaticFrms = <table> {
 }
 UpdateTrackingDelay = 0
 IconNavScale = 1
 MiniFrms = <table> {
 }
 InCombat = false
 Win = <table> {
 }
 InstanceId = false
 RealScale = 4
 Data = <table> {
 }
 TrackDir = false
 MMMaskName = "Interface\Buttons\White8x8"
 TrackETA = false
 MMZoomChanged = false
 MMScale = 4
 MenuIShowTimber = <table> {
 }
 CurOverlays = false
 MMZoomType = 0
 Indoors = true
 LocTipFStrs = <table> {
 }
 TrackPlyrs = <table> {
 }
 TextFrm = <unnamed> {
 }
 Cont = 4
 TextScFrm = <unnamed> {
 }
 MMChkDelay = 6
 GIconMenuIFindNote = <table> {
 }
 PlyrY = -309.062521
 Level = 3
 WorldHotspotsCity = <table> {
 }
 Guide = <table> {
 }
 WorldHotspots = <table> {
 }
 Tracking = <table> {
 }
 PlyrRZY = 51.143962
 W = 150
 CurWorldUpdateMapId = 947
 MenuIInstanceMaps = <table> {
 }
 LocTipFrm = NxMapTip {
 }
 MMAlphaDelay = 0
 MapsDrawnFade = <table> {
 }
 PlyrSpeedY = -309.062521
 ContFrms = <table> {
 }
 MMOwnedFrms = <table> {
 }
 TileFrms = <table> {
 }
 ScaleW = 0.250000
 UpdateTargetDelay = 0
 CurOpts = <table> {
 }
 MenuIPlyrFollow = <table> {
 }
 TitleH = 0
 MapPosY = -309.062521
 IconWQFrms = <table> {
 }
 ArchAlpha = 0.300000
 MapPosXDraw = 2216.013171
 MapIndex = 1
 MenuIMonitorZone = <table> {
 }
 PlyrRZX = 66.549963
 KillShow = false
 BGIconMenu = <table> {
 }
 NeedWorldUpdate = false
 DotZoneScale = 1
 GIconMenu = <table> {
 }
 Frm = <unnamed> {
 }
 TransMenu = <table> {
 }
 MoveDir = 180
 BackgndAlphaFull = 1
 DotPalScale = 1
}
elapsed = 0.010000
Nx = <table> {
 GetDataToolBar = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1878
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:147
 Quest = <table> {
 }
 OnUnit_spellcast_sent = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1108
 IsGathering = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:3011
 prt = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:133
 BarData = <table> {
 }
 prtVar = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:204
 ScheduleTimer = <function> defined @Interface\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 GroupMembers = <table> {
 }
 ADDON_LOADED = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:845
 prtFrame = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:241
 RequestTime = false
 UnregisterAllComm = <function> define
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.3.4
  AtlasLootClassicData, vv1.3.4
  AtlasLootClassicDungeonsAndRaids, vv1.3.4
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  Carbonite, v@project-version@
  CarboniteNotes, v@project-version@
  CarboniteQuests, v@project-version@
  CarboniteSocial, v@project-version@
  CarboniteWarehouse, v@project-version@
  CEPGP, v
  DBMCore, v1.13.24
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Dominos, v8.2.31
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  ElkBuffBars, v2.6.0-194
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExtendedCharacterStats, v1.5
  honorspy, v1.6.0
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LunaUnitFrames, v3042
  NeatPlates, v1.13.2.45
  NeatPlatesAlvara, v5a
  NeatPlatesBlizzardPlates, v1.5
  NeatPlatesClassicPlates, v
  NeatPlatesGraphite, v
  NeatPlatesGrey, v
  NeatPlatesNeon, v
  NeatPlatesQuatre, v
  NeatPlatesRenaitre, vv7.0.3
  NeatPlatesRoth, v
  NeatPlatesSimple, v7.3.0
  NeatPlatesSlimHorizontal, v2.2
  NeatPlatesSlimVertical, v2.2
  NeatPlatesHub, v
  NeatPlatesWidgets, v
  OmniCC, v8.2.5
  Quartz, v3.5.2
  RealMobHealth, v2.2
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  tdBag2, v1.0.1
  TrinketMenu, v7.3.2
  WeakAuras, v2.14.0-beta2
  YaHT, v
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=74a)

second:
Date: 2019-12-12 10:52:14
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite\NxMap.lua line 4327:
   attempt to call global 'GetCurrencyInfo' (a nil value)
Debug:
   Carbonite\NxMap.lua:4327: Update()
   Carbonite\NxMap.lua:3922:
      Carbonite\NxMap.lua:3806
Locals:
self = <table> {
 MiniBlks = 6
 IconScale = 3
 MenuIShowWorld = <table> {
 }
 GIconMenuITogInst = <table> {
 }
 TargetNextUniqueId = 1
 MMScalesC = <table> {
 }
 LOpts = <table> {
 }
 TextFStrs = <table> {
 }
 PlyrLastDir = 0
 Scrolling = false
 Menu = <table> {
 }
 EffScale = 0.748250
 Zone = 1416
 WorldAlpha = Infinite
 StartupShown = true
 ScaleDraw = 4
 ClickFrmY = 674.333252
 BackgndAlphaFade = 1
 MoveLastX = 2216.013171
 PlyrDir = 0
 PlyrSpeedCalcTime = 92406.099000
 MapPosYDraw = -309.062521
 PlyrSpeed = 0
 MapScale = 0.399202
 CurMapBG = false
 PadX = 0
 BGIncNum = 0
 ViewSavedData = <table> {
 }
 MapW = 314.799347
 MMGathererUpdateDelay = 1
 MMAddonFrms = <table> {
 }
 LClickTime = 0
 MouseEnabled = true
 ButAutoScaleOn = <table> {
 }
 MapH = 316.221985
 MMScales = <table> {
 }
 MMArrowName = "Interface\Minimap\MinimapArrow"
 MapPosX = 2216.013171
 BackgndAlphaTarget = 1
 MapsDrawnOrder = <table> {
 }
 BGGrowBars = true
 ArrowScroll = 0.980000
 H = 141
 Tick = 22275
 IconNIFrms = <table> {
 }
 LastDungeonLevel = 0
 BaseScale = 1
 ToolBar = <table> {
 }
 MoveLastY = -309.062521
 MenuIShowHerb = <table> {
 }
 DotPartyScale = 1
 PlyrX = 2216.013171
 QuestAlpha = 0.300000
 CurWorldUpdateOverlayNum = 9
 MMFScale = 0.400000
 Scale = 4
 Targets = <table> {
 }
 BackgndAlpha = 1
 ArrowPulse = 1
 MenuIShowMine = <table> {
 }
 MapId = 1416
 MMOwn = true
 MMModels = <table> {
 }
 Size1 = 1.002338
 MenuMapId = 1459
 MMChkDelay = 12
 ShowUnexplored = false
 PIconMenu = <table> {
 }
 DotRaidScale = 1
 IconFrms = <table> {
 }
 WorldHotspotTipStr = "Eastern Kingdoms, Western Plaguelands (51-58)
"
 StepTime = 5
 PlyrSpeedX = 2216.013171
 PlyrFrm = <unnamed> {
 }
 DebugAdjustScale = 0.100000
 ScaleDrawW = 0.250000
 IconStaticFrms = <table> {
 }
 UpdateTrackingDelay = 0
 IconNavScale = 1
 MiniFrms = <table> {
 }
 InCombat = false
 Win = <table> {
 }
 InstanceId = false
 RealScale = 4
 Data = <table> {
 }
 TrackDir = false
 MMMaskName = "Interface\Buttons\White8x8"
 TrackETA = false
 MMZoomChanged = false
 MMScale = 4
 MenuIShowTimber = <table> {
 }
 CurOverlays = false
 MMZoomType = 0
 Indoors = true
 LocTipFStrs = <table> {
 }
 TrackPlyrs = <table> {
 }
 TextFrm = <unnamed> {
 }
 Cont = 2
 TextScFrm = <unnamed> {
 }
 ClickFrmX = 788.733271
 GIconMenuIFindNote = <table> {
 }
 PlyrY = -309.062521
 Level = 3
 WorldHotspotsCity = <table> {
 }
 Guide = <table> {
 }
 WorldHotspots = <table> {
 }
 Tracking = <table> {
 }
 PlyrRZY = 51.143962
 W = 150
 CurWorldUpdateMapId = 1459
 MenuIInstanceMaps = <table> {
 }
 LocTipFrm = NxMapTip {
 }
 MMAlphaDelay = 0
 MapsDrawnFade = <table> {
 }
 PlyrSpeedY = -309.062521
 ContFrms = <table> {
 }
 MMOwnedFrms = <table> {
 }
 TileFrms = <table> {
 }
 ScaleW = 0.250000
 UpdateTargetDelay = 0
 CurOpts = <table> {
 }
 MenuIPlyrFollow = <table> {
 }
 TitleH = 0
 MapPosY = -309.062521
 IconWQFrms = <table> {
 }
 ArchAlpha = 0.300000
 MapPosXDraw = 2216.013171
 MapIndex = 1
 MenuIMonitorZone = <table> {
 }
 PlyrRZX = 66.549963
 KillShow = false
 BGIconMenu = <table> {
 }
 NeedWorldUpdate = false
 DotZoneScale = 1
 GIconMenu = <table> {
 }
 Frm = <unnamed> {
 }
 TransMenu = <table> {
 }
 MoveDir = 180
 BackgndAlphaFull = 1
 DotPalScale = 1
}
elapsed = 0.588000
Nx = <table> {
 GetDataToolBar = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1878
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:147
 Quest = <table> {
 }
 OnUnit_spellcast_sent = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1108
 IsGathering = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:3011
 prt = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:133
 BarData = <table> {
 }
 prtVar = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:204
 ScheduleTimer = <function> defined @Interface\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 GroupMembers = <table> {
 }
 ADDON_LOADED = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:845
 prtFrame = <function> defined @Interface\AddOns\Carbonite\Nx
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.3.4
  AtlasLootClassicData, vv1.3.4
  AtlasLootClassicDungeonsAndRaids, vv1.3.4
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  Carbonite, v@project-version@
  CarboniteNotes, v@project-version@
  CarboniteQuests, v@project-version@
  CarboniteSocial, v@project-version@
  CarboniteWarehouse, v@project-version@
  CEPGP, v
  DBMCore, v1.13.24
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Dominos, v8.2.31
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  ElkBuffBars, v2.6.0-194
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExtendedCharacterStats, v1.5
  honorspy, v1.6.0
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LunaUnitFrames, v3042
  NeatPlates, v1.13.2.45
  NeatPlatesAlvara, v5a
  NeatPlatesBlizzardPlates, v1.5
  NeatPlatesClassicPlates, v
  NeatPlatesGraphite, v
  NeatPlatesGrey, v
  NeatPlatesNeon, v
  NeatPlatesQuatre, v
  NeatPlatesRenaitre, vv7.0.3
  NeatPlatesRoth, v
  NeatPlatesSimple, v7.3.0
  NeatPlatesSlimHorizontal, v2.2
  NeatPlatesSlimVertical, v2.2
  NeatPlatesHub, v
  NeatPlatesWidgets, v
  OmniCC, v8.2.5
  Quartz, v3.5.2
  RealMobHealth, v2.2
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  tdBag2, v1.0.1
  TrinketMenu, v7.3.2
  WeakAuras, v2.14.0-beta2
  YaHT, v
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=777)

**Comment by IrcDirk** [comment]
Battlegrounds are not implemented. Maybe in the future.

**Comment by poosev2** [comment]
probably same issue here. Works fine in the battleground, but tons of errors upon leaving the bg. Forced to reload ui after every bg to prevent errors

**Comment by evilmaran** [comment]
is there anything we can do to fix this on our end? other then disabling the addon?

**Comment by evilmaran** [comment]
got this error now: 

Date: 2019-12-19 18:33:00
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite\NxMap.lua line 4355:
   attempt to call global 'GetCurrencyInfo' (a nil value)
Debug:
   ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:732:
      ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:692
   [C]: GetCurrencyInfo()
   Carbonite\NxMap.lua:4355: Update()
   Carbonite\NxMap.lua:3922:
      Carbonite\NxMap.lua:3806
Locals:
errMsg = "Interface\AddOns\Carbonite\NxMap.lua:4355: attempt to call global 'GetCurrencyInfo' (a nil value)"
tsmErrMsg = nil
oldModule = nil
private = <table> {
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:513
 num = 0
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:132
 hitInternalError = false
 origErrorHandler = <function> defined @Interface\AddOns\Decursive\Dcr_DIAG.lua:597
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:494
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:479
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:487
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:327
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:379
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:455
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:296
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AddOnSkins, v4.39
  AtlasLootClassic, vv1.4.3
  AtlasLootClassicData, vv1.4.3
  AtlasLootClassicDungeonsAndRaids, vv1.4.3
  ATTClassic, v0.1.3
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucScanData, v8.2.6498 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  Carbonite, v@project-version@
  CarboniteNotes, v@project-version@
  CarboniteQuests, v@project-version@
  CarboniteSocial, v@project-version@
  CarboniteWarehouse, v@project-version@
  ClassicPremade, v6
  ClassicSpellActivations, v
  ClassicThreatMeter, v1.10
  Clique, vv1.0.3-classic
  DBMCore, v1.13.24
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.6
  DSM, v4
  ElvUI, v1.19
  ElvUIExtraDataTextsClassic, v1.0.2
  ElvUILocationPlus, v1.01
  ElvUIOptionsUI, v1.06
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  ExtendedCharacterStats, v1.5
  FishingBuddy, v0.7 Beta 1
  GatherMate2, v1.45.5
  GTFO, v4.51
  honorspy, v1.6.7
  Informant, v8.2.6508 (SwimmingSeadragon)
  ItemRack, v
  LeatrixPlus, v1.13.41
  PallyPower, vv1.1d-classic
  RealMobHealth, v2.17
  Recount, vv8.2.5d
  ShowMeMyHeal, v0.6.1
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Spy, v1.0.19
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TradeSkillMaster, vv4.8.24
  TradeSkillMasterAppHelper, vv4.0.6
  WeakAuras, v2.15.5
  WeakAurasOptions, v2.15.5
  WhatsTraining, v1.8.7
  WideQuestLog, v
  WIM, v3.8.4
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=731)

**Comment by evilmaran** [comment]
and this on leaving BG:

Date: 2019-12-19 18:47:51
ID: 3
Error occured in: AddOn: Carbonite
Count: 14
Message: Note: AddOn Carbonite attempted to call a protected function (CompactRaidFrame1:Show()) during combat lockdown.
Debug:
   [C]: Show()
   ..\FrameXML\CompactUnitFrame.lua:353: CompactUnitFrame_UpdateVisible()
   ..\FrameXML\CompactUnitFrame.lua:286: CompactUnitFrame_UpdateAll()
   ..\FrameXML\CompactUnitFrame.lua:54:
      ..\FrameXML\CompactUnitFrame.lua:51
Locals:
None
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AddOnSkins, v4.39
  AtlasLootClassic, vv1.4.3
  AtlasLootClassicData, vv1.4.3
  AtlasLootClassicDungeonsAndRaids, vv1.4.3
  ATTClassic, v0.1.3
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucScanData, v8.2.6498 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  Carbonite, v@project-version@
  CarboniteNotes, v@project-version@
  CarboniteQuests, v@project-version@
  CarboniteSocial, v@project-version@
  CarboniteWarehouse, v@project-version@
  ClassicPremade, v6
  ClassicSpellActivations, v
  ClassicThreatMeter, v1.10
  Clique, vv1.0.3-classic
  DBMCore, v1.13.24
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.6
  DSM, v4
  ElvUI, v1.19
  ElvUIExtraDataTextsClassic, v1.0.2
  ElvUILocationPlus, v1.01
  ElvUIOptionsUI, v1.06
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  ExtendedCharacterStats, v1.5
  FishingBuddy, v0.7 Beta 1
  GatherMate2, v1.45.5
  GTFO, v4.51
  honorspy, v1.6.7
  Informant, v8.2.6508 (SwimmingSeadragon)
  ItemRack, v
  LeatrixPlus, v1.13.41
  PallyPower, vv1.1d-classic
  RealMobHealth, v2.17
  Recount, vv8.2.5d
  ShowMeMyHeal, v0.6.1
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Spy, v1.0.19
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TradeSkillMaster, vv4.8.24
  TradeSkillMasterAppHelper, vv4.0.6
  WeakAuras, v2.15.5
  WeakAurasOptions, v2.15.5
  WhatsTraining, v1.8.7
  WideQuestLog, v
  WIM, v3.8.4
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=731)

**Comment by IrcDirk** [comment]
@evilmaran u are using latest version from this repository?

**Comment by evilmaran** [comment]
using latest from twitch app

**Comment by IrcDirk** [comment]
Use latest from this repo. Twitch is updated after fix is confirmed here.

pt., 20 gru 2019, 15:51 użytkownik evilmaran <notifications@github.com>
napisał:

**Comment by evilmaran** [comment]
dont get massive lag anymore after leaving BG, havent seen an error yet either since using latest from here.
