### ISSUE TITLE
Quest Tracker standalone

### ISSUE THREAD

**Issue by Drexl** [IrcDirk/Carbonite-Classic#114]
Would there be any chance of getting just the quest tracker module with Tom Tom emulation as a standalone addon for classic? It's the only part of Carbonite I use. Also, it's dependency conflicts with others.

Thanks for your consideration.

**Comment by IrcDirk** [comment]
Sorry, but no. Hardly have time for maintaining both Classic and Retail version.

**Comment by IrcDirk** [comment]
Try Questie or Codex.

**Comment by Drexl** [comment]
I use Questie. Unfortuantely even with just that and TomTom active the arrow doesn't work. Even if it did, the tracker looks awful. I've not found any quest tracker that looks as good as Carbonite's. Thanks for the suggestion though. :)
