### ISSUE TITLE
Errors upon entering and exiting AV

### ISSUE THREAD

**Issue by evilmaran** [IrcDirk/Carbonite-Classic#115]
Error 1:

Date: 2019-12-15 12:37:27
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite\NxMap.lua line 4355:
   attempt to call global 'GetCurrencyInfo' (a nil value)
Debug:
   ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:732:
      ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:692
   [C]: GetCurrencyInfo()
   Carbonite\NxMap.lua:4355: Update()
   Carbonite\NxMap.lua:3922: OnUpdate()
   Carbonite\NxMap.lua:1387: MainOnUpdate()
   Carbonite\Carbonite.lua:1332: NXOnUpdate()
   [string "*:OnUpdate"]:1:
      [string "*:OnUpdate"]:1
Locals:
errMsg = "Interface\AddOns\Carbonite\NxMap.lua:4355: attempt to call global 'GetCurrencyInfo' (a nil value)"
tsmErrMsg = nil
oldModule = nil
private = <table> {
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:513
 num = 0
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:132
 hitInternalError = false
 origErrorHandler = <function> defined @Interface\AddOns\Decursive\Dcr_DIAG.lua:597
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:494
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:479
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:487
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:327
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:379
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:455
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:296
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AddOnSkins, v4.39
  AtlasLootClassic, vv1.4.2
  AtlasLootClassicData, vv1.4.2
  AtlasLootClassicDungeonsAndRaids, vv1.4.2
  ATTClassic, v0.1.2
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  Carbonite, v@project-version@
  CarboniteNotes, v@project-version@
  CarboniteQuests, v@project-version@
  CarboniteSocial, v@project-version@
  CarboniteWarehouse, v@project-version@
  ClassicSpellActivations, v
  ClassicThreatMeter, v1.10
  Clique, vv1.0.3-classic
  DBMCore, v1.13.24
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.6
  ElvUI, v1.19
  ElvUILocationPlus, v1.01
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  ExtendedCharacterStats, v1.5
  FishingBuddy, v0.7 Beta 1
  GatherMate2, v1.45.5
  GTFO, v4.51
  honorspy, v1.6.7
  Informant, v8.2.6508 (SwimmingSeadragon)
  ItemRack, v
  LeatrixPlus, v1.13.40
  PallyPower, vv1.1c-classic 
  RealMobHealth, v2.17
  Recount, vv8.2.5d
  ShowMeMyHeal, v0.6.1
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Spy, v1.0.18
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TradeSkillMaster, vv4.8.24
  TradeSkillMasterAppHelper, vv4.0.6
  WeakAuras, v2.15.5
  WhatsTraining, v1.8.7
  WideQuestLog, v
  WIM, v3.8.4
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=68d)

  
  
  Error2:

  Date: 2019-12-15 12:50:30
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite\NxMap.lua line 4327:
   attempt to call global 'GetCurrencyInfo' (a nil value)
Debug:
   ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:732:
      ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:692
   [C]: GetCurrencyInfo()
   Carbonite\NxMap.lua:4327: Update()
   Carbonite\NxMap.lua:3922: OnUpdate()
   Carbonite\NxMap.lua:1387: MainOnUpdate()
   Carbonite\Carbonite.lua:1332: NXOnUpdate()
   [string "*:OnUpdate"]:1:
      [string "*:OnUpdate"]:1
Locals:
errMsg = "Interface\AddOns\Carbonite\NxMap.lua:4327: attempt to call global 'GetCurrencyInfo' (a nil value)"
tsmErrMsg = nil
oldModule = nil
private = <table> {
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:513
 num = 0
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:132
 hitInternalError = false
 origErrorHandler = <function> defined @Interface\AddOns\Decursive\Dcr_DIAG.lua:597
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:494
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:479
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:487
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:327
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:379
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:455
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:296
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AddOnSkins, v4.39
  AtlasLootClassic, vv1.4.2
  AtlasLootClassicData, vv1.4.2
  AtlasLootClassicDungeonsAndRaids, vv1.4.2
  ATTClassic, v0.1.2
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  Carbonite, v@project-version@
  CarboniteNotes, v@project-version@
  CarboniteQuests, v@project-version@
  CarboniteSocial, v@project-version@
  CarboniteWarehouse, v@project-version@
  ClassicSpellActivations, v
  ClassicThreatMeter, v1.10
  Clique, vv1.0.3-classic
  DBMCore, v1.13.24
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.6
  ElvUI, v1.19
  ElvUILocationPlus, v1.01
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  ExtendedCharacterStats, v1.5
  FishingBuddy, v0.7 Beta 1
  GatherMate2, v1.45.5
  GTFO, v4.51
  honorspy, v1.6.7
  Informant, v8.2.6508 (SwimmingSeadragon)
  ItemRack, v
  LeatrixPlus, v1.13.40
  PallyPower, vv1.1c-classic 
  RealMobHealth, v2.17
  Recount, vv8.2.5d
  ShowMeMyHeal, v0.6.1
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Spy, v1.0.18
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TradeSkillMaster, vv4.8.24
  TradeSkillMasterAppHelper, vv4.0.6
  WeakAuras, v2.15.5
  WhatsTraining, v1.8.7
  WideQuestLog, v
  WIM, v3.8.4
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=68d)

**Comment by IrcDirk** [comment]
Same as #113
