### ISSUE TITLE
Carbonite is causing frame rate issues

### ISSUE THREAD

**Issue by richjobes** [IrcDirk/Carbonite-Classic#117]
My frame rates are all normal without Carbonite enabled. As soon as I enable Carbonite my frame rate goes to crap. Any idea whats going on? It could be a certain combination of my add ons, but unsure which combination it could be. Was totally fine before the latest wow update.

**Comment by IrcDirk** [comment]
No issues on my side. Check only Carbonite + Modules enabled.
