### ISSUE TITLE
Carbonite's map interfering with blizzard's UI

### ISSUE THREAD

**Issue by Klala** [IrcDirk/Carbonite-Classic#118]
Not sure if anybody posted this already (I looked) but...

![](https://media.giphy.com/media/TLaYCQ3zSQWQRKnuXG/giphy.gif)

This is very annoying...

**Comment by cj1967** [comment]
I have same issue.

**Comment by Dokkasan** [comment]
Maybe by changing the layering would help?

**Comment by IrcDirk** [comment]
Yes, layering might be the issue... No time to fix this now.
