### ISSUE TITLE
Flight Paths/Zone Connections not Tracking Correctly

### ISSUE THREAD

**Issue by chuman72486** [IrcDirk/Carbonite-Classic#12]
It seems the coordinates for Flight Paths aren't set up correctly, so when I use a Flight Path, the tracking arrow seems to aim at the center of the entire world map, not the actual location of the flight.

**Comment by IrcDirk** [comment]
Yes, Flight Masters are not updated yet.

**Comment by IrcDirk** [comment]
Updated.

**Comment by chuman72486** [comment]
Now it's not tracking Flight Masters at all.  I just tried to fly back and forth between Menethil Harbor and Ironforge and it didn't track.

**Comment by chuman72486** [comment]
Flight Master icons also seem to show for the wrong faction...  I was trying to reach a new FP and almost ran into a Horde town...

**Comment by IrcDirk** [comment]
Updated. Now all should be ok.

**Comment by wtfaatp** [comment]
Still having the problem.. Latest down load as of 1 hour ago. 
![WoWScrnShot_091819_181217](https://user-images.githubusercontent.com/7692617/65195254-7a8de500-da4c-11e9-9d82-1a664e13e464.jpg)

**Comment by IrcDirk** [comment]
Thats not Flight Path ... thats zone connection which is wrong ;)

**Comment by IrcDirk** [comment]
Fixed.

**Comment by sanfair** [comment]
> Still having the problem.. Latest down load as of 1 hour ago.
It seems to me that the coordinates under the cursor is upside down (x become y, y become x)
But when I open blizzard map(Or Mapster i my case) they in right places (x is x, y is y)
![image](https://user-images.githubusercontent.com/20707205/65379113-9c48cf80-dccb-11e9-90b7-9ce460d89ad9.png)
![image](https://user-images.githubusercontent.com/20707205/65379093-758a9900-dccb-11e9-9ef4-c64adee40175.png)
On both pictures cursor on player

**Comment by IrcDirk** [comment]
Thats not the same issue.
