### ISSUE TITLE
Issue after coming back from Alterac valley

### ISSUE THREAD

**Issue by Srljm** [IrcDirk/Carbonite-Classic#121]
![CarboniteBug](https://user-images.githubusercontent.com/55985046/72363466-2db5d480-36f5-11ea-8936-0b9e5c1bbb8f.jpg)

This message is what I get in town after I have left the battleground. It is counting up endlessly and forces me to reload.
I only use the Carbonite Maps module (no loading for Notes, Quests etc)

**Comment by IrcDirk** [comment]
Duplicate #113
