### ISSUE TITLE
Carbonite breaking guild admin controls

### ISSUE THREAD

**Issue by chuman72486** [IrcDirk/Carbonite-Classic#122]
I get the following errors when trying to edit ranks in my new guild.  It seems that for some reason Carbonite is trying to change something in the guild controls, but it's a protected function.

```Date: 2020-01-20 10:08:48
ID: 1
Error occured in: AddOn: Carbonite
Count: 1
Message: Error: AddOn Carbonite attempted to call a forbidden function (GuildControlSetRank()) from a tainted execution path.
Debug:
   [C]: GuildControlSetRank()
   ..\FrameXML\FriendsFrame.lua:2516: func()
   ..\FrameXML\UIDropDownMenu.lua:958: UIDropDownMenuButton_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ACP, v3.5.6 
  AdvancedInterfaceOptions, v1.3.3
  Atlas, vv1.47.00.11303.00
  AtlasClassicWoW, vv1.47.00.11303.00
  AtlasLootClassic, vv1.4.5
  AtlasLootClassicData, vv1.4.5
  AtlasLootClassicDungeonsAndRaids, vv1.4.5
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  Carbonite, v@project-version@
  CarboniteQuests, v@project-version@
  CharacterStatsClassic, v3.1
  ClassicAuraDurations, v
  ClassicCastbars, vv1.2.3
  ClassicCastbarsOptions, v
  ClassicWorldMapEnhanced, v1.1-Release
  ColoredInventoryItems, v1.4
  DBMCore, v1.13.30
  DBMCountPackHotS, v1.7.5
  DBMCountPackOverwatch, v1.4.9
  DBMDefaultSkin, v
  DBMSMGEventsPack, v1.5.5
  DBMSoundEventsPack, v1.6.4
  DBMStatusBarTimers, v
  DBMVPVEM, v10.0.0
  DBMVPVV, v20190829
  DBMVPYike, v20190406
  DingAnnounce, v0.1
  EasyMail, v4.3
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExRT, v4110
  ExtendedCharacterStats, v2.1.3
  GatherMate2, v1.45.5
  Informant, v8.2.6374 (SwimmingSeadragon)
  LibSharedMedia30, v3.0-113
  MissingTradeSkillsList, v1.13.32
  OmniCC, v8.3.1
  QuestFrameFixer, v1.1.1
  QuestIconDesaturation, v3.1
  Questie, v5.5.1
  Recount, vv1.13.3b
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  VendorPrice, v1.3.0
  WhatsTraining, v1.8.7
  WideQuestLog, v
  WIM, v3.8.5
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=70c)
```

**Comment by chuman72486** [comment]
Somehow it seems Carbonite is tainting the guild and party interfaces.  I also get errors referencing Carbonite when I'm in a party, usually when something happens while I'm in combat, although I haven't figured out the source of that error.  It seems to be related to when someone's buffs change during a battle, but it doesn't happen every time.

**Comment by chuman72486** [comment]
This is still an issue.  When I try to change various Guild settings I either get errors about protected functions, or the Guild controls behave incorrectly, such as overwriting rank names with another rank, applying permissions to the wrong rank, etc.  If I disable Carbonite the issue goes away, so I know Carbonite is somehow the cause.

**Comment by IrcDirk** [comment]
Please provide error log. Im not guild master so i cant check it myself.

**Comment by chuman72486** [comment]
`
Message: [ADDON_ACTION_FORBIDDEN] AddOn 'Carbonite' tried to call the protected function 'GuildControlSetRank()'.
Time: Sun Jun  6 12:14:40 2021
Count: 1
Stack: [ADDON_ACTION_FORBIDDEN] AddOn 'Carbonite' tried to call the protected function 'GuildControlSetRank()'.
[string "@Interface\FrameXML\UIDropDownMenu.lua"]:960: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: <none>
`
If I try to click the Guild Control button and then select a different rank, this error appears and the game tells me I should disable the addon.   If I "ignore" the error and try to change anything on the other rank's permissions, it seems to merge the two ranks together, with permissions from the wrong rank being applied, even causing the Guild Master rank to lose permissions.  The key issue seems to stem from the above error, where it can't select the actual rank I want to edit.
I'm not sure why Carbonite even needs access to this function...maybe it can just be removed?

**Comment by IrcDirk** [comment]
Ok, ill will check this soon.

**Comment by IrcDirk** [comment]
Should be fixed and newest release.
