### ISSUE TITLE
NXMap and NXtravel - WoW-Pro incompatibility

### ISSUE THREAD

**Issue by draemen** [IrcDirk/Carbonite-Classic#123]
So I'm having a similar error and I understand this will be a duplicate however, I'm not using bagon, I'm not use Social/Punk or Warehouse.

I'm trying to copy and paste the error but the LUA error window won't scroll down so i can copy and paste.

Any help would be greatly appreciated 

![WoWScrnShot_012920_091400](https://user-images.githubusercontent.com/10390766/73360396-3243c680-4279-11ea-932e-a4fe8a1d3408.jpg)

**Comment by IrcDirk** [comment]
Disable all other addons and leave only Carbonite + Modules, check it this happens.

**Comment by draemen** [comment]
Well crap, Carbonite has a conflict with the WoW-Pro leveing guide. And that makes me extremely sad

**Comment by IrcDirk** [comment]
I was using it... was fine... maybe newer version broke something. Sorry have no time make fix for this incompatibility. Maybe in the future.

**Comment by draemen** [comment]
It's ok IrcDirk take you time, we all appreciate the work you do for Carbonite :)

**Comment by IrcDirk** [comment]
I think they fixed this on they side... I dont see this error now. Can anyone confirm this?
