### ISSUE TITLE
Carbonite causing frames to drop

### ISSUE THREAD

**Issue by Bloendro** [IrcDirk/Carbonite-Classic#124]
Hey as the title says Carb is casuing the frames to drop - I have nothing but Cabonite selected and frames are going from 60 to 30-35, also as you can see in the video - my map icons are missing as well (bank, mailbox, flightmaster)

A little more info I have found since posting: This issue seems to be isolated to my hunter - I cannot reproduce these issues on any other toon, I have completely uninstalled wow, removed all files and did a fresh install of everything, logging back in the FPS seems to be a bit better stable around 40 now but my map icons are all missing now, I've reset carb in every which way I found online and nothing seems to bring them back/fix the FPS on my hunter. 

Video showing issue

https://youtu.be/AKGNzywZxpM

**Comment by IrcDirk** [comment]
So did u found what was the problem?
