### ISSUE TITLE
Carbonite waypoints in Zygor Guides

### ISSUE THREAD

**Issue by Stellartois** [IrcDirk/Carbonite-Classic#125]
Carbonite waypoint used to work with Zygor but no longer does, is there anything on your end that you can do to make this work again

**Comment by IrcDirk** [comment]
Will check this in spare time.

**Comment by Woodwind800** [comment]
Is there any update with this being looked at?

**Comment by IrcDirk** [comment]
Sorry currently i dont have time for Carbonite... Please be patient. This isnt abandoned project.

**Comment by IrcDirk** [comment]
This is not Carbonite problem. WoWPro addons works with no problems. Please report this to Zygor they option to use /way doesnt work (opt_register_way_slash).

**Comment by IrcDirk** [comment]
They did changed something in Zygro. Need to make some work around to make this work again.

**Comment by Stellartois** [comment]
What work around will work

**Comment by IrcDirk** [comment]
"need to make work around" i need to code it :wink:

**Comment by Stellartois** [comment]
Oh I see... thank you very much

**Comment by IrcDirk** [comment]
Now Zygor waypoints should be set on Carbonite map,

**Comment by IrcDirk** [comment]
Can anyone test it on their side?

**Comment by Stellartois** [comment]
Is the map suppose to “waypoint” according to the current quest that the guide has for you?

**Comment by IrcDirk** [comment]
Yes. For me it now it works with Zygor guide.

**Comment by Stellartois** [comment]
Is that for classic as well... I went to go download it but it said I had current version

**Comment by IrcDirk** [comment]
Yes. But u need to download version from this repository. Ill upgrade it on Curse and WoWI later when im sure it works.

**Comment by Stellartois** [comment]
It works wonderfully thus far... thanks a bunch

**Comment by Woodwind800** [comment]
Works well for me as well thank you.

It does seem a little laggy in places though.

Would it also be possible to have world quests intergrated? As currently i cannot see them on my 120 character.

**Comment by IrcDirk** [comment]
Closing.

As for world quest they are implemented should work fine. Please open another issue for this and describe your problem.

**Comment by Stellartois** [comment]
So here is another question... it is running nicely with Zygor... is it designed to run with Dugi Guides

**Comment by IrcDirk** [comment]
No.

**Comment by marcodelmoral** [comment]
broken again with zygor

**Comment by IrcDirk** [comment]
@marcodelmoral Wdym? It works without any problems with Zygor, just tested...

**Comment by marcodelmoral** [comment]
> @marcodelmoral Wdym? It works without any problems with Zygor, just tested...

Routes from guides such as the mining one are not showing on the map, but they show on blizzards map.

**Comment by IrcDirk** [comment]
Routes are not waypoints... Sorry but im not implementing this to Carbonite right now...
