### ISSUE TITLE
Carbonite experiences large amount of errors when exiting a battleground

### ISSUE THREAD

**Issue by wiesshund** [IrcDirk/Carbonite-Classic#126]
Pasting a lua error below.
When you exit a BG like Arathi Basin, the game drops to single digit FPS
and carbonite experiences a constant slew of LUA errors

Message: Interface\AddOns\Carbonite\NxMap.lua:4327: attempt to call global 'GetCurrencyInfo' (a nil value)
Time: Fri Mar 13 03:20:01 2020
Count: 1918
Stack: Interface\AddOns\Carbonite\NxMap.lua:4327: attempt to call global 'GetCurrencyInfo' (a nil value)
Interface\AddOns\Carbonite\NxMap.lua:4327: in function `Update'
Interface\AddOns\Carbonite\NxMap.lua:3922: in function `OnUpdate'
Interface\AddOns\Carbonite\NxMap.lua:1387: in function `MainOnUpdate'
Interface\AddOns\Carbonite\Carbonite.lua:1332: in function `NXOnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: self = <table> {
 MiniBlks = 6
 IconScale = 3
 Scale = 5.200019
 MenuIShowWorld = <table> {
 }
 TextFrm = <unnamed> {
 }
 Targets = <table> {
 }
 ArchAlpha = 0.300000
 TrackETA = false
 GIconMenuITogInst = <table> {
 }
 BackgndAlpha = 0.400000
 TrackDir = false
 ArrowPulse = 1
 DotRaidScale = 1
 PlyrY = 807.894323
 MenuIShowMine = <table> {
 }
 PlyrRZY = 89.213759
 MMScalesC = <table> {
 }
 MapPosY = 807.894323
 LOpts = <table> {
 }
 Guide = <table> {
 }
 PlyrLastDir = 0
 WorldHotspots = <table> {
 }
 MapId = 1455
 TargetNextUniqueId = 1
 Size1 = 0.750000
 MMOwn = false
 TextFStrs = <table> {
 }
 Scrolling = false
 ShowUnexplored = false
 EffScale = 1
 Menu = <table> {
 }
 ScaleDrawW = 0.192307
 InstanceId = false
 Zone = 1455
 CurMapBG = false
 Cont = 2
 PIconMenu = <table> {
 }
 MMChkDelay = 24
 WorldAlpha = 0
 Level = 3
 StartupShown = false
 LocTipFrm = NxMapTip {
 }
 ScaleDraw = 5.200019
 PlyrSpeedY = 807.894323
 MapIndex = 1
 StepTime = 5
 BackgndAlphaFade = 0.400000
 PlyrFrm = <unnamed> {
 }
 GIconMenu = <table> {
 }
 IconWQFrms = <table> {
 }
 MoveLastX = 2253.272670
 IconStaticFrms = <table> {
 }
 UpdateTrackingDelay = 0
 IconNavScale = 1
 MapPosYDraw = 807.894323
 PlyrSpeedX = 2253.272670
 PlyrSpeed = 0
 IconFrms = <table> {
 }
 DebugAdjustScale = 0.100000
 MiniFrms = <table> {
 }
 PlyrDir = 0
 InCombat = false
 MapScale = 0.518964
 PlyrSpeedCalcTime = 6179.666000
 Win = <table> {
 }
 PadX = 0
 MenuIInstanceMaps = <table> {
 }
 RealScale = 5.200019
 Data = <table> {
 }
 LastDungeonLevel = 0
 BGIncNum = 0
 MenuIMonitorZone = <table> {
 }
 MapW = 245.539993
 ViewSavedData = <table> {
 }
 MMGathererUpdateDelay = 1
 MenuIShowTimber = <table> {
 }
 CurOverlays = false
 LClickTime = 0
 MouseEnabled = true
 LocTipFStrs = <table> {
 }
 TrackPlyrs = <table> {
 }
 ButAutoScaleOn = <table> {
 }
 BGIconMenu = <table> {
 }
 TextScFrm = <unnamed> {
 }
 MMOwnedFrms = <table> {
 }
 GIconMenuIFindNote = <table> {
 }
 MapH = 204.399994
 MMScales = <table> {
 }
 WorldHotspotsCity = <table> {
 }
 W = 150
 CurWorldUpdateMapId = 1461
 MapPosXDraw = 2253.272670
 Tracking = <table> {
 }
 MapPosX = 2253.272670
 BackgndAlphaTarget = 0.400000
 ContFrms = <table> {
 }
 TileFrms = <table> {
 }
 MoveDir = 180
 BGGrowBars = true
 TransMenu = <table> {
 }
 MapsDrawnOrder = <table> {
 }
 ArrowScroll = 0.400000
 MapsDrawnFade = <table> {
 }
 H = 141
 ScaleW = 0.192307
 UpdateTargetDelay = 0
 CurOpts = <table> {
 }
 MenuIPlyrFollow = <table> {
 }
 TitleH = 0
 BaseScale = 1
 ToolBar = <table> {
 }
 MoveLastY = 807.894323
 MenuIShowHerb = <table> {
 }
 Tick = 25460
 DotPartyScale = 1
 PlyrRZX = 69.915855
 PlyrX = 2253.272670
 QuestAlpha = 0.300000
 NeedWorldUpdate = false
 IconNIFrms = <table> {
 }
 BackgndAlphaFull = 1
 Frm = <unnamed> {
 }
 DotZoneScale = 1
 KillShow = false
 CurWorldUpdateOverlayNum = 0
 DotPalScale = 1
}
elapsed = 0.487000
Nx = <table> {
 GetDataToolBar = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1878
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:147
 Quest = <table> {
 }
 OnUnit_spellcast_sent = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1108
 IsGathering = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:3011
 prt = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:133
 BarData = <table> {
 }
 prtVar = <function> de

**Comment by wiesshund** [comment]
Message: Interface\AddOns\Carbonite\NxMap.lua:4355: attempt to call global 'GetCurrencyInfo' (a nil value)
Time: Fri Mar 13 02:39:30 2020
Count: 1
Stack: Interface\AddOns\Carbonite\NxMap.lua:4355: attempt to call global 'GetCurrencyInfo' (a nil value)
Interface\AddOns\Carbonite\NxMap.lua:4355: in function `Update'
Interface\AddOns\Carbonite\NxMap.lua:3922: in function `OnUpdate'
Interface\AddOns\Carbonite\NxMap.lua:1387: in function `MainOnUpdate'
Interface\AddOns\Carbonite\Carbonite.lua:1332: in function `NXOnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: self = <table> {
 MiniBlks = 6
 IconScale = 3
 Scale = 5.200019
 MenuIShowWorld = <table> {
 }
 Targets = <table> {
 }
 ArchAlpha = 0.300000
 TextFrm = <unnamed> {
 }
 TrackETA = false
 GIconMenuITogInst = <table> {
 }
 BackgndAlpha = 0.400000
 TrackDir = false
 ArrowPulse = 1
 DotRaidScale = 1
 PlyrY = 807.894323
 TargetNextUniqueId = 1
 MenuIShowMine = <table> {
 }
 MapId = 1461
 ScaleDrawW = 0.192307
 MMOwn = false
 TextFStrs = <table> {
 }
 PlyrLastDir = 0
 Scrolling = false
 MMScalesC = <table> {
 }
 InstanceId = false
 Menu = <table> {
 }
 LOpts = <table> {
 }
 Guide = <table> {
 }
 WorldHotspots = <table> {
 }
 ShowUnexplored = false
 EffScale = 1
 CurMapBG = true
 Cont = 4
 Size1 = 0.750000
 Zone = 1461
 PlyrRZY = 89.213759
 MMChkDelay = 1
 PIconMenu = <table> {
 }
 Level = 3
 WorldAlpha = 0
 MenuIInstanceMaps = <table> {
 }
 StartupShown = false
 ScaleDraw = 5.200019
 LastDungeonLevel = 0
 IconFrms = <table> {
 }
 LocTipFrm = NxMapTip {
 }
 StepTime = 0
 PlyrSpeedX = 2253.272670
 PlyrFrm = <unnamed> {
 }
 W = 150
 DebugAdjustScale = 0.100000
 MoveLastX = 2253.272670
 PlyrDir = 0
 PlyrSpeedCalcTime = 6179.666000
 IconNavScale = 1
 MapPosYDraw = 807.894323
 PlyrSpeedY = 807.894323
 PlyrSpeed = 0
 CurWorldUpdateMapId = 947
 BackgndAlphaFade = 0.400000
 MiniFrms = <table> {
 }
 MMOwnedFrms = <table> {
 }
 InCombat = false
 MapScale = 0.518964
 IconWQFrms = <table> {
 }
 Win = <table> {
 }
 PadX = 0
 IconStaticFrms = <table> {
 }
 RealScale = 5.200019
 Data = <table> {
 }
 UpdateTrackingDelay = 0
 BGIncNum = 0
 ViewSavedData = <table> {
 }
 MapW = 245.539993
 MapPosY = 807.894323
 MMGathererUpdateDelay = 1
 BGIconMenu = <table> {
 }
 CurOverlays = false
 LClickTime = 0
 MouseEnabled = true
 LocTipFStrs = <table> {
 }
 TrackPlyrs = <table> {
 }
 ButAutoScaleOn = <table> {
 }
 MapPosXDraw = 2253.272670
 MapH = 204.399994
 MapIndex = 1
 GIconMenuIFindNote = <table> {
 }
 TextScFrm = <unnamed> {
 }
 MMScales = <table> {
 }
 WorldHotspotsCity = <table> {
 }
 MenuIMonitorZone = <table> {
 }
 MenuIShowTimber = <table> {
 }
 ContFrms = <table> {
 }
 MapPosX = 2253.272670
 TileFrms = <table> {
 }
 BackgndAlphaTarget = 0.400000
 DotZoneScale = 1
 GIconMenu = <table> {
 }
 MapsDrawnOrder = <table> {
 }
 BGGrowBars = true
 MapsDrawnFade = <table> {
 }
 Tracking = <table> {
 }
 ArrowScroll = 0.830000
 TransMenu = <table> {
 }
 H = 141
 ScaleW = 0.192307
 Tick = 85
 CurOpts = <table> {
 }
 IconNIFrms = <table> {
 }
 TitleH = 0
 BaseScale = 1
 ToolBar = <table> {
 }
 MoveLastY = 807.894323
 MenuIShowHerb = <table> {
 }
 MoveDir = 180
 DotPartyScale = 1
 PlyrRZX = 69.915855
 PlyrX = 2253.272670
 QuestAlpha = 0.300000
 NeedWorldUpdate = false
 MenuIPlyrFollow = <table> {
 }
 BackgndAlphaFull = 1
 Frm = <unnamed> {
 }
 KillShow = false
 UpdateTargetDelay = 0
 CurWorldUpdateOverlayNum = 0
 DotPalScale = 1
}
elapsed = 0.068000
Nx = <table> {
 GetDataToolBar = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1878
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:147
 Quest = <table> {
 }
 OnUnit_spellcast_sent = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1108
 IsGathering = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:3011
 prt = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:133
 BarData = <table> {
 }
 prtVar = <function> defined @In

**Comment by wiesshund** [comment]
reloading UI clears it until you enter and exit another battleground.

Carbonite has all its modules enabled

**Comment by IrcDirk** [comment]
Duplicate #113 ... update from here.

**Comment by wiesshund** [comment]
@IrcDirk 
Hi, i dont want to reopen this, as grabbing source from here cured it.
But do you know why curse/twitch does not use your proper updated stuff?

Heh, it wants to go "update" carbonite with one that is outdated and would just give the problem back, which is probably how i wound up suddenly having the issue to begin with

**Comment by IrcDirk** [comment]
Thats becouse i dont have time lately to update Carbonite/Carbonite Classic.

**Comment by wiesshund** [comment]
Wish I understood add-ons a lot better, I would try to help out a little.Carbonite is a complicated add-on, I'd probably be a hindrance at best.On Mar 14, 2020 9:05 AM, Radek <notifications@github.com> wrote:
Thats becouse i dont have time lately to update Carbonite/Carbonite Classic.
