### ISSUE TITLE
Carbonite causing char to lag and blink

### ISSUE THREAD

**Issue by lazerbyte** [IrcDirk/Carbonite-Classic#127]
Carbonite just recently started to give lag and my character blinks in and out as I had to disable it. Just wanted to let you know an issue I was having.  I do have a gaming laptop with a Geoforce video card and I have google fiber net so I know that is not the issue as when carbonite is disabled I don't have any further issues!

**Comment by IrcDirk** [comment]
Retest it only with Carbonite + Modules enabled, it might be other addon incompatibilty.

**Comment by IrcDirk** [comment]
No reply. Closing.
