### ISSUE TITLE
Dark Map

### ISSUE THREAD

**Issue by Henchman284** [IrcDirk/Carbonite-Classic#128]
map is dark and you can't see anything.

**Comment by IrcDirk** [comment]
Just checked, all is fine. Disable all other addons leave only carbonite + modules and recheck. It might be incompatibility with other addon. If this still persists provide screenshot.

**Comment by IrcDirk** [comment]
No reply. Closing.

**Comment by Henchman284** [comment]
ok. thx for responding

 Rob   ¥ Henchman ¥    Dirty Dozen MC   


henchman284@yahoo.com

 

    On Monday, April 6, 2020, 11:25:57 PM MDT, Radek <notifications@github.com> wrote:  
 
 


Just checked, all is fine. Disable all other addons leave only carbonite + modules and recheck. It might be incompatibility with other addon. If this still persists provide screenshot.
