### ISSUE TITLE
Corpse Tracking not working

### ISSUE THREAD

**Issue by chuman72486** [IrcDirk/Carbonite-Classic#13]
While the tracking arrow works fine in the same zone, if you happen to mouse over another zone, the corpse mark moves to the equivalent coordinates in the wrong zone.  I'm assuming it's because the corpse coordinates are relative to the zone and not the entire world map, so it can't mark it correctly when another zone's map has focus.
Also the texture used to represent the corpse is wrong.

**Comment by IrcDirk** [comment]
Will fix this soon.

**Comment by Gyffes** [comment]
it is working for me fine :-)

**Comment by chuman72486** [comment]
Tracking is working now, but there's still a bug that the icon for your corpse shows up in the wrong spot if you mouse over another zone.

**Comment by IrcDirk** [comment]
Nope, thats fixed too.

**Comment by IrcDirk** [comment]
Update to latest version.
