### ISSUE TITLE
Carbonite map shows player dot in the wrong area.

### ISSUE THREAD

**Issue by BetaVirus** [IrcDirk/Carbonite-Classic#134]
Is anyone else having this issue? I see it on the laptop and desktop computer? It shows this on any areas i hover over.

![image](https://user-images.githubusercontent.com/13993587/80931287-08b5a200-8d76-11ea-840c-b9202cda2160.png)

**Comment by IrcDirk** [comment]
I think this is already fixed in Classic. Download latest version from this repositiory and check again.

**Comment by BetaVirus** [comment]
It was installed from Curse, Version 1.02; in game is shows 11 build 4eed1

**Comment by IrcDirk** [comment]
Alpha version with fix available here. Just download it.
