### ISSUE TITLE
Carbonite Classic map icons are missing.

### ISSUE THREAD

**Issue by Sweetsp08** [IrcDirk/Carbonite-Classic#135]
all the map and minimap icons for flight masters, boats/zeppelins, auctioneers, bankers, inns, mailboxes, etc. are nowhere to be found on my map or minimap. I've tried uninstalling and reinstalling the addon, and they show up for a second or two and immediately disappear. I logged onto a different character on the same realm and everything showed up.

**Comment by IrcDirk** [comment]
Of course u did disabled all other addons and checked this only with Carbonite + Modules enabled?

**Comment by Sweetsp08** [comment]
I've reset the Carbonite profile, and tried it on every character on every server with all other addons enabled and disabled. It only happens on my 48 gnome rogue. It's like after 5 seconds of being logged in it auto-unchecks the "Show POI" box in the maps options, but I look and it's still checked. And checking and unchecking it don't do anything.

**Comment by Sweetsp08** [comment]
I figured it out!! After reinstalling WoW Classic and having the issue persist, I tried untracking all my quests one by one, and found that "Crystals of Power", a quest in Un'Goro Crater, was causing all the map POI not to show up.
