### ISSUE TITLE
Herbs and veins not showing on map while struck in combat

### ISSUE THREAD

**Issue by romadurr** [IrcDirk/Carbonite-Classic#136]
For some reason, I can not see any nearby herbs/mines(depending which ability I activate) while I am struck in combat. As soon as I leave combat, they appear on my minimap. 
But it makes me miss some really often, especially at high lvl areas
Thx for your work :)

**Comment by IrcDirk** [comment]
Will check this in spare time, just be patient.

**Comment by IrcDirk** [comment]
![obraz](https://user-images.githubusercontent.com/1030023/211193585-a4d5236d-51ec-4d72-b85b-0ea9ed757ae6.png)

Works fine. Closing...
