### ISSUE TITLE
WoW Classic?

### ISSUE THREAD

**Issue by Karin-H** [IrcDirk/Carbonite-Classic#138]
Does Carbonite-Classic work with WoW classic, or did they both just like the word "classic"??
Thanks -

**Comment by IrcDirk** [comment]
What? 

Carbonite Classic is for official Blizzard WoW Classic servers.

**Comment by Karin-H** [comment]
That's great to know, thanks!
I got confused when I opened the zip file and saw stuff about quests way above WoW Classic lvls.
Nice to know Carb is there to shepherd me through the original game like it got me through Burning Crusade onward.
^_^
(and by "both" I meant WoW Classic and Carbonite Classic)
