### ISSUE TITLE
Gathermate2 data doesn't import

### ISSUE THREAD

**Issue by shinooni** [IrcDirk/Carbonite-Classic#140]
Hi,
Trying to import gathermate2 data doesn't seem to work.

When I Import it says 11547 nodes from carbonite.gathermate2_data have been imported. But on the map the nodes don't show up. 

I'll have attached an image showing the world map that displays the gathermate 2 data and the carbonite map that doesn't 
![Question](https://user-images.githubusercontent.com/653684/87880090-31bf0800-ca32-11ea-980e-160e722e2654.JPG)

When i compare the default file that comes with the module and the HerbalismData.lua that is generated by Gathermate it seems to contain different entries. 

I'll upload the herbalismdata.lua file as a .log file (github restrictions) if it helps.
[HerbalismData..log](https://github.com/IrcDirk/Carbonite-Classic/files/4944017/HerbalismData.log)

**Comment by IrcDirk** [comment]
What source of gathermate data do u use?

**Comment by shinooni** [comment]
Indeed Gathermate2 Classic

**Comment by IrcDirk** [comment]
Ok. So let me explain how import of G2 data in Carbonite works. 

It doesnt import data from G2 but from helper module Carbonite.Gathermate2_Data. Not all people can find good source of data for G2 so i did it for them. I dont remeber what source it was but it was accurate for the time i did used it.

But u can use your own source just replace HerbalismData.lua and MiningData.lua in Carbonite.Gathermate2_Data folder and import again. Those file have the same structure as G2 data.

**Comment by shinooni** [comment]
That is the exact process I did. Gathermate2 has the Gathermate2_Data folder - that is where I pulled the main two files from - merged the lua with the information provided on the classicguides.org site and then put the two lua files into Carbonite.Gathermate2_Data. 
Load the addon used for importing and click import - message pops up 11547 nodes from carbonite.gathermate2_data.
Untick and retick show herb - no new nodes. Logoff then exit client gracefully (through the menus) and started the client again. Untick and retick show herb still no new nodes.

**Comment by IrcDirk** [comment]
Ok, found the problem. Should be fixed and working now.

**Comment by IrcDirk** [comment]
But default data that comes with Carbonite.Gathermate2_Data Classic seems to be quite accurate.

**Comment by shinooni** [comment]
I'll check in 2 hours when I get home; I might end up just merging the black lotus locations with the default data provided with carbonite.Gathermate2_data

Thank you for the prompt reaction :-)

**Comment by IrcDirk** [comment]
Now u can use whatever data u want :)
