### ISSUE TITLE
Minion 3 lists the wrong version of carbonite in it's update for classic.

### ISSUE THREAD

**Issue by too2fun** [IrcDirk/Carbonite-Classic#141]
I use both twich and minion to update my add-ons, the version listed in Minion under the classic tab as an update for carbonite is the retail version, thus destroying the installed classic version.

**Comment by IrcDirk** [comment]
I did checked WoW Interface page of Carbonite Classic, latest version is for Classic: https://www.wowinterface.com/downloads/info25328-CarboniteClassicwithallmodules.html ... Are u downloading the right version?
