### ISSUE TITLE
Carbonite database update

### ISSUE THREAD

**Issue by Rhendak** [IrcDirk/Carbonite-Classic#143]
The Carbonite database seems to be missing about 40-50% of all quests in WoW classic. Not just in 1 zone, but across the entire game. It somehow feels less complete then it was when WoW classic came out. I'd like to request an update for the Carbonite database  so it contains at least 80-99% of the quests.

Screenshot for example, all the orange orbs is missing data. 
![image](https://user-images.githubusercontent.com/1855295/103245423-68456b00-4960-11eb-9125-2ff53f39dd33.png)

**Comment by macromaster2015** [comment]
I too have been having this problem and would love to get it fixed, especially with BC Classic coming.

**Comment by Rhendak** [comment]
Why was this issue closed? Has it been resolved?

**Comment by IrcDirk** [comment]
Yes, it has been updated. Use latest from this repo.
