### ISSUE TITLE
Enabling Carbonite classic disable system messages like /played

### ISSUE THREAD

**Issue by MedAmineAzaiez** [IrcDirk/Carbonite-Classic#144]
when i enable it i can't see system messages anymore, for example when i type /played it doesn't retun anything

**Comment by IrcDirk** [comment]
Works for me:

![obraz](https://user-images.githubusercontent.com/1030023/120478523-3ae86780-c3ad-11eb-83c7-78ee73c2e8ba.png)

**Comment by IrcDirk** [comment]
It might be other addon.
