### ISSUE TITLE
Game lagging (fps) with quest module enabled

### ISSUE THREAD

**Issue by Venkx** [IrcDirk/Carbonite-Classic#145]
As soon as I enable the quest module fps gets extremely low and is practically unplayable.
Just the map enabled works just fine

**Comment by IrcDirk** [comment]
Works with no problems on my side. U sure u are not on TBC beta?

**Comment by Venkx** [comment]
yeah pretty sure, ok let me check if it's some other addon interfering with carbonite, but I haven't changed anything, couldn't play for a week and the problems just started today, disabling the quest module fixed it.
WIll update in a few minutes if I find which addon causes it

**Comment by Venkx** [comment]
Ok that was quick, disabled all addons except carbonite maps and quest module, and it sill causes the problem.

I will try some things, when you say it works it just has to be something on my side

**Comment by Venkx** [comment]
I am pretty sure I tried everything except a clean wow install, and it sill causes lags, but I will just do that now, if that fails too I dont know what else I could do.

**Comment by Venkx** [comment]
ok sorry but nothing helps, clean install with only carbonite installed still lags with the quest module, as soon as I disable it it works.
Any ideas what else I could try?

**Comment by Venkx** [comment]
Even with the clean install it doesnt work, but I just noticed something, I accidentally pressed the button for "show quests on map" and the lag was gone, so the "real" problem might be the map when it shows the quest objectives
