### ISSUE TITLE
Kalimdor Maps don't line up correctly when zoomed in to details on TBC classic

### ISSUE THREAD

**Issue by ArcAios26** [IrcDirk/Carbonite-Classic#147]
on the Kalimdor map when you zoom down to detailed map the maps aren't lined up correctly. For instance, in Feralas if you zoom into camp mojache you are seeing the detailed map of the lower corner of ungoro crater instead

**Comment by IrcDirk** [comment]
Thanks for the info.

**Comment by IrcDirk** [comment]
Should be fixed => https://github.com/IrcDirk/Carbonite-Classic/commit/66fb430850401d286c62d2a5191d3e9b8fd18591
