### ISSUE TITLE
Will this mod be updated for TBC classic?

### ISSUE THREAD

**Issue by scoutsb** [IrcDirk/Carbonite-Classic#149]
Will this mod be updated for TBC classic?

**Comment by IrcDirk** [comment]
Its already updated to Pre-TBC and i have udpated map and quests so it should work on TBC start with no problems.

**Comment by scoutsb** [comment]
the map does not work.

**Comment by IrcDirk** [comment]
It works fine, playing it in Pre Patch right now.

**Comment by scoutsb** [comment]
well im not playing beta. the main map doesnt work when i hit the m key. nor does the punk list.  the option list is showing up but the main map isnt working.   ive uninstalled and reinstalled with all the other mods turned off and nothing. same deal. doesnt work.

**Comment by IrcDirk** [comment]
No one else is reporting this problem. U sure u are using the right version? 

Disable ALL OTHER ADDONS run only Carbonite. If there are problems there should be errors. Please provide log of those.

**Comment by DaveJ61** [comment]
Everything appears to be working fine for me and is actually even working in beta, so far.

**Comment by scoutsb** [comment]
im pretty sure its the right ver. its the only one on curseforge.

**Comment by IrcDirk** [comment]
I will close this soon. U are not providing enough info.

**Comment by scoutsb** [comment]
Carbonite-Classic-1.02.zip
in game it says, 113.0 build 436eed1 
ive deleted all other mods, and run just carbonite.  no errors are popping up. however the map still isnt working.  when i hit the m key i here the sound i should be, but the map itself isn't popping up. 

could it be something with my resolution setting, or something?

**Comment by IrcDirk** [comment]
Thats not for TBC ;)

**Comment by scoutsb** [comment]
ah,  guess that would do it then.  where can i get that ver?
cause the ver im on is the only on i can see on curse.

**Comment by IrcDirk** [comment]
U need to remove it and redownload verison 2.0. U can do it with Curse client or just go to => https://www.curseforge.com/wow/addons/carbonite-classic/files and replace all the files.

**Comment by scoutsb** [comment]
cool thanks

**Comment by scoutsb** [comment]
got it.  yay it works.  thanks bud.
