### ISSUE TITLE
Quest 0-20 

### ISSUE THREAD

**Issue by Gyffes** [IrcDirk/Carbonite-Classic#15]
hello and thank you for the addon. good work.

I noticed that some of the quest 0-20 are not in the database. 

I'll continue testing and reporting

thx

**Comment by IrcDirk** [comment]
Report quest Name/ID from WoWHead.

**Comment by Gyffes** [comment]
hi thx for quickly answer

I still have this one in log
https://de.classic.wowhead.com/quest=451/a-recipe-for-death
https://de.classic.wowhead.com/quest=5725/the-power-to-destroy

**Comment by IrcDirk** [comment]
The problem is on WoWHead side... No quest objectives are on WoWHead Map so Carbonite has no data to paint the blobs...

**Comment by Gyffes** [comment]
ok Thanks for Information.
