### ISSUE TITLE
Import quest data from questie

### ISSUE THREAD

**Issue by sungerbob** [IrcDirk/Carbonite-Classic#150]
Hi,
I just saw some quests is not showing on carbonite classic. After using questie addon for questing I saw nearly most of the quests is available on questie. I think it's great if questie quest data merged with carbonite-quest.

**Comment by IrcDirk** [comment]
Give me some examples please. I just updated Quest DB did u update?

**Comment by IrcDirk** [comment]
Quest database updated.
