### ISSUE TITLE
Does not show quest givers name on the map

### ISSUE THREAD

**Issue by sungerbob** [IrcDirk/Carbonite-Classic#151]
Hi,
Carbonite-tbc classic addon does not show quest givers name on the map. It shows only "?" name to all quest givers. I'm using 2.0.1 version from curseforge.
![11](https://user-images.githubusercontent.com/31207969/119260637-66fd2f00-bbdc-11eb-89f0-1e5b25a866b6.png)
![12](https://user-images.githubusercontent.com/31207969/119260639-68c6f280-bbdc-11eb-949e-9df5b0843f88.png)

**Comment by IrcDirk** [comment]
Ohhh yeah i forgot to export NPCs names data. Thanks will fix this soon.

**Comment by IrcDirk** [comment]
Fixed. Try latest version from this repository.

**Comment by sungerbob** [comment]
It's working thank you so much
