### ISSUE TITLE
Guide Issue on TBC? 

### ISSUE THREAD

**Issue by shinozuka75** [IrcDirk/Carbonite-Classic#152]
Long time user, love the features.  I am using the latest Curse version of Carbonite. I am standing in the Ghostlands and when I select to get the location of the nearest Banker Carbonite is pointing  me to the Undercity (6779 yards).  It says the nearest Mailbox is Eastern Plaguelands (80.9 58.6) . 

All the common places,  class trainers and profession trainers are giving me these results .  I decided to delete the addon manually and redownload . No chance. 

Any ideas?

**Comment by IrcDirk** [comment]
All Guides data needs to be updated. Ill will do it in incomming week.

**Comment by shinozuka75** [comment]
Thank you!

**Comment by Elimsmage** [comment]
IrcDirk, you are the best as well as all those who have developed this addon from the bad ole subscription days to the source code release and separating the modules etc etc. Don't think I'd have the energy for that ...lol.. in any case, hat's off and many thanks to all of you for keeping life in this fantastic addon. 

One thing, for some reason Curseforge app  is only showing the version 1 of the classic addon and not the 2. vers you can download. That is probably why some are having issues. Had it myself until I read the other post now closed. Don't know how much influence you have there but it would help clear out some peoples issues with the addon. Tnx again!

**Comment by IrcDirk** [comment]
Yeah... It seems bug in Curse app... other addons have same issue ;)

**Comment by IrcDirk** [comment]
Fixed. Try latest version from this repository.
