### ISSUE TITLE
Quest Investigate the Amani Catacombs sending me to incorrect place 

### ISSUE THREAD

**Issue by shinozuka75** [IrcDirk/Carbonite-Classic#153]
I got the quest Investigate the Amani Catacombs. Carbonite is sending me to Un'Goro Crater .  27.1K from where I am.    ;) 

https://www.wowhead.com/quest=9193/investigate-the-amani-catacombs

Have a nice day.

**Comment by IrcDirk** [comment]
Works fine for me. Try newest version from this repositiory.

**Comment by shinozuka75** [comment]
Ok it is working now. Thanks
