### ISSUE TITLE
Mining/Herbalism spots

### ISSUE THREAD

**Issue by Culliq** [IrcDirk/Carbonite-Classic#154]
Hello :)
I have an issue with gathering module :( when i mine a vein or pick up flower carbonite seems to not registering that and i can't see any icon on the mini-map after mining/harvesting. Is it something wrong with my addon options?
Thank you in advance for your help :D

**Comment by IrcDirk** [comment]
Works fine. 

1) Right Click Map -> Show... -> Show Mining Locations => check it
2) Right Click Map -> Transparency... -> Gather Icon Transparency => set to 1
3) Zoom in Map or set Gather Icon at Scale => Right Click Map -> Scale... -> Gather Icon at Scale
