### ISSUE TITLE
20 Max quests?

### ISSUE THREAD

**Issue by DarkInos** [IrcDirk/Carbonite-Classic#155]
Hello,
I'm a bit unsure as.. I see no one else mentioning this problem.. but my Carbonite (2.X v) for BC prepatch shows just 20 max quests, as TBC allowed us to get 25.. I was many times 21+/20.
It normaly does not cause issues, except when you are about to get a quest by event.
Escorts and such.. it always goes into (Your Quest log is full) and does not allow you to proceed with Q.
It is minor nuisance.. but I had to redo 3 escorts already on my Shaman.. waited for a update, that did not change anything so I am here :-)

![Carbonite](https://user-images.githubusercontent.com/6153995/119519352-a4e38a00-bd79-11eb-9cd5-34ffdbf3c01a.png)

**Comment by IrcDirk** [comment]
Yeah ill check this issue.

**Comment by IrcDirk** [comment]
Thats Blizzard BUG... hope they will fix it soon ;)

**Comment by DarkInos** [comment]
> 
> 
> Thats Blizzard BUG, gobal variable MAX_QUESTS i set to 20 ... hope they will fix it soon ;)

Without Carbonite I see max Quests 25.
In carbonite 20.
You set "20".
Do I miss something?

**Comment by IrcDirk** [comment]
Nope thats not how it works. There are two BLIZZARD global variables MAX_QUESTS and MAX_QUESTLOG_QUESTS. Blizzard forgot to change MAX_QUESTS to 20 and thats whats the problem, thats why u are getting "Your Quest log is full" messages. Carbonite has nothing to do with this. U can check this by yourself running /dump MAX_QUESTS .

**Comment by DarkInos** [comment]
Ahhh so that it is.. Thanks for the explanation!
Sorry I took your time :-)
Keep up great work!

**Comment by IrcDirk** [comment]
No problem :)
