### ISSUE TITLE
ElvUI MiniMap problem

### ISSUE THREAD

**Issue by Toetag1974** [IrcDirk/Carbonite-Classic#156]
Just downloaded carbonite for BC classic, and there is a big black non-interactive box in the middle of the mini map.
![WoWScrnShot_052721_124415](https://user-images.githubusercontent.com/74637048/119872846-856b6f00-bee9-11eb-89b9-d57b212c58b6.jpg)

**Comment by IrcDirk** [comment]
Thats becouse of ElvUI. Disable ElvUI minimap in ElvUI options.

**Comment by Toetag1974** [comment]
OK, thank you. Been a long time since I have used carbonite. Never used it with Elvui.
