### ISSUE TITLE
Auto Track turns off after every logout

### ISSUE THREAD

**Issue by 0ldi** [IrcDirk/Carbonite-Classic#158]
and it must be turned on manually again.

-If the quest is canceled, then when you take it again, it is not added to the list of tracked
-Probably the maximum number of quests should be 25?

![image](https://user-images.githubusercontent.com/16578229/120069727-09f7f200-c090-11eb-93e2-87876fcf41f7.png)

**Comment by IrcDirk** [comment]
Ill check it in spare time.

As to 25 quests see this => https://github.com/IrcDirk/Carbonite-Classic/issues/155
