### ISSUE TITLE
minimap elvui and carbonite integration

### ISSUE THREAD

**Issue by Gyffes** [IrcDirk/Carbonite-Classic#16]
hi

the integration of the carbonite map into the minimap of Elvui is not possible. The two addons are probably not compatible.

Thank you very much for the hard work

**Comment by IrcDirk** [comment]
U need to disable minimap integration in ElvUI then minimap will integrate with Carbonite.

**Comment by Gyffes** [comment]
That's right integration into the Elvui mini-map would be great. But that's just a nice to have.
and sorry for my bad english

**Comment by IrcDirk** [comment]
No problem, but im not planning integration with ElvUI.

**Comment by Gyffes** [comment]
ok thx i close the Issue :-)
