### ISSUE TITLE
FPS drop when quest module initializes

### ISSUE THREAD

**Issue by Jamminmon** [IrcDirk/Carbonite-Classic#160]
Hi,

This evening while loading in for about the 3rd time today, my FPS dropped substantially when the quest module initialized.

I did re install the addon, deleted settings and no changes. I can just disable the quest module and then everything is fine, so it is indeed the quest module causing the issue.

Regards

**Comment by IrcDirk** [comment]
So what FPS do u have without and with Quest module enabled?

**Comment by Jamminmon** [comment]
Hi,
Enabled 77 FPS / Disabled 120FPS(Native)

**Comment by IrcDirk** [comment]
Doesnt happen to me. How many quest u have in quest log? Do u have mining/herb nodes show on map?

**Comment by Jamminmon** [comment]
I've disabled everything, and have just the quests running and it lags a lot less, like up to 90 FPS but its still there. I'm not sure whats going on. Been fine for years and now its not. LoL. Maybe the next update will fix it ^_^

**Comment by IrcDirk** [comment]
Weird. I got 120FPS with 10 quests on map, but nodes disabled.

**Comment by Jamminmon** [comment]
Hi,
This last comment of yours gave me an idea.
So everything is now running fun with all modules initialized. It seems that the lag increases more if there are more quests being tracked. With each quest a little more lag happens. 1 quest tracked = 2-3 FPS. No quests Tracked = 0 FPS Reduction

**Comment by IrcDirk** [comment]
Show me a screenshot of your Ungoro map with quests watched.

**Comment by Jamminmon** [comment]
![WoWScrnShot_060121_175216](https://user-images.githubusercontent.com/85077550/120353806-39159a00-c302-11eb-81d7-8d685bc98a5b.jpg)

**Comment by Jamminmon** [comment]
Im in Ungoro now, Im not sure what I've done, but my FPS is Native and Im tracking 11 quests on mini-map, I think it had something to do with a specific quest, because I've completed some.

**Comment by IrcDirk** [comment]
It seems its baceuse one quest has big quest area on map. When u finished it when to normal.

**Comment by IrcDirk** [comment]
Made some changes to quest areas, should be better now => https://github.com/IrcDirk/Carbonite-Classic/commit/8531576eb3ba3327a9596125a7ed76c3c76af14f

**Comment by Jamminmon** [comment]
Its much better now.. Im in blasted lands now with alot of quest tracking on the mini map and its great. Thank you for your help, Im glad a resolution was found :) I'll let you know if it happens again, though I don't think it will :)
