### ISSUE TITLE
Missing quest objective - [52] Extinguish the Firegut

### ISSUE THREAD

**Issue by crestcere** [IrcDirk/Carbonite-Classic#163]
Wowhead link: https://classic.wowhead.com/quest=3823/extinguish-the-firegut
As you can see in images I can't see quest objective in carbonite map. It's not low level quest and all 40-50, 50-60 quest databases loaded in carbonite setting.
![Screenshot 2021-06-02 221425](https://user-images.githubusercontent.com/31207969/120749511-6a15ea80-c50d-11eb-9fca-3a320674d6e3.png)
![Screenshot 2021-06-02 221443](https://user-images.githubusercontent.com/31207969/120749518-6e420800-c50d-11eb-9060-392afb5d1dc8.png)

**Comment by IrcDirk** [comment]
I will be updating Quest DB once in a month. So please be patient.
