### ISSUE TITLE
Missing quest objective - [52] Clear the Way

### ISSUE THREAD

**Issue by crestcere** [IrcDirk/Carbonite-Classic#164]
Wowhead link: https://classic.wowhead.com/quest=5092/clear-the-way
Quest objective did not show up in carbonite. 40-50, 50-60 quest databases loaded in settings.
![Screenshot 2021-06-03 000442](https://user-images.githubusercontent.com/31207969/120749875-017b3d80-c50e-11eb-9805-56b1c2b43855.png)
![Screenshot 2021-06-03 000458](https://user-images.githubusercontent.com/31207969/120749786-d7c21680-c50d-11eb-941a-4517e8b5102c.png)

**Comment by IrcDirk** [comment]
I will be updating Quest DB once in a month. So please be patient. Thank u for reporting.
