### ISSUE TITLE
Missing quest giver location - [52] It's a Secret to Everybody

### ISSUE THREAD

**Issue by crestcere** [IrcDirk/Carbonite-Classic#165]
Wowhead link: https://classic.wowhead.com/quest=3845/its-a-secret-to-everybody

I enabled quest giver setting in carbonite. As you can see in image it did not show quest giver location in carbonite map.

![Screenshot 2021-06-01 223130](https://user-images.githubusercontent.com/31207969/120750028-499a6000-c50e-11eb-8ff7-9cc31142e576.png)
![Screenshot 2021-06-01 223109](https://user-images.githubusercontent.com/31207969/120750031-4b642380-c50e-11eb-97e0-61d002eff285.png)

**Comment by IrcDirk** [comment]
I will be updating Quest DB once in a month. So please be patient. Thank u for reporting.
