### ISSUE TITLE
Linking Quest with Carbonite Quest-UI not possible (Questie installed)6

### ISSUE THREAD

**Issue by avveka** [IrcDirk/Carbonite-Classic#168]
Hello!

I got Questie and Carbonite - both up to date. When Carbonite loads its Quest-UI im no longer able to link a Quest. Few seconds before (when i got the original wow Quest-UI it works!).

Can you fix it?

**Comment by IrcDirk** [comment]
I will check it in spare time.

**Comment by IrcDirk** [comment]
How do u try to link the quest? U got both Questie and Carbonite enabled?

**Comment by avveka** [comment]
Yes both enabled. Posting works few seconds before carbonite Quest UI loaded. After that it wont work anymore.Am 28.06.2021 09:12 schrieb IrcDirk ***@***.***>:
How do u try to link the quest? U got both Questie and Carbonite enabled?

**Comment by IrcDirk** [comment]
Sorry i dont really understand? U are using Questie Tracker or Carbonite Quest Tracker to link quest?

**Comment by avveka** [comment]
I use the carbonite QuestLog to link quest. But i have also questie installed.Am 28.06.2021 12:13 schrieb IrcDirk ***@***.***>:
Sorry i dont really understand? U are using Questie Tracker or Carbonite Quest Tracker to link quest?

**Comment by IrcDirk** [comment]
Questie linking will not work in Carbonite Quest Tracker those are different addons. 

But Carbonite has its own functionality for this. U can link quest to chat by Shift+Right Click the dot beside quest in Carbonite Quest Tracker.
