### ISSUE TITLE
Map No Longer Replaces Blizzard UI (TomTom Related)

### ISSUE THREAD

**Issue by NerpxTheTurtle** [IrcDirk/Carbonite-Classic#169]
Hi. Over the past couple days, my carbonite map fails to show up when pressing the "M" key. I've verified several times that the option for replacing the Blizzard UI map is checked. I just reinstalled Carbonite maps to verify that there's not a missing file. The only way I'm able to get the large map to show up is by right clicked the minimap tooltip and pressing "Show Map."

**Comment by NerpxTheTurtle** [comment]
It appears that after turning off "TomTom Addon Suite", the map function started behaving normally.

**Comment by IrcDirk** [comment]
If u have enabled Carbonite u dont have to use TomTom. It has build in TomTom emulation, so all navigation goes trough Carbonite maps.
