### ISSUE TITLE
The quest tracker disappeared from my screen

### ISSUE THREAD

**Issue by Galenthor** [IrcDirk/Carbonite-Classic#170]
I have done everything I could to try to figure this out, including deleting the addon, rebooting my comp, then going to reinstall it again, and nothing seem to bring the quest tracking back up; I have looked through all of the options to see if there is or could be set any keybinds for it, didn't find one... thoughts?

**Comment by IrcDirk** [comment]
Disable all other addons, just leave Carbonite + modules. If that doesnt help reset profile settings.

**Comment by Galenthor** [comment]
ok, got it figured out...  found a way to delete my settings, and now it came back...
