### ISSUE TITLE
Blizzard map showing when in combat

### ISSUE THREAD

**Issue by mondvrr** [IrcDirk/Carbonite-Classic#171]
When i'm in combat and i press M blizzard's map show up instead of carbonite, also if i have the talents or the character screen and i open the map, and then i try to close it again pressing M, it doesn't close until i close the character or talent screen. I tried disabling the rest of the addons and the carbonite modules aswell but it doesn't work

**Comment by IrcDirk** [comment]
Should be fixed. Please confirm.
