### ISSUE TITLE
'Carbonite' tried to call the protected function 'CompactRaidFrame1:Show()'.

### ISSUE THREAD

**Issue by Pow761** [IrcDirk/Carbonite-Classic#172]
im getting this quite often 

 
1x [ADDON_ACTION_BLOCKED] AddOn 'Carbonite' tried to call the protected function 'CompactRaidFrame1:Show()'.

 

TBC Classic

**Comment by IrcDirk** [comment]
Please post the full error log.

**Comment by Pow761** [comment]
This is the full log i get 

1x [ADDON_ACTION_BLOCKED] AddOn 'Carbonite' tried to call the protected function 'CompactRaidFrame1:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\CompactUnitFrame.lua"]:359: in function `CompactUnitFrame_UpdateVisible'
[string "@FrameXML\CompactUnitFrame.lua"]:292: in function `CompactUnitFrame_UpdateAll'
[string "@FrameXML\CompactUnitFrame.lua"]:125: in function <FrameXML\CompactUnitFrame.lua:53>

**Comment by IrcDirk** [comment]
Thats error from BugGrabber.

pt., 2 lip 2021, 16:56 użytkownik Pow761 ***@***.***> napisał:

**Comment by IrcDirk** [comment]
Thats error from BugGrabber.

**Comment by Pow761** [comment]
Ah ok, thats my bad then, sorry for the inconvenience

**Comment by IrcDirk** [comment]
No problem.
