### ISSUE TITLE
Flight Paths not Taken into consideration

### ISSUE THREAD

**Issue by noahgithub** [IrcDirk/Carbonite-Classic#175]
When calculating the fastest route between destinations the availability of flight paths is not taken into consideration.  It now always gives you the route for walking only.

**Comment by noahgithub** [comment]
Is this as intended?

**Comment by noahgithub** [comment]
One of the string points for carbonite for me was that it gave the fastest path to a destination and it kept extra knot what flight points you had and would give you the route based on that data. I don’t know when it stopped, but it no longer does this. It seems like it would work by storing your flight path data  just like warehouse works by storing bag and bank data. I don’t know how it was done, just that it was before.

**Comment by IrcDirk** [comment]
@artscout Just checked thats not the problem (line 453)... Saved flight master names are different then those in FlightMaster db file ;)

**Comment by artscout** [comment]
Ahhh ok I didn't check that part yet as I'm in raid currently

**Comment by IrcDirk** [comment]
Should be fixed but FlightMaster.lua needs an update.

**Comment by noahgithub** [comment]
I am excited to see this working, how would I go about testing this?  Is there a download link I can try?

**Comment by artscout** [comment]
Where exactly did you test it? Also I think that it won't show you FP if you have flying skill and your current position is somewhetre in Outlands

**Comment by artscout** [comment]
I'll be testing it now too.

**Comment by noahgithub** [comment]
Tested it in outlands, level 61, No Flying skill.  Just between Shattrath and Honor Hold and Telhamat Temple.  Going to IF to sell a few things, will test there to see if anything pops.

**Comment by noahgithub** [comment]
In Ironforge It still doesn't track FlightPoints fully.  But there is imporvement.  It ignored the FP in IF but then offered to run to the FP in LochModan and then fly to the Aerie Peak FP.  So not everything is right, but its getting closer.

**Comment by artscout** [comment]
Well I tested myself and first you have to talk to FlightMaster on every continent on you character first so it could populate database of known and unrestricted flight masters to fly to, otherwise it doesn't know which flyght master is allowed to use and fly to.

**Comment by artscout** [comment]
Every time you talk to flymaster it goes and checks if there's any update for flight path available. But I thik that I need to check if some flightmasters are bugged.

**Comment by noahgithub** [comment]
Try Ironforge, I have talked to the FlightMaster and it definitely still will not suggest that FP as a start. If there is anything I can try for you guys let me know.

**Comment by artscout** [comment]
Yeah I gues we'll have to check every Flight Master there. Also I fount that localization too may discrupt everything as for some languages there are different localizations were made in the past and we have to find correct values too. darn.

**Comment by artscout** [comment]
Now, I've tested my theory about localizations and sadly it proven as true. Trouble is that database of accessible flightmasters filled with localized locations as they named by game localizations. Those are changed in some expansions and are not always correct. Even original names could be incorrect thus requiring us to check it too.

**Comment by artscout** [comment]
BTW are you playing with original locale or some other?

**Comment by noahgithub** [comment]
Original English

**Comment by IrcDirk** [comment]
Yeah, some Filght Masters might need to be updated in localizations or in FlightMaster.lua

**Comment by IrcDirk** [comment]
FlightMasters.lua should be OK now, but in locales need to be updated to make it work.

@noahgithub Ironforge should be OK ;)

**Comment by artscout** [comment]
Checked over PTR version (as it's the only way I can have my character with all Alliance FlightMasters open to check in English), everything seems fine except Wetlands FlightMaster location, fixed that up there with merge request.

**Comment by IrcDirk** [comment]
@artscout Accepted your pull. Wrong algorithm for converting coordinates so i fixed it added new FilghtMaster.lua (only coordinates changed for some FlightMasters)/

**Comment by noahgithub** [comment]
Will test the new merge today. Thank you for not letting this bug sit. It’s my favorite add on and this only makes it better again. 

Noah

**Comment by noahgithub** [comment]
This seems to work for the FP I have now.  I will let you know if I find any that are broken.,  Thanks you for the fix!  It might be worth updating CurseForge for others who have this issue and don't realize it.

**Comment by IrcDirk** [comment]
Will update curse and wowi ;)
