### ISSUE TITLE
Docked Minimap is black (blank)

### ISSUE THREAD

**Issue by mattlokk** [IrcDirk/Carbonite-Classic#179]
Whenever I go inside or in an instance, the docked minimap is just a black square.

If I toggle "full size" it will fix itself for a short period, but it will always go back to being blank. Usually in less than a minute. It works as long as I stay still, but if I move around it always goes away.

I tried disabling all my other addons and get the same behavior.  Tried changing all the transparency settings to no effect

![image](https://user-images.githubusercontent.com/3373299/125346092-2bdec880-e30e-11eb-9701-8bb150193e59.png)

**Comment by Galenthor** [comment]
I have this problem as well, very confused by it

**Comment by Galenthor** [comment]
went into an instance last night, while it wasn't black, it still refuses to go full size, no clue why, and not gettign an error msg about it

**Comment by Galenthor** [comment]
sadly, this is still an ongoing issue...
