### ISSUE TITLE
Tracker and Map Options

### ISSUE THREAD

**Issue by YoungGooby** [IrcDirk/Carbonite-Classic#181]
I've been using carbonite for a little while and really like it. So, I have a question/suggestion.

Here is what my UI looks like outside of combat:
https://i.imgur.com/jTH6trI.jpeg

Here is what my UI looks like in combat:
https://i.imgur.com/w0u1hoK.jpeg

The tracker disappears as I have set and I have set the map to hide as well and it doesn't. Is there a way to fix this?

Also, is there or could there be an option to hide map and tracker inside of dungeons and raids? Or maybe detect it's in a dungeon hide the map and tracker then open Atlas (the dungeon map addon) instead when you press M?

Thanks.

**Comment by IrcDirk** [comment]
> I have set the map to hide as well and it doesn't

This setting is for the BIG map not minimap. There is no such option for Minimap.
