### ISSUE TITLE
Guild Bank

### ISSUE THREAD

**Issue by Fatherknight** [IrcDirk/Carbonite-Classic#182]
The Guild Bank was added to Classic and since then when you try to put an item in the Guild Bank or try to work the Guild Controls or Guild Bank Control, its asking to Disable Carbonite and puts a black line across the screen about 1" x 12", if you disable Carbonite it don't help still unable any of the Controls.

Thanks
Fatherknight

**Comment by IrcDirk** [comment]
So thats another addon. Just disable one by one.
