### ISSUE TITLE
2.5.2 game version does not let me use Carbonite

### ISSUE THREAD

**Issue by Damorka** [IrcDirk/Carbonite-Classic#183]
Since game was updated to 2.5.2  version WoW does not allow me to use carbonite
If I load it as out of date addon minimap is separate from Carbonite
And instead of Carbonite map classic WoW map opens
Can this be fixed pls?

**Comment by IrcDirk** [comment]
I dont play WoW Retail right now ... so no active subscription right now. Need to think about it...

**Comment by IrcDirk** [comment]
Apart of "out of date" addon works without problems in 2.5.2

**Comment by IrcDirk** [comment]
"Out of date" fixed in => https://github.com/IrcDirk/Carbonite-Classic/commit/5b551437051c6853404cb985f81889c34a6a6f78
