### ISSUE TITLE
Carbonite preventing map from opening when in combat

### ISSUE THREAD

**Issue by tms64690206** [IrcDirk/Carbonite-Classic#185]
Confirmed this by disabling all apps except Carbonite.  Map will not open while in combat.  Disabled Carbonite and entered combat and was able to open map.  The option to hide map while in combat is deselected in Carbonite.  I get a message in my dialogue box "Interface action failed because of an AddOn."

**Comment by artscout** [comment]
I'm investigating this now, but TBC classic does not show the cause for interface error and taint logging doesn't help either so it could take a while for me to find it.

**Comment by IrcDirk** [comment]
Taint logs should work in TBC Classic https://wowpedia.fandom.com/wiki/CVar_taintLog ;)

**Comment by artscout** [comment]
Yep iot works when you set it up to 2. Now I'm working on fix
