### ISSUE TITLE
Minimap-Button-Window coexistence with Questie

### ISSUE THREAD

**Issue by Malspherus** [IrcDirk/Carbonite-Classic#186]
Symbols that Questie shows on the minimap are moved into Carbonites minimap-button-window unless the character is moving, in which case they are correctly shown in the minimap until the character stops moving again.

Currently on Carbonite 113.0 and Questie 6.6.0, but this problem existed since forever

![grafik](https://user-images.githubusercontent.com/5000275/135283121-755ecbd2-2816-4a2d-8808-bdf1bc1b102b.png)

**Comment by Malspherus** [comment]
This issue is still relevant in the WotLK prepatch with with v3.4.0. It also (kind of) relates to #223

**Comment by IrcDirk** [comment]
Fixed Questie icons, now they are not showing in Docked Icons of Carbonite.

**Comment by Malspherus** [comment]
I can confirm the problem is fixed in the current version, thank you for your work!
