### ISSUE TITLE
mini map issue

### ISSUE THREAD

**Issue by krzykjn1** [IrcDirk/Carbonite-Classic#189]
My mini map has no details on the map all the time. this problem is different on each Character. as of the moment in order to use the map I have to scroll out to see where i am on the map, but cannot see the area i am in as far as roads, cities, and areas for quests. I need to fid a way to get the details of the map area when zoomed in. any help will be appreciated.

**Comment by IrcDirk** [comment]
Please provide screenshots. Try without any other addons enabled only Carbonite.

**Comment by krzykjn1** [comment]
![inside IF zoomed out just moved the mouse over IF](https://user-images.githubusercontent.com/29016075/138027889-d77693e3-daec-4cad-8ed3-05a5950c10ac.jpg)
![inside IF zoomed out](https://user-images.githubusercontent.com/29016075/138027902-682ef43b-f1de-4fe2-9013-92ad48290da0.jpg)

![inside IF](https://user-images.githubusercontent.com/29016075/138027912-0ffaca31-a563-4602-85dc-df6c6c8a2d15.jpg)
![out side IF](https://user-images.githubusercontent.com/29016075/138027921-68644fe1-0f60-46a0-90eb-fb0b97ef09d5.jpg)
![outside IF 2](https://user-images.githubusercontent.com/29016075/138027932-8e46ff0f-ca81-407e-8ee2-3e64185b032d.jpg)
![outside IF 3](https://user-images.githubusercontent.com/29016075/138027941-6e84b1f5-fe3d-4609-a719-b8d5a76caee9.jpg)
