### ISSUE TITLE
dang patch breaking Carbonite again

### ISSUE THREAD

**Issue by Galenthor** [IrcDirk/Carbonite-Classic#191]
after this last patch/maintenance, the quests aren't showing on the map anymore, and the hide quests not in zone doesn't work anymore regardless of what I do, including reinstalling the addon... thoughts?

**Comment by Conan1996-2** [comment]
No, Classic Era... What I had to do was manually download 2.08 and unzip that version into classic era, set ALLOW all outdated addons to work (I am to lazy to edit the TOC file) to work.

Classic Era has updated to 1.14.1

**Comment by IrcDirk** [comment]
I wrote before i don't support Classic Era.

**Comment by Conan1996-2** [comment]
I'm not sure if you are aware, they are doing an event/server wipe for classic era.

**Comment by IrcDirk** [comment]
I will not maintain 3 versions of Carbonite. I barely have time for two.

**Comment by Conan1996-2** [comment]
I get it, I have addons for both versions...  but with my addon I just have to switch the game numbers. It works in both Era and BC... I understand yours is more detailed with map changes, Quests, etc. But Like I said earlier for anyone else reading, All I did was download your latest TBC version, manually install it.
