### ISSUE TITLE
Carbonite breaks blizz big map

### ISSUE THREAD

**Issue by Basskasa** [IrcDirk/Carbonite-Classic#192]
![image](https://user-images.githubusercontent.com/92186427/148224123-eef68769-4643-4d98-89c0-fb88e50cae85.png)
Opening the blizz map (alt+m) with carbonite enabled causes it to open off-center and on some zones half the map is hidden

**Comment by IrcDirk** [comment]
I dont see whats wrong...

**Comment by Basskasa** [comment]
![image](https://user-images.githubusercontent.com/92186427/148225396-f7047e54-3691-406d-a096-d8942d29af59.png)
How it normally looks.

**Comment by IrcDirk** [comment]
Works fine on my side... Try running WOW + only Carbonite and its modules enabled. It might be other addon.

**Comment by Basskasa** [comment]
yes it is tbc and running only carbonite didn't fix it.

**Comment by Rozzemak** [comment]
Looks like scaling issue. Try disabling/enable scaling under wow.exe properties // Enable ui scaling in wow.
