### ISSUE TITLE
trying to set focus on a mate.  this is an error code  please help

### ISSUE THREAD

**Issue by mypandora1** [IrcDirk/Carbonite-Classic#194]
Date: 2022-03-09 10:25:00
ID: 1
Error occured in: AddOn: LFG113
Count: 1
Message: Error: AddOn LFG113 attempted to call a forbidden function (FocusUnit()) from a tainted execution path.
Debug:
   [string "=[C]"]: FocusUnit()
   [string "@Interface_TBC\FrameXML\UnitPopup.lua"]:1954:
      Interface_TBC\FrameXML\UnitPopup.lua:1693
   [string "=[C]"]: func()
   [string "@..\FrameXML\UIDropDownMenu.lua"]:942: UIDropDownMenuButton_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
None
AddOns:
  Swatter, v2.5.6773 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.7.0
  Atlas, vv1.50.02
  AtlasBurningCrusade, vv1.50.00
  AtlasClassicWoW, vv1.50.00
  AtlasDungeonLocs, vv1.50.00
  AtlasTransportation, vv1.50.03
  AtlasLootClassic, vv2.4.1-bcc
  AtlasLootClassicData, vv2.4.1-bcc
  AtlasLootClassicDungeonsAndRaids, vv2.4.1-bcc
  AucAdvanced, v2.5.6733 (SwimmingSeadragon)
  AucFilterBasic, v2.5.6759 (SwimmingSeadragon)
  AucStatHistogram, v2.5.6761 (SwimmingSeadragon)
  AucStatiLevel, v2.5.6765 (SwimmingSeadragon)
  AucStatPurchased, v2.5.6762 (SwimmingSeadragon)
  AucStatSimple, v2.5.6763 (SwimmingSeadragon)
  AucStatStdDev, v2.5.6764 (SwimmingSeadragon)
  AucUtilFixAH, v2.5.6766 (SwimmingSeadragon)
  Auctionator, v9.2.2
  BagBrother, v
  Bagnon, v9.1.4
  BagnonItemLevel, v1.0.47-Release
  Bartender4, v4.11.1
  BeanCounter, v2.5.6767 (SwimmingSeadragon)
  Carbonite, v@project-version@
  CarboniteNotes, v@project-version@
  CarboniteQuests, v@project-version@
  CarboniteSocial, v@project-version@
  CarboniteWarehouse, v@project-version@
  ClassicCastbars, vv1.4.4
  DBMCore, v80137cb
  DBMSpellTimers, vr138
  DBMStatusBarTimers, v80137cb
  DBMVPVEM, v4462b1d
  Decursive, v2.7.8.5
  Enchantrix, v2.5.6768 (SwimmingSeadragon)
  EnchantrixBarker, v2.5.6769 (SwimmingSeadragon)
  GTFO, v4.66
  HandyNotes, vv1.6.5
  HealBot, v2.5.3.7
  HealBotData, v2.5.3.7
  HealBoten, v2.5.3.7
  HealBotExtraSkins, v2.5.3.0
  HealBotOptions, v2.5.3.7
  HealBotTips, v2.5.3.7
  HHTD, v2.4.9.11
  Informant, v2.5.6770 (SwimmingSeadragon)
  ItemRack, v
  LFG113, v
  MaxCam, vv2.5.9
  Pawn, v2.5.31
  QuestCompletist, v109.35
  Recount, vv2.5.3c
  Scrap, v9.1.2
  SlideBar, v2.5.6771 (SwimmingSeadragon)
  SpeedyAutoLoot, v2.1.8
  Stubby, v2.5.6772 (SwimmingSeadragon)
  ThreatClassic2, v2.42
  TomTom, vv3.0.6
  TotemCaddy, v2.53
  TotemTimers, v2.0.3
  WhatsTraining, v3.0.0
  BlizRuntimeLib_enUS v2.5.3.20503 <none>
  (ck=782)

**Comment by IrcDirk** [comment]
**AddOn LFG113** attempted to call a forbidden function (FocusUnit()) from a tainted execution path.

Thats not Carbonite ;)
