### ISSUE TITLE
Probably bug?

### ISSUE THREAD

**Issue by sanfair** [IrcDirk/Carbonite-Classic#20]
Look at [30220 line in this commit](https://github.com/IrcDirk/Carbonite-Classic/commit/5925bced9cfdce860f33f8d8b433bb793f03cda0#diff-39d93f5f50ca1b3757b45eb90481fb7fR30220). Don't sure but think [this](https://github.com/IrcDirk/Carbonite-Classic/commit/657b2614a3d7bdf176199cde90530d6692450fe5)  related to it.

**Comment by IrcDirk** [comment]
Thanks, but im already on that ;)
