### ISSUE TITLE
Map Position not correct

### ISSUE THREAD

**Issue by erazor9000** [IrcDirk/Carbonite-Classic#203]
In normal Map View everything is fine. But when i zoom in for the minimap view, the map view is moved to south east.
This problem exists since Version 2.1.0. in version 2.0.8 both views are fine

Example at the Position Crossroads in Map View https://ibb.co/Zzkb00g shows the entrance from the barrens to mulgore in minimap view https://ibb.co/sVKSw82

**Comment by IrcDirk** [comment]
Yeah @artscout changes ids to new continent map. Please go back to old ones those new ones are bigger and can lower fps.

**Comment by artscout** [comment]
Ok will do that.

**Comment by artscout** [comment]
Now that done and I see what you mean. Changed to old, they're smaller and has no issues after that

**Comment by IrcDirk** [comment]
Thanks. Will send fixed release to curse.

**Comment by spinshock** [comment]
Still have this issue with v2.1.1

Before zoom to minimap/stellite view:
![image](https://user-images.githubusercontent.com/5298279/177750451-a0d9afea-6526-4403-a424-31a18f1b5272.png)
After zoom to minimap/satellite view:
![image](https://user-images.githubusercontent.com/5298279/177750573-d5024e83-2f33-4291-a9f8-9a0816587b7d.png)

**Comment by IrcDirk** [comment]
Needed to fix this by my self ;) Now it should be ok => https://github.com/IrcDirk/Carbonite-Classic/commit/c1734b12b2667bd2718a8fe90bc248d32ef12562

**Comment by artscout** [comment]
Oh that was my mistake, sorry, I missed that. Gald to see that fixed.

**Comment by IrcDirk** [comment]
@artscout no problem, it happens :D
