### ISSUE TITLE
Quest Module Not Showing Tooltips

### ISSUE THREAD

**Issue by puffidredz** [IrcDirk/Carbonite-Classic#206]
Quest info in tooltips has been working fine for months but suddenly today they're no longer displaying. I've disabled all addons and deleted all the Carbonite bak and lua files, then reinstalled all the carbonite modules for TBC and still they're not showing

**Comment by artscout** [comment]
I've checked everywhere and it works just fine. Check that Carbonite.Quests is enabled and set to show tooltips info in settings for Quests module. Also you can try to clear Carbonite.Quests.lua files in WTF SavedVariables subfolders.
