### ISSUE TITLE
Map Loading Error (I think)

### ISSUE THREAD

**Issue by tyjdu92** [IrcDirk/Carbonite-Classic#217]
I and some friends also using this addon have noticed that occasionally when loading into the game the map doesn't fully load and is dark and non-interactable. It usually happens when we have logged out in a city or inside a building, and the map is trying to load the docked mini-map as well as the main carbonite map. 

I'm not sure if it is related but we also set up our map fade out to 1, so that the border is static at all times.

The only way we've found to fix the error is to reset profile, and slowly adjust settings back to where we like them. Certain settings like map details will usually replicate the error. And changing settings or loading another profile while indoors / in a city, will also usually replicate the error.

We are using Carbonite 113.0. There's multiple downloads on curse, and wow-interface, and the carbonite website so I'm not sure if we are using the most up to date version, but searching carbonite classic on google takes us to a curse page that was updated the most recently of any of the downloads I've found thus far.

**Comment by artscout** [comment]
Can you record video of this to show what exactly happens and place it somewhere?

**Comment by tyjdu92** [comment]
https://www.youtube.com/watch?v=0JGQBixGOHw

Sorry, I didn't see this comment until today. Here's a screencap of the issue. At first I thought it had to do with the fade out option, but further testing proved that it will happen no matter what I do. 

This video is capturing the latest files, updated 9 hours ago on curseforge at the time of writing, playing in WLK pre patch. 

Usually the map doesn't bug out when logging in/out in an outdoors environment, but it did in the video until I opened the full map.

**Comment by tyjdu92** [comment]
> Can you record video of this to show what exactly happens and place it somewhere?

https://www.youtube.com/watch?v=0JGQBixGOHw

Sorry, I didn't see this comment until today. Here's a screencap of the issue. At first I thought it had to do with the fade out option, but further testing proved that it will happen no matter what I do.

This video is capturing the latest files, updated 9 hours ago on curseforge at the time of writing, playing in WLK pre patch.

Usually the map doesn't bug out when logging in/out in an outdoors environment, but it did in the video until I opened the full map.

**Comment by IrcDirk** [comment]
@tyjdu92 Does this still happen on newest Carbonite Classic version?

**Comment by tyjdu92** [comment]
> @tyjdu92 Does this still happen on newest Carbonite Classic version?

So far so good. Tested logging out/in in cities, indoor areas that are not cities, and changing settings that used to replicate the error.
