### ISSUE TITLE
The tooltip on quest target has no quest tracking info

### ISSUE THREAD

**Issue by kenhwong** [IrcDirk/Carbonite-Classic#22]
The tooltip on quest target has no quest tracking info. 
not sure whether it's a wow feature and disabled in classic edition, or it's a carbonite feature?

**Comment by IrcDirk** [comment]
API doesnt have the information. I think it must be included when scrapping from WoWHead this is will be feature to add in future.

**Comment by Rhendak** [comment]
I'm experiencing the same issue. 

![image](https://user-images.githubusercontent.com/1855295/65593819-9d128780-df91-11e9-99d1-2c90ca102e2d.png)


I noticed in the screenshots of https://github.com/IrcDirk/Carbonite-Classic/issues/37#issue-496704432 that it was working for this specific user? Also questie seems to be able to do this as well, not sure where that addon is getting the information from.

**Comment by IrcDirk** [comment]
@Rhendak thats not an issue. Thats not simply implemented.

On this screen user has Questie and thats why it shows tooltips. Questie has it own database in addon files for this.

**Comment by Rhendak** [comment]
Will this ever get fixed? I don't feel like using 2 questing addons (Questie) because one questing addon is incomplete. It's been a year since this was reported.

**Comment by nefartxxx** [comment]
same issue in TBC

**Comment by IrcDirk** [comment]
Blizzard API doesnt provide that info about quest objectives in TBC. It was avaiable from WOTLK. Im not thinking about implementing this in this moment. Maybe in some future, but I can't promise. 

U can use Questie for this.

**Comment by IrcDirk** [comment]
Ok, it though that i need to scrap more data but it seems i already got it. Pushed commit with data 2d596a2 and made some modifications and it should work now ;)

**Comment by chuman72486** [comment]
Is it possible for Carbonite to "discover" these things?  Like, when you kill a monster and a quest suddenly shows progress, make a note that the monster just killed will progress the quest?  Or if you loot an item that causes quest progress, make note of the monster it was looted from?  The idea would be that Carbonite might be able to make educated guesses of which monsters to show progress on based on data it has collected so far.  Perhaps later users can submit their quest discovery data to expand the "official" database?  Maybe Carbonite can even share what it has discovered with group and guild members with the addon, as a sort of crowdsource method of building the quest database?

**Comment by IrcDirk** [comment]
Sorry, but no. Tootlips will be based on quests scraped data. We already tried recording and sharing, it didn't worked.
