### ISSUE TITLE
Major lag when Carbonite Quest- Classic @project-version@ is turned on

### ISSUE THREAD

**Issue by Kenoxxxx** [IrcDirk/Carbonite-Classic#221]
I have no other addons enabled just carbonite and the modules it comes with, all modules are fine until the quest one is turned on then major lag starts happening going from 122fps down to 30 fps. was using the addon as normal with no issues for a month or so before hand then the WOTLK pre-patch came out and now I'm having this issue with the addon. I have tried uninstalling and reinstalling, no quest bubbles are even popping up on the map anymore.

**Comment by insectdude1258** [comment]
i suggest using bug grabber and bug sack so you can upload the error its giving. when i enable carbonite quest module, it it throwing about 10 errors a second. the plugin hasnt been updated for wotlk yet. but those errors are why youre having the lag. ive found i can use the map part of carbonite, but not the quests part

**Comment by BetaVirus** [comment]
Till they update the mod, disabled the Carbonite quest modlet

**Comment by KoolKeith** [comment]
Also, together with Questie 7.0.1 it does not work. I downgraded Questie to 7.0.0 and it Carbonite works again. Hope this helps too.

**Comment by IrcDirk** [comment]
Are u using version from this repository? Curse is not updated yet.

**Comment by IrcDirk** [comment]
Curse and WoWInterface now updated.

**Comment by IrcDirk** [comment]
Let me know if this problem still occurs after updating the addon.

**Comment by Kenoxxxx** [comment]
Yup working as normal now with the update! Thank you! :)
