### ISSUE TITLE
Carbonite and Questie

### ISSUE THREAD

**Issue by KoolKeith** [IrcDirk/Carbonite-Classic#223]
Hello, making a new Thread. Tested configurations:
------------------------------------------------
Carbonite 3.4.0-1 with Quest-Module 
+ Questie 7.0.0 

-> Works !
------------------------------------------------
Carbonite 3.4.0-1 with Quest-Module 
+ Questie **7.0.1**

 -> Works too !
------------------------------------------------

Well, Carbonite and Questie fight for the small "Quest Tracker List" window. I can't seem to have both active and working, but I guess you only need one anyway (will prefer Carbonite). 

Oddly, only during moving the character, Questie icons (like the little swords etc.) are indeed planted onto the Carbonite minimap. That's cool ! Also, opening the "Non-Carbonite Map", all seems to be there from Questie, which is good. 

Dirk, is it possible to increase the "hitbox radius" of the needle, when I reach my Pin ?

**Comment by KoolKeith** [comment]
My list of Addons:

  Swatter, v2.5.6773 (SwimmingSeadragon)
  AccountantClassic, vv2.12.20
  AdiBags, vv1.9.26-bcc
  _(Auctioneer Suite v2.5.x abbreviated)_
  AuctionDB, vv1.07.00
  Bartender4, v4.11.4
  BeanCounter, v2.5.6767 (SwimmingSeadragon)
  BrokerEverything, v4.3.9-release
  BulkMail2Inbox, v9.0.5
  ButtonForge, v1.0.5-classic-TBC
  Carbonite, v@project-version@
  CarboniteNotes, v@project-version@
  CarboniteQuests, v@project-version@
  CarboniteWarehouse, v@project-version@
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  EasyMail, v4.4.9
  Elephant, v2.5.1a
  Enchantrix, v2.5.6768 (SwimmingSeadragon)
  ~~InFlightLoad, v2.05.001~~
  Informant, v2.5.6770 (SwimmingSeadragon)
  LeatrixPlus, v3.0.02
  LittleBuster, v1.14.0
  Masque, v9.2.7
  MinimapButtonButton, v1.8
  Plater, vPlater-v353.1-9-gbe1144c-Wrath
  Prat30, v3.9.1
  Prat30Libraries, v
  Questie, v7.0.1
  SkilletClassic, v1.47
  SlashHelp, v5.1
  SlideBar, v2.5.6771 (SwimmingSeadragon)
  StatBlockDurability, v
  Stubby, v2.5.6772 (SwimmingSeadragon)
  TipTac, v22.08.11
  TipTacItemRef, v22.08.11
  _TitanClassic, v1.5.3.30400  (Suite, abbreviated)_
  _ZPerl, v6.3.3  (Suite abbreviated)_
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v3.4.0.30400

**Comment by artscout** [comment]
Not sure about hitbox radius, that's for Dirk to see probably. About questie icons being visible by moving character - it's the same issue we had with HandyNotes and minimap. The thing is that both questie and carbonite trying to draw their things on minimap and carbonite would redraw minimap while you're not moving clearing all other icons. That I probably can fix for Questie too. I had some thought about "Questie integration" but that's a thought for future.

**Comment by IrcDirk** [comment]
Nope there is no setting for hitbox radius, sorry.

As to Questie icons, yeah its a bug, but it happens also with other addons.

**Comment by IrcDirk** [comment]
Fixed Questie icons, now they are not showing in Docked Icons of Carbonite.

**Comment by syswis** [comment]
Hello, not sure if is the same issue, but when Questie is enabled I can no longer see PoI icons on Carbonite Maps.

**Comment by IrcDirk** [comment]
> Hello, not sure if is the same issue or related, but when Questie is enabled I can no longer see PoI icons on Carbonite Maps.

Not releated, but i checked and Carb POI works with Questie for me without any problems.
