### ISSUE TITLE
Carbonite wotlk classic problems with fps and quest log

### ISSUE THREAD

**Issue by chaliniak** [IrcDirk/Carbonite-Classic#224]
Basically when i got mine carbonite quest log my fps get shredded to pieces, the game is barely playable, and quest log does not want to merge with each other the only one i got working is not from addon, while the ui log is carbonite and not working
![image](https://user-images.githubusercontent.com/112666006/188022635-a6de39cc-61a2-4a48-a4d2-056b049686f4.png)

**Comment by artscout** [comment]
I'm sorry but why send us screenshot of working blizzard quest log? Send us Carbonite quest log screenshot with problem clearly visible, otherwise it's hard to even begin investigation of what could be wrong.

**Comment by GhineaNicolaeFlorin** [comment]
Having similar issues with the FPS when Quest module is enabled. Opening the map will tank my fps to ~7. Unfortunately I do not know what logs/screenshot I could give to better understand this issue

**Comment by artscout** [comment]
Working on it, investigating issue. Already found some issues with quest log merging, that I'll fix soon enough. Investigating FPS dtop (I still can't reproduce it, can you send me screenshot of Carbonite quest log with "Show Quest ID" option enabled for Quest module?)

**Comment by MaxShineOn** [comment]
The FPS drop happens when engaging in combat mostly.

**Comment by IrcDirk** [comment]
I dont see any problems with FPS, took 10 quest, fighting, completing quest and still  FPS is good and steady... 

So first of all what u need to do is to test the game with **ONLY Carbonite + Modules enabled**, all other addons disabled. It might be other addon that does the FPS drop when used with Carbonite.

**Comment by GhineaNicolaeFlorin** [comment]
Video with fps drops that I am getting, check the mouse position on the map: https://streamable.com/a44f8c
FPS drops even when hovering over NPCs, related or not to active quests that I have.
It might also be a hardware issue, no I am not running this on a potato but even so these fps drops are massive.
As soon as I disable only the quests module the game runs fine.

**Comment by IrcDirk** [comment]
@GhineaNicolaeFlorin As i wrote before... Check with **ONLY Carbonite + Modules enabled, all other addons DISABLED**.

It might be other addon that does the FPS drop when used with Carbonite Quest module.

**Comment by MaxShineOn** [comment]
I just tested, seems to be getting the lag drop when Questie is enabled alonside Carbonite. The lag mostly seems to occur while in combat/hoving over the mob you're attacking.

**Comment by MaxShineOn** [comment]
Re-testing, I can also reproduce it while the Carbonite Quest module is loaded and it has finished loading the 8275 quests according to the system message. After that, mobs and herb nodes will trigger the lag, even without any other addons running (just Maps, Notes, and Quest).

**Comment by IrcDirk** [comment]
Im testing on PTR and on there i got zero FPS problems... Go to wow subscription to check it on Retail Classic Pre-Wotlk.

**Comment by nochio23** [comment]
Same issues, kills my FPS when having the quest component loaded. Mousing over literally anything in the game makes the game lag. Not a hardware issue.

**Comment by IrcDirk** [comment]
Is there a difference after recent WoW update (3.4.0.45435)?

**Comment by GhineaNicolaeFlorin** [comment]
For me the issue is still there after the update.

**Comment by IrcDirk** [comment]
Can someone with those problem send me compressed WTF folder?

**Comment by artscout** [comment]
It's probably some settings. I couldn't reproduce issue at all on live Prepatch, tried different settings (graphics settings, minimap settings like docker minimap and such). Need exact settings to see if it could be reproduced.

**Comment by BetaVirus** [comment]
I just loaded the game with no Mods and just carbonite and it lagged so hard it caused my Computer to become unresponsive for several minutes. Again only when the quest module is enabled.

**Comment by MaxShineOn** [comment]
Tossed you a wow sub and some Starbucks, good luck!

**Comment by IrcDirk** [comment]
> I just loaded the game with no Mods and just carbonite and it lagged so hard it caused my Computer to become unresponsive for several minutes. Again only when the quest module is enabled.
> 
> How is it that Git does not support 7zip?! [WTF.zip](https://github.com/IrcDirk/Carbonite-Classic/files/9481469/WTF.zip)

Tested with your settings an all seems fine :( No fps drop.

**Comment by IrcDirk** [comment]
@BetaVirus Can u do me a favour and rename WTF folder to WTF2, then start WOW Classic WOTLK and test FPS on all new setting. Load only Carbonite + Modules and let me know if there is still FPS issue on your side.

After that test u can just delete WTF folder and rename WTF2 to WTF and all your settings will be back :)

**Comment by BetaVirus** [comment]
I am on a different computer  now having the same issues. I will try the test you wanted later today.

**Comment by IrcDirk** [comment]
@BetaVirus On both computers u played on Classic TBC also?

**Comment by nochio23** [comment]
> @BetaVirus Can u do me a favour and rename WTF folder to WTF2, then start WOW Classic WOTLK and test FPS on all new setting. Load only Carbonite + Modules and let me know if there is still FPS issue on your side.
> 
> After that test u can just delete WTF folder and rename WTF2 to WTF and all your settings will be back :)

After renaming WTF to WTF2 the lag stopped for me

**Comment by artscout** [comment]
[NxQuest.zip](https://github.com/IrcDirk/Carbonite-Classic/files/9483125/NxQuest.zip)
Ok could you try to download this file, unpack it and placeinto Interface/Addons/Carbonite.Quests folder overwriting current file. Just a hunch to check over. See if this helps with mouseover

**Comment by chaliniak** [comment]
> I'm sorry but why send us screenshot of working blizzard quest log? Send us Carbonite quest log screenshot with problem clearly visible, otherwise it's hard to even begin investigation of what could be wrong.

Sorry, i just wasnt on my pc for two days and was unable to response.
The prolblem lies in screenshot carbonite doesnt want to open it's quest log, only wow qlog works,
to addition that beatiful qlog list on right side of screen is unresponsive and doesn't want to list my tracked quests,
I've seen on other forums repair tip to limit loaded quests in carbonite to +5/-5lvls from your own, but i can't find option to this.
Fps drops ONLY when quest module is active, i've tested it with and without other addons

**Comment by artscout** [comment]
@chaliniak you too could try file I posted one post above.

**Comment by chaliniak** [comment]
[WTFs from wow clasic in zip not rar.zip](https://github.com/IrcDirk/Carbonite-Classic/files/9483185/WTFs.from.wow.clasic.in.zip.not.rar.zip)
okay, so i've tried new Nx.Quests file, i've tried with and without other addons and i'm linking my WTFs folders numbered and named.
Only thing i can think of next is that old WoW could use limited amount of RAM and even stronger pc's couldn't hande the fps drops (mainly in dala in northrend) and response to that was some kind of file from 3rd "company" that was unblocking the limit on wow, it wasn't made by the Blizzard but they've said that it works and i've used that "file" or program or whatever that was and my dala problems with fps drops were gone, maybe the problem is in RAM consumption by quest module?

**Comment by artscout** [comment]
Ok try this. When in game open carbonite settings, select quests on the left side. you'll see four tabs, last tab is database settings. There you'll see level loading limiter, try to set it up for you character

**Comment by chaliniak** [comment]
![image](https://user-images.githubusercontent.com/112666006/188285020-f72b746f-3454-4657-9093-634029227cce.png)
there's no quest module here

**Comment by artscout** [comment]
Wait a moment. And you had Carbonite.Quests enabled when you took this screenshot with you having lags with mouseover?

**Comment by chaliniak** [comment]
> 

yes xD

**Comment by artscout** [comment]
![carbonite_options](https://user-images.githubusercontent.com/18420005/188285909-aae901f7-b9fb-4e0f-bed8-175d879f14ff.jpg)

You should have this when Quests module is enabled.

**Comment by chaliniak** [comment]
but i dont have it :V that's the problem probably with not working quest log properly too

**Comment by artscout** [comment]
Ok let me ask another question: open file Interface/Addons/Carbonite/Carbonite.toc, copy everything there and paste here please.

**Comment by chaliniak** [comment]
## Interface: 30400
## Title: Carbonite Maps - Classic @project-version@
## Version: @project-version@
## Author: No one
## Notes: Released Under GPL
## DefaultState: Enabled
## LoadOnDemand: 0
## SavedVariables: CarbData
## SavedVariablesPerCharacter: CarbMigr

## X-WoWI-ID: 12965

Libs\libs.xml
Locales\Locales.xml
Carbonite.lua
NxUI.lua
NxOptions.lua
NxCom.lua
NxHUD.lua
Data\data.xml
NxMapData.lua
NxMap.lua
NxMapGuide.lua
NxTravel.lua
Carbonite.xml

**Comment by artscout** [comment]
ok another thing to try. right after logging in game with character type this in chat:
/console ScriptErrors 1
after that /reload to see if there are any errors

**Comment by chaliniak** [comment]
Message: Interface\AddOns\Carbonite\NxUI.lua:4567: attempt to perform arithmetic on local 'pos' (a nil value)
Time: Sat Sep  3 22:16:52 2022
Count: 1
Stack: Interface\AddOns\Carbonite\NxUI.lua:4567: attempt to perform arithmetic on local 'pos' (a nil value)
[string "@Interface\AddOns\Carbonite\NxUI.lua"]:4567: in function `SetSlider'
[string "@Interface\AddOns\Carbonite.Quests\NxQuest.lua"]:8746: in function `?'
[string "@Interface\AddOns\Carbonite.Quests\NxQuest.lua"]:2764: in function `Init'
[string "@Interface\AddOns\Carbonite.Quests\NxQuest.lua"]:2127: in function `func'
[string "@Interface\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua"]:57: in function <...\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals: self = <table> {
 SliderMax = 25
 User = <table> {
 }
 Id = 0
 Text = "Max Visible In List"
 Func = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8651
 Step = 1
 Menu = <table> {
 }
 Table = <table> {
 }
 SliderMin = 1
 Slider = true
 VarName = "NXWVisMax"
 ShowState = 1
}
pos = nil
min = 1
max = 25
step = 1
varName = "NXWVisMax"
(*temporary) = <function> defined =[C]:-1
(*temporary) = 1
(*temporary) = 25
(*temporary) = "attempt to perform arithmetic on local 'pos' (a nil value)"



Message: Interface\AddOns\Carbonite.Quests\NxQuest.lua:5423: attempt to index field 'TTIgnore' (a nil value)
Time: Sat Sep  3 22:17:11 2022
Count: 2
Stack: Interface\AddOns\Carbonite.Quests\NxQuest.lua:5423: attempt to index field 'TTIgnore' (a nil value)
[string "@Interface\AddOns\Carbonite.Quests\NxQuest.lua"]:5423: in function `TooltipProcess2'
[string "@Interface\AddOns\Carbonite.Quests\NxQuest.lua"]:5371: in function `TooltipProcess'
[string "@Interface\AddOns\Carbonite\Carbonite.lua"]:974: in function `?'
[string "@Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Carbonite\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...\AddOns\Carbonite\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>




Message: Interface\AddOns\Carbonite.Quests\NxQuest.lua:5423: attempt to index field 'TTIgnore' (a nil value)
Time: Sat Sep  3 22:17:13 2022
Count: 15
Stack: Interface\AddOns\Carbonite.Quests\NxQuest.lua:5423: attempt to index field 'TTIgnore' (a nil value)
[string "@Interface\AddOns\Carbonite.Quests\NxQuest.lua"]:5423: in function `TooltipProcess2'
[string "@Interface\AddOns\Carbonite.Quests\NxQuest.lua"]:5371: in function `TooltipProcess'
[string "@Interface\AddOns\Carbonite\Carbonite.lua"]:1314: in function `NXOnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: self = <table> {
 IconTracking = <table> {
 }
 UnpackCategory = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10573
 DailyTypes = <table> {
 }
 IsTargeted = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10339
 Menu_OnTrack = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3260
 GetQuestReward = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3314
 DecodeComRcv = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11208
 MsgNotInDB = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5273
 Watch = <table> {
 }
 PartyStartSend = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11470
 SortQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4348
 NullQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11618
 CheckQuestSE = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3198
 GetFromPlyr = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5087
 Custom = <table> {
 }
 TooltipProcess2 = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5382
 IdToCurQ = <table> {
 }
 PerColors = <table> {
 }
 GetClosestObjectivePos = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10852
 RecordQuestsLog = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3500
 ExtractTitle = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4324
 CalcCNumMax = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4132
 UnpackObjective = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10610
 GetQuestObjectiveInfo = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4290
 ClearCaptured = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5107
 TooltipProcess = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5358
 SelectBlizz = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3368
 UnpackNext = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10564
 ShowUIPanel = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5860
 CapturePlyrData = <table> {
 }
 GetObjectiveType = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10623
 PartyUpdateTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11463
 MapChanged = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4024
 OnParty_members_changed = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11304
 TrackedAchievements = <table> {
 }
 UpdateQuestDetails = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8312
 DailyIds = <table> {
 }
 CalcDesc = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4272
 QLocColors = <table> {
 }
 CalcPreviousDone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4175
 AccessAllQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3448
 IconOnMouseDown = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8257
 OnProfileChanged = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:2157
 WatchAtLogin = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4918
 CreateLink = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4316
 L
 
 
 there are 3 errors right after logging

**Comment by chaliniak** [comment]
![image](https://user-images.githubusercontent.com/112666006/188286592-3c23afcd-b5e0-447f-be3c-22a7206ed9a4.png)
this one goes up in count like crazy while mouseovering and causing a lot of fps drops

**Comment by GhineaNicolaeFlorin** [comment]
Can confirm that I also do not have the quests tab in settings when quest module is enabled.

**Comment by artscout** [comment]
> Stack: Interface\AddOns\Carbonite.Quests\NxQuest.lua:5423: attempt to index field 'TTIgnore' (a nil value)

This can be ingnored, because it caused by earlier mistake. @GhineaNicolaeFlorin can you do the same thing (/console ScriptErrors 1 and /reload) to see that you have the same mistake: 
Message: Interface\AddOns\Carbonite\NxUI.lua:4567: attempt to perform arithmetic on local 'pos' (a nil value)

**Comment by artscout** [comment]
@IrcDirk they have new file so file positions are skewed. It's a Nx.Quest:GetQuestOpts() returning nil somehow.

**Comment by artscout** [comment]
[NxQuest.zip](https://github.com/IrcDirk/Carbonite-Classic/files/9483366/NxQuest.zip)
Can you try again with this file (same as before, unpack, replace in interface/addons/Carbonite.Quests)?

**Comment by chaliniak** [comment]
nothing has changed

**Comment by artscout** [comment]
[NxQuest.zip](https://github.com/IrcDirk/Carbonite-Classic/files/9483388/NxQuest.zip)
This one. Forgot to add one thing to check.

**Comment by chaliniak** [comment]
![image](https://user-images.githubusercontent.com/112666006/188287692-abe0a110-4964-425e-ac82-0f2bb1c5a3fc.png)
we have some action, it actually works rn xD

**Comment by artscout** [comment]
Oh ok. What about lags?

**Comment by chaliniak** [comment]
Right now works like a dream even without limiting loaded quests, i'm not getting fps drops on mouseovering anything, quest log has merged together, quest tracking list is working properly, i don't have any more Lua errors with /console ScriptErrors 1 opened

**Comment by artscout** [comment]
Ok thank you for being damn good test partner :) I will create pull request with fix and we will push it soon.

**Comment by chaliniak** [comment]
> Ok thank you for being damn good test partner :) I will create pull request with fix and we will push it soon.

Nice, thanks for ALL the help i had <3 luv ya, and luv Carbonite :p btw it'd be probably faster to reply and work on it with a discord chat XD
