### ISSUE TITLE
Eastern Plaguelands map is offset and doubled

### ISSUE THREAD

**Issue by Em-Cin** [IrcDirk/Carbonite-Classic#225]
Exactly what the title says. Additionally, at least one of them doesn't seem to be functioning correctly with the show unexplored areas option unchecked. After taking this image, I also checked the map on a fresh character with only Carbonite enabled, and the problem persisted.
![image](https://user-images.githubusercontent.com/112682169/188067284-b8695a0f-5167-40f0-a102-0b55d8bdf44e.png)

**Comment by IrcDirk** [comment]
It seems its TBC map not the WOTLK one ;) It changed in WOTLK... It needs to be fixed.

**Comment by Em-Cin** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/112682169/188080159-8073f790-9cf9-4401-88a9-526bf8b28ef7.png)
