### ISSUE TITLE
Stormwind quest locations are off

### ISSUE THREAD

**Issue by Em-Cin** [IrcDirk/Carbonite-Classic#226]
What the title says.
![image](https://user-images.githubusercontent.com/112682169/188081079-f7bf6b0a-8b3d-4dcf-9a0f-ae647ef9c282.png)

**Comment by artscout** [comment]
Stormwind map changed in WotLK. @IrcDirk I will fix locations in few hours and send you MR

**Comment by IrcDirk** [comment]
@artscout Sorry already fixed ;)

**Comment by Em-Cin** [comment]
Fixed.
