### ISSUE TITLE
blizz map merge not working

### ISSUE THREAD

**Issue by jeger774** [IrcDirk/Carbonite-Classic#228]
can't seem to be able to merge game minimap into carbonites map, tried disabling, reloading, then re-enabling the option, no dice

**Comment by IrcDirk** [comment]
@jeger774 Cant reproduce. 

Disable all other addons try with only Carbonite + Modules ... Your other addons might not be updated and causing errors.

**Comment by jeger774** [comment]
You're right, the culprit was ElvUI, disabling that, merging, reenabling worked. Thank you for making this for classic:)

**Comment by IrcDirk** [comment]
If u are using ElvUI disable Minimap integration in ElvUI options.
