### ISSUE TITLE
Carbonite Quest classic killing fps

### ISSUE THREAD

**Issue by nochio23** [IrcDirk/Carbonite-Classic#229]
Carbonite kills my FPS on classic, ONLY carbonite/quest running. When I mouse over anything at all, players, abilities, enemies, the quest map, anything at all that you can click or interact with it makes my fps  poof

**Comment by nochio23** [comment]
running just the map alone does not lag btw, only when running quests

**Comment by IrcDirk** [comment]
Duplicate. Closing.
