### ISSUE TITLE
Stormwind, Orgrimmar, and Undercity maps broken

### ISSUE THREAD

**Issue by Em-Cin** [IrcDirk/Carbonite-Classic#230]
Exactly what's stated in title. All three maps will show whatever zone you last had moused over instead of the city map. This only started happening after the most recent game update.
![image](https://user-images.githubusercontent.com/112682169/188224117-cc1414d5-1252-4f21-b7ea-983788b02925.png)
![image](https://user-images.githubusercontent.com/112682169/188224410-66f0332b-d4bc-44bc-a413-94d8748af29e.png)

**Comment by IrcDirk** [comment]
Update Carbonite from this repository and it should be fine ;)

**Comment by Em-Cin** [comment]
It does work fine, after updating it fully from here. Thanks.
