### ISSUE TITLE
Error loading instance map

### ISSUE THREAD

**Issue by geezerbahl** [IrcDirk/Carbonite-Classic#235]
I get the following error when I right click and try to load instance map:

Message: ...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:428: attempt to index local 'layers' (a nil value)
Time: Sat Sep  3 16:50:02 2022
Count: 2
Stack: ...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:428: attempt to index local 'layers' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua"]:428: in function `CreateZoomLevels'
[string "@Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua"]:415: in function `OnCanvasSizeChanged'
[string "@Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua"]:407: in function `SetMapID'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:35: in function `SetMapID'
[string "@Interface\AddOns\Carbonite\NxMap.lua"]:256: in function `SetMapByID'
[string "@Interface\AddOns\Carbonite\NxMap.lua"]:9419: in function `SetCurrentMap'
[string "@Interface\AddOns\Carbonite\NxMap.lua"]:5183: in function `SetInstanceMap'
[string "@Interface\AddOns\Carbonite\NxMap.lua"]:2962: in function `Func'
[string "@Interface\AddOns\Carbonite\NxUI.lua"]:4968: in function <Interface\AddOns\Carbonite\NxUI.lua:4938>

Locals:

**Comment by IrcDirk** [comment]
U are not providing enough information. What was the instance?

**Comment by geezerbahl** [comment]
I was in The Stockade.  Eventually when I went in far enough into the instance the map just went blank.  

This error came up when I right-clicked on instance and tried to load it manually (as it wasn't popping up when I was in the instance).

**Comment by IrcDirk** [comment]
Can u show me what do u mean by "tried to load it manually"?

**Comment by IrcDirk** [comment]
Hmmm... sorry but im not sure what u are talking about... Give me a screenshot or something :)

**Comment by nimanox** [comment]
i never get a dungeon map when i go into one do you need a mod to get the instance map in the carbo map?

**Comment by IrcDirk** [comment]
**Instance MAPS are only available for Northend Dungeons. (ill test them when WOTLK releases)**.

So sorry no instance maps in WOTLK Classic, they are just not available...

**Comment by IrcDirk** [comment]
=> https://github.com/IrcDirk/Carbonite-Classic/issues/7#issuecomment-1404686840
