### ISSUE TITLE
The Darkmoon Faire quest shows wrong destination

### ISSUE THREAD

**Issue by geezerbahl** [IrcDirk/Carbonite-Classic#236]
I accepted this quest in Ironforge, but when I click on the quest it is telling me to travel to ThunderBluff.  It should be showing outside of Stormwind.

**Comment by IrcDirk** [comment]
U are not providing enough information. Please provide quest name and if possible link to wowhead page of this quest.

**Comment by geezerbahl** [comment]
Sorry, here is the quest: https://www.wowhead.com/wotlk/quest=7905

**Comment by IrcDirk** [comment]
With newest Quest DB it shows location in Terrokar Forest. Since its the first location found in WoWHead DB. Carbonite doesnt support multiple locations of end NPC.
