### ISSUE TITLE
Dragging map is not smooth

### ISSUE THREAD

**Issue by Pazureka** [IrcDirk/Carbonite-Classic#239]
on for ex. OG TBC client carbonite map was very smooth while dragged with LMB, now its pretty choppy

**Comment by Pazureka** [comment]
https://user-images.githubusercontent.com/12884079/188447848-76d2366a-6c16-4bb2-91c5-96d6c262ab11.mp4

i recorded a comparsion to wotlk client, it's nitpicky, i know, it aint a issue, more like QOL idea, i would tag label as idea/improvement but there are no defined labels in this repo

**Comment by IrcDirk** [comment]
TBC was based on BFA client, WOTLK is Shadowlands... check video options. Thats not something i can fix.
