### ISSUE TITLE
Quest log cannot be resized or closed down

### ISSUE THREAD

**Issue by Pazureka** [IrcDirk/Carbonite-Classic#240]
Text goes out of black background, the window cannot be resized and minimized
![image](https://user-images.githubusercontent.com/12884079/188447191-de6d0522-8b5a-4b56-9c1c-baea1600b23d.png)
![image](https://user-images.githubusercontent.com/12884079/188447218-de07036f-f7dd-448a-a980-857cde40ecf3.png)
second screen is after minimizing

**Comment by IrcDirk** [comment]
For resizing check if u have option "Use A Fixed Size for Quest Watch" enabled, minimizing works fine on my side.

**Comment by Pazureka** [comment]
indeed, i had it checked, but problem did not appear before, and now minimizing works also with it unchecked, i guess if it's broken maybe it would be better to set this parameter to disabled by default. Thanks for help

**Comment by IrcDirk** [comment]
Ill take that in mind.
