### ISSUE TITLE
Icons on map are not sized in regard to actual zoom

### ISSUE THREAD

**Issue by Pazureka** [IrcDirk/Carbonite-Classic#241]
https://user-images.githubusercontent.com/12884079/188449961-e4b1d5a1-1048-4133-9b09-08cd662dd908.mp4

Here is a comparsion between actual client and old 3.3.5a wotlk client. If i change size of icons on actual client to be bigger, then after a zoom they will be too big. They do not scale with map zoom.

**Comment by IrcDirk** [comment]
Dont compare to 3.3.5a, Classic WOTLK is based on Shadowlands client. I will be not changing this sorry...

**Comment by IrcDirk** [comment]
U can play with this setting if u want smaller icons:

![obraz](https://user-images.githubusercontent.com/1030023/188451054-641f35d2-74e9-4c55-bf79-4f77388fc387.png)

**Comment by Pazureka** [comment]
that's the fix, now it works like it always worked before. thanks

**Comment by IrcDirk** [comment]
Not a fix, just different settings ;)
