### ISSUE TITLE
Errors w/Loot Roll Window not showing up

### ISSUE THREAD

**Issue by rhodan412** [IrcDirk/Carbonite-Classic#242]
I am receiving the following errors and when an item drop should trigger a loot window, the loot window doesn't show up as long as Carbonite is loaded.  These errors seem to exist with both v3.4.0-00004-wrath and v3.4.0-00005-wrath

1x Frame NxListFrms4: Unknown function QuestObjectiveItem_OnHide in element OnHide
1x Frame NxListFrms4: Unknown function QuestObjectiveItem_OnShow in element OnShow
1x Frame NxListFrms4: Unknown function QuestObjectiveItem_OnEvent in element OnEvent
1x Frame NxListFrms4: Unknown function QuestObjectiveItem_OnLoad in element OnLoad
1x Frame NxListFrms3: Unknown function QuestObjectiveItem_OnEvent in element OnEvent
1x Frame NxListFrms3: Unknown function QuestObjectiveItem_OnLoad in element OnLoad
1x Frame NxListFrms2: Unknown function QuestObjectiveItem_OnHide in element OnHide
1x Frame NxListFrms2: Unknown function QuestObjectiveItem_OnShow in element OnShow
1x Frame NxListFrms2: Unknown function QuestObjectiveItem_OnEvent in element OnEvent
1x Frame NxListFrms2: Unknown function QuestObjectiveItem_OnLoad in element OnLoad
1x Frame NxListFrms1: Unknown function QuestObjectiveItem_OnHide in element OnHide
1x Frame NxListFrms1: Unknown function QuestObjectiveItem_OnShow in element OnShow
1x Frame NxListFrms1: Unknown function QuestObjectiveItem_OnEvent in element OnEvent
1x Frame NxListFrms1: Unknown function QuestObjectiveItem_OnLoad in element OnLoad

**Comment by IrcDirk** [comment]
Sorry i cant reproduce... Post full log not one line. Also **disable** all other addons and try with only Carbonite + modules, it might not be Carbonite.

**Comment by rhodan412** [comment]
Each error actually only showed one line.  I have also verified that it is Carbonite.  Even removing Bugsack and Buggrabber the errors comes up as LUA Warning

**Comment by rhodan412** [comment]
The map module of Carbonite doesn't generate the error, only when I add the Carbonite Quest module with the main (Map)

**Comment by rhodan412** [comment]
The error also only shows up if you have an usable quest item in the Carbonite Quest module (that might have been why you couldn't duplicate my issue).  Maybe check Isle of Quel'Danas dailies?

**Comment by IrcDirk** [comment]
Thats weird... ill try to reproduce...

**Comment by IrcDirk** [comment]
Got it and it should be fixed ;)

**Comment by rhodan412** [comment]
Looks great.  Thank you.
