### ISSUE TITLE
Not working in DK Starting Area

### ISSUE THREAD

**Issue by Crudos286** [IrcDirk/Carbonite-Classic#243]
I use Carbonite for a long Time now but i just noticed that nothing is working in the DK starting Area.
Its not new Content its just an old Expansion but there is no map no targets.
Now i have to install another Addon. I dont think its what u wanted or im wrong?
testet the newest update and some older ones.

**Comment by IrcDirk** [comment]
Install what ever u want... I dont like your tone...
