### ISSUE TITLE
Quest filter option?

### ISSUE THREAD

**Issue by joltox** [IrcDirk/Carbonite-Classic#245]
Is it possible to filter available quests by faction? If not perhaps add an option to do so.

I appreciate the time and work you put into this mod. TY!

**Comment by IrcDirk** [comment]
Hmmm... they should be... but i see they are not... so ill do it in spare time ;)

**Comment by IrcDirk** [comment]
Yeah... Quest DB scrapper didn't read it the right faction. Now everything should be fine.
