### ISSUE TITLE
Low FPS/Refresh rate in map

### ISSUE THREAD

**Issue by phonomania2** [IrcDirk/Carbonite-Classic#247]
I'm comparing the behaviour to a reference 3.3.5a client, running carbonite on a private server, the map zoom and drag work buttery smooth, in contrast to wrath classic where it seems to have a capped refresh rate

I've recorded 2 comparison videos to show this

Original 3.3.5a client running carbonmite on a private server: https://www.youtube.com/watch?v=sg5lNwuOr4Y
Wrath classic running carbonite downloaded from curse: https://www.youtube.com/watch?v=UFwGVGSqnBY

**Comment by jamsch** [comment]
Had a look in to this a few days ago myself. Primary cause seems to be the following lines:

https://github.com/IrcDirk/Carbonite-Classic/blob/master/Carbonite/NxMap.lua#L3842-L3846
which limits the OnUpdate function (called every frame) to once every 5ms (at least). I've calculated the duration of the whole OnUpdate function and it seems to be negligible to do this early return.

Also animation durations are quite long which adds to the perceived lagginess, specifically mouse wheel:
https://github.com/IrcDirk/Carbonite-Classic/blob/master/Carbonite/NxMap.lua#L3808

**Comment by phonomania2** [comment]
> Had a look in to this a few days ago myself. Primary cause seems to be the following lines:
> 
> https://github.com/IrcDirk/Carbonite-Classic/blob/master/Carbonite/NxMap.lua#L3842-L3846 which limits the OnUpdate function (called every frame) to once every 5ms (at least). I've calculated the duration of the whole OnUpdate function and it seems to be negligible to do this early return.
> 
> Also animation durations are quite long which adds to the perceived lagginess, specifically mouse wheel: https://github.com/IrcDirk/Carbonite-Classic/blob/master/Carbonite/NxMap.lua#L3808

Wow you're amazing, thank you. I changed the value to .00606 (cause my screen is 165hz) and it completely fixed the issue. Thank you

**Comment by IrcDirk** [comment]
@phonomania2 I mentioned this earlier... WOTLK client has nothing similar to 3.3.5a ... its based on Shadowlands client. So comparing those makes no sense.

@jamsch Thanks for those. I think ill make this "thick" value configurable, so every one can find the right value. Those thick value was added because without it some of the people complained about FPS ;) and i mean FPS of whole game not only the Carb Map.

**Comment by jamsch** [comment]
@IrcDirk I'd change the default value to a lower number, 0.05 makes interactions with the map run at ~19fps. I'd change it to at most 0.016, 60fps.

**Comment by IrcDirk** [comment]
Yeah... different computers need different values, that's why i made that configurable. Seems its hardware dependent... 

I have steady 90FPS no matter what i set ;)
