### ISSUE TITLE
Plaguebloom not showing on map

### ISSUE THREAD

**Issue by Em-Cin** [IrcDirk/Carbonite-Classic#248]
Plaguebloom isn't showing on my map, at least in Felwood. I have not checked WPL or EPL. I am unsure whether this problem originates from the addon itself or if something weird happened with the stuff in my WTF folder. I did notice that going into Guide>Gather>Herb, it was listed as Sorrowmoss instead of Plaguebloom.

I would post screenshots, but for some reason Github is currently refusing to allow me to upload any images whatsoever.

**Comment by IrcDirk** [comment]
Yeah Sorrowmoss = Plaguebloom ... it changed name, but i dont know when ;) Ill just change the name ;)

**Comment by Em-Cin** [comment]
It doesn't retroactively show on the map where I had gathered, but newly gathered spawns are now showing properly on the map.
Additionally, I tried pulling up Sorrowmoss on retail WoWhead, and the comments section there says that it was changed in Cataclysm, and that it moved from Felwood, WPL, and EPL to Swamp of Sorrows.
https://www.wowhead.com/item=13466/sorrowmoss#comments

**Comment by IrcDirk** [comment]
U can just load Ghatermate data to see where nodes are.

czw., 15 wrz 2022, 21:48 użytkownik Em-Cin ***@***.***>
napisał:
