### ISSUE TITLE
World Map off centered on 4k display

### ISSUE THREAD

**Issue by cde311** [IrcDirk/Carbonite-Classic#251]
I believe that carbonite main world map may not be displaying properly on my 4k screen.  It is fine on my laptop (1920x1080) screen but on my 3840x2160 display, the map is off-centered and cut off.  That is the only thing I can think of that may be causing this.  Any other ideas? I have done a full reset on my UI by deleting cache, wtf and interface folders and only adding back the carbonite addon. See pic
![maperror](https://user-images.githubusercontent.com/84498178/190873623-46642eea-a548-4812-ad08-99d8ec9af638.png)

**Comment by IrcDirk** [comment]
Thats main Blizzard map that has nothing to do with Carbonite.

**Comment by cde311** [comment]
> Thats main Blizzard map that has nothing to do with Carbonite.

The stock map works fine when I have carbonite off though, is my issue.

**Comment by SanUnkara** [comment]
I use a triple monitor setup with 5760x1080 Screen
and i got the same problem since version 2.0.7, everything was OK with 2.0.6
if you open the Bliz Map, its not centered anymore, and the map opens in left corner on your screen

**Comment by IrcDirk** [comment]
Just checked on my 4K everything is fine... Did u checked only with Carbonite + Modules enabled? Seems it might be incompatibility with other addon...

**Comment by SanUnkara** [comment]
i checked only with carbonite + quest modul, no other addons and cleared cache, 
bliz map opens in the left corner and is cut off cause its not centerd in any monitor

**Comment by IrcDirk** [comment]
Sorry cant reproduce:

![obraz](https://user-images.githubusercontent.com/1030023/191035695-b3b8dd16-41f5-450c-b519-1400a373c6bb.png)

**Comment by IrcDirk** [comment]
Ok, so my map is not centered too... Didnt saw that... I might be blind :D

Tired to fix that... Please check on your side.

**Comment by IrcDirk** [comment]
@SanUnkara Let mi know if it worked for u.

**Comment by SanUnkara** [comment]
Yes that solved it for me too, thanks =)
