### ISSUE TITLE
Coordinates tooltip sometime get stuck

### ISSUE THREAD

**Issue by syswis** [IrcDirk/Carbonite-Classic#253]
The tooltip in upper-right showing the zone name and coordinates under the cursor on the carbonite map, frequently get stucked and no longer show coordinates under cursor.
After a while the tooltip goes away and start working again.

I tried to reproduce it but is just happen randomly

**Comment by IrcDirk** [comment]
@syswis Please show me some screenshot because i don't know which coordinates u are talking about.

**Comment by IrcDirk** [comment]
No response... Closing.

**Comment by syswis** [comment]
@IrcDirk Sorry for the delay, here is the screenshot: [https://i.ibb.co/nff6zMv/Screenshot-62.png](url)
I'm taliing about that tooltip.

**Comment by IrcDirk** [comment]
They are not stuck ;) Those are mouse over coordinates and distance between your current location.

**Comment by syswis** [comment]
I'm pretty sure that when moving the mouse it show the coordinates under the cursor. I always used it to create Goto's.
And when trying to create a Goto with precision, sometimes I can't because get stucked and no longer show coordinates under cursors. Sometimes get stucked completely while overing another zone.

Here's a video showing the issue:

https://user-images.githubusercontent.com/102670530/192797245-4eb8ee5f-9a98-47f8-a998-d73cec6835c2.mp4

**Comment by IrcDirk** [comment]
Sorry cant reproduce. Disable all other addons leave only Carbonite + Modules enabled. It might be incompatibility with other addon.

**Comment by syswis** [comment]
I tried and it's still happening :(

https://user-images.githubusercontent.com/102670530/192802674-814d4ed7-35d8-43ef-a59a-bbdaf2a1099e.mp4

**Comment by syswis** [comment]
Just something I have found out that maybe is causing the issue, I tried to see when `SetLocationTip` is called and I see being called also while not overing on the map, and when get stucked it does not get called.
Seems to be an issue with overing checks.

**Comment by IrcDirk** [comment]
I don't have this problem... If i cant reproduce i cant fix it...

https://user-images.githubusercontent.com/1030023/192841312-a4fc142c-bb92-4252-8b66-fd1810f4754f.mp4

**Comment by syswis** [comment]
Yes of course I understand. I don't know what is causing the issue on my end.
I always had this issue since I started playing TBC Classic and if i remember correctly also way back in time on retail.
For now it's working with that change I made and it's ok :)

**Comment by IrcDirk** [comment]
Seems its a hardware issue ... Weird.
