### ISSUE TITLE
Blizzard Quest Log unable to open during combat

### ISSUE THREAD

**Issue by Shronky** [IrcDirk/Carbonite-Classic#257]
When the option "set Carbonite quest log to Alt+L keybind" is enabled, you cannot open the Blizzard (default UI) quest log while in combat.

The problem is within the Carbonite Quest module (as when it's turned off the problem does not persist). Fiddling with options does not fix anything. 

Using Alt+L to open the Carbonite Quest log still works however.

**Comment by IrcDirk** [comment]
Should be fixed now.

**Comment by Shronky** [comment]
Tested it and it works without any issue. Thanks for the fix!
