### ISSUE TITLE
Dragonblight missing quest objectives

### ISSUE THREAD

**Issue by cy6wycked** [IrcDirk/Carbonite-Classic#259]
This is a giant list of quests i've found missing in Dragonblight
Super love this addon - used it back in the day and can solely attribute it to hitting 80. Would love to see it nice and finished like back in the glory days, Quest list is as follows:

Syntax:
QUEST WITH PARTIAL INFORMATION IN DB #1
- objective 1 [EXISTS IN DB]
- objective 2 [DOESNT]
- etc
QUEST NAME OR TITLE THAT DOESNT EXIST IN DB AT ALL #2
- Objective 1
- Objective 2
- etc

[74] On Ruby Wings (Part 4 of 4)
- Wastes Scavenger Slain 0/30 [EXISTS IN DB]
- Scythe of Antiok: 0/1 [DOESNT]

[72] Blighted Last Rites
- Flask of Blight tested: 0/1

[72$] Planning for the Future
- Snowfall Glade Pup 0/12 

[72] The Focus on the Beach (Part 3 of 16)
- Ley line focus information retrieved: 0/1 

[73] In Service of Blood 
- Filled Blood Gem 0/1 

[73] In Service of Frost
- Filled Frost Gem 0/1

[73] In Service of the Unholy
- Filled Unholy Gem 

 [73] The Denouncement (Part 2 of 2)
 - Commander Jordan's Denouncement and Death: 0/1
 - Lead Cannoneer Zierhut's denouncement & death: 0/1
 - Blacksmith Goodman's denouncement & death: 0/1
 - Stable Master Mercer's denouncement & death: 0/1
 
 [73] Where the Wild Things Roam (Part 5 of 5)
 - Snowfall Elk inoculated: 0/5
 - Arctic Grizzly Inoculated: 0/5
 
 [74] No One to Save You
- Burning Depths Necrolyte Slain: 0/6 [EXISTS IN DB]
- Smoldering Skeleton Slain: 0/10 [DOESNT]
 
 [74] No Place to Run (Part 1 of 2)
- Destructive Ward Fully Charged 0/1

[74+] The Plume of Alystros
- The Plume of Alystros: 0/1

[74+] Wanton Warlord
- Grom'thar's Head: 0/1

This is just the start, (currently everything in my quest log that isn't in the DB)
I'll add to this list below or in another comment - not too used to github

but regardless I randomly thought about this addon and reinstalled it , found a bunch of information on quests that Questie had bugged, and found Carbonite ACTUALLY TELLING me that it needed quest information - unlike the other addons. 
Stoked to collaborate. Thanks for the addon o7
Let me know if there is anything else I can do to help.

**Comment by cy6wycked** [comment]
Also if I should switch up syntax with more/less information let me know.

**Comment by IrcDirk** [comment]
Sorry i dont have access to Dragonblight beta, so till PTR will have it i cant do much about it. So u need to wait till quest db update.

**Comment by IrcDirk** [comment]
Just pushed commit => https://github.com/IrcDirk/Carbonite-Classic/commit/988c691dff559ea0aa196bf18ea0bde71e8e8a52 its not perfect but now there should be more quest objectives in quest database.
