### ISSUE TITLE
Paths to Trainers.

### ISSUE THREAD

**Issue by Cithramir** [IrcDirk/Carbonite-Classic#26]
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite\NxMapGuide.lua line 1535:
   bad argument #3 to 'format' (string expected, got nil)
Debug:
   [C]: format()
   Carbonite\NxMapGuide.lua:1535: UpdateMapGeneralIcons()
   Carbonite\NxMapGuide.lua:1464: UpdateMapIcons()
   Carbonite\NxMapGuide.lua:1145: Update()
   Carbonite\NxMapGuide.lua:733: OnListEventDo()
   Carbonite\NxMapGuide.lua:639: UserFunc()
   Carbonite\NxUI.lua:6540: UserFunc()
   Carbonite\NxUI.lua:3706:
      Carbonite\NxUI.lua:3688

**Comment by Cithramir** [comment]
![image](https://user-images.githubusercontent.com/10510781/65232074-d732e380-dad0-11e9-8bfc-78d5cc08c4d9.png)

**Comment by Cithramir** [comment]
When clicking on trainers paths this pops up also

**Comment by IrcDirk** [comment]
Trainers not yet updated.

**Comment by Cithramir** [comment]
Thanks!

**Comment by Cithramir** [comment]
Appreciate the work you are doing

**Comment by IrcDirk** [comment]
Updated. Closing,
