### ISSUE TITLE
Latest update has broken quest tracking

### ISSUE THREAD

**Issue by XWingMitch0** [IrcDirk/Carbonite-Classic#261]
![image](https://user-images.githubusercontent.com/58368127/193697694-e372da6b-6d70-4bdf-bedf-55725f8982ee.png)
![image](https://user-images.githubusercontent.com/58368127/193697726-4a4d055a-68a0-4f91-9cfd-3c807de4e6f6.png)
WoW Classic WotLK Client 3.4.0 (45854) (release x64)

**Comment by XWingMitch0** [comment]
Confirmed still broken with all other addons disabled

**Comment by XWingMitch0** [comment]
Confirmed still non-functional with addons disabled.

please disregard ticket close/reopen; I am not familiar with GitHub comments.

**Comment by nefartxxx** [comment]
Still not working

**Comment by IrcDirk** [comment]
Just use previous release till ill fix this issue.

wt., 4 paź 2022, 01:28 użytkownik nefartxxx ***@***.***>
napisał:

**Comment by IrcDirk** [comment]
Fixed => https://github.com/IrcDirk/Carbonite-Classic/commit/2c1edc85963b35320a3b96c159d158f958036107

**Comment by XWingMitch0** [comment]
> Fixed => [2c1edc8](https://github.com/IrcDirk/Carbonite-Classic/commit/2c1edc85963b35320a3b96c159d158f958036107)

Confirmed working again - Thanks for the quick turnaround IrcDirk!

**Comment by IrcDirk** [comment]
It was my mistake sorry for that ;)
