### ISSUE TITLE
Multiple northrend quests with easy locations are "missing from quest database"

### ISSUE THREAD

**Issue by hvownij** [IrcDirk/Carbonite-Classic#263]
Theres a very large amount of quests missing from the database.  Im not sure if this is considered a bug, but I recall all of these working on the OG version from WOTLK.  Most of the locations  are very simple /way X, Y positions in the game world.  

The list is very massive.... Would probably take pages to post them all.  Is this a known issue that I should just forget about... or is there a easier way to report quests that are missing...

**Comment by IrcDirk** [comment]
@hvownij Give me some examples of those missing quests, wowhead links if u can :)

**Comment by hvownij** [comment]
Note:  Im trying to provide good feedback, but these quests were completed already by me so its pretty hard to see what ones were messed up without being on the quest currently...  Im going to attempt to pull my histroy on wow head and try to remember. 
Another Note:  Some of these were just not correctly marked, or were way off.  used /way's found in comments to complete.

https://www.wowhead.com/wotlk/quest=13285/forging-the-keystone

https://www.wowhead.com/wotlk/quest=13037/memories-of-stormhoof

https://www.wowhead.com/wotlk/quest=12985/forging-a-head

https://www.wowhead.com/wotlk/quest=13057/the-terrace-of-the-makers

https://www.wowhead.com/wotlk/quest=13273/going-after-the-core

https://www.wowhead.com/wotlk/quest=12858/pieces-to-the-puzzle

https://www.wowhead.com/wotlk/quest=12828/ample-inspiration

https://www.wowhead.com/wotlk/quest=12985/forging-a-head

https://www.wowhead.com/wotlk/quest=11989/truce

https://www.wowhead.com/wotlk/quest=12415/the-horse-hollerer

https://www.wowhead.com/wotlk/quest=13035/lokens-lackeys 

https://www.wowhead.com/wotlk/quest=11969/springing-the-trap

https://www.wowhead.com/wotlk/quest=12093/runes-of-compulsion

https://www.wowhead.com/wotlk/quest=12453/eyes-above

https://www.wowhead.com/wotlk/quest=11984/filling-the-cages



As I go forward, I will keep posting to this threat missing / incorrectly marked quests and provide wowhead links.  I think there should be a feature added to carbonite to automatically send missing quest information ingame somehow.

**Comment by hvownij** [comment]
but i should also mention, multiple users reported in game things were missing / not added to data base as they were leveling up too.

**Comment by IrcDirk** [comment]
Dont post more... I needed just a few examples ;)

**Comment by hvownij** [comment]
If I encounter more how do we get them fixed then?

**Comment by IrcDirk** [comment]
Sorry but we are not Questie and mostly im the one developer of this addon. Quest DB is based on previous versions of Carbonite (old 3.3.5a) and Wowhead quest database. Sorry i dont have time to fix quest one by one. But ill just updated quests objectives and there should be many more added.

**Comment by hvownij** [comment]
so you dont want issues reported to improve your addon?

**Comment by hvownij** [comment]
Im looking at the database files... it seems like simple search for quest ID tags, update the points.  If that is the case, this is a very simple process to automate.  Do you not want help with this?

**Comment by IrcDirk** [comment]
@hvownij That's not that simple u think. 

First of all Carbonite Quests DB consists of 2 types of objectives: one point objectives (simple to add) and blobs which consists of more points connected to each other by height and width (not so simple to add, u need to have algorithm for that).

Second thing is that i update Quests DB periodically by scrapping WowHead database, so any changes may be overwritten by that. So we need other solution for that... 

If u are willing to help and suggest easy solution for that and then implement it, then please make pull requests to this repository. Any help is appreciated... :)

**Comment by IrcDirk** [comment]
@hvownij and did you came up with something?

**Comment by hvownij** [comment]
Ive decided to support questie for quest features.  They offer more tools and are a bit more accepting to reporting issues.  I wish you luck with your addon though
