### ISSUE TITLE
PVP Objective Overlays

### ISSUE THREAD

**Issue by tyjdu92** [IrcDirk/Carbonite-Classic#265]
Not sure if it's an issue, or just not integrated. Is there any way to enable PvP Objective Overlays on the expanded map? My minimap shows control points (in Hellfire Peninsula at least), but my full size map does not. I haven't tried any BG's since the latest update, but I know it wasn't working at all for AB a few months ago.

**Comment by IrcDirk** [comment]
Duplicate => https://github.com/IrcDirk/Carbonite-Classic/issues/250
