### ISSUE TITLE
LFG window not working when running Carbonite WOTLK Classic

### ISSUE THREAD

**Issue by cheeseburgerdepot** [IrcDirk/Carbonite-Classic#267]
Just updated to **[CarboniteClassic-v3.4.0-00027]** but it started happening under the previous version too.  When i disable carbonite its ok again (and all the listings appear)

![grpfinder](https://user-images.githubusercontent.com/115516921/194983339-27ccaa8c-a04c-4639-a623-b88b73745ca7.PNG)

**Comment by IrcDirk** [comment]
=> https://github.com/IrcDirk/Carbonite-Classic/commit/7faf37d0d58eb59c65657503be9e813a744e638e

**Comment by cheeseburgerdepot** [comment]
Great! Thank you, much appreciated!
