### ISSUE TITLE
Quest Objective Missing from Database: Preparations for the Underworld

### ISSUE THREAD

**Issue by XWingMitch0** [IrcDirk/Carbonite-Classic#268]
Zone: Zul'Drak
Quest Giver: Har'Koa
Point of Interest: Altar of Har'Koa
Quest: Preparations for the Underworld (ID:12666)
Objective: Kill Claw of Har'Koa and Har'Koan Subduer for 8 Sacred Adornments.

https://www.wowhead.com/wotlk/quest=12666/preparations-for-the-underworld

**Comment by XWingMitch0** [comment]
Follow-up quest Seek the Wind Serpent Goddess (ID:12667) also missing

**Comment by XWingMitch0** [comment]
Seems it is the entire Quest series as all Follow-up quests in the series are missing.

**Comment by IrcDirk** [comment]
[12666] = {
		Quest = [[Preparations for the Underworld|2|77|74|12667|0|0]],
		Start = "28401|121|32|63.72|70.42",
		End = "28401|121|32|63.72|70.42",
		Objectives = {
			[1] = {
				"Sacred Adornment|121|35|63.5|62|20.04|3.34",
				"Sacred Adornment|121|35|62.5|62.5|30.06|3.34",
				"Sacred Adornment|121|35|62|63|35.07|3.34",
				"Sacred Adornment|121|35|61.5|63.5|45.09|3.34",
				"Sacred Adornment|121|35|61.5|64|50.1|3.34",
				"Sacred Adornment|121|35|61|64.5|60.12|3.34",
				"Sacred Adornment|121|35|60.5|65|70.14|3.34",
				"Sacred Adornment|121|35|60|65.5|75.15|3.34",
				"Sacred Adornment|121|35|59.5|66|80.16|10.02",
				"Sacred Adornment|121|35|59|67.5|85.17|3.34",
				"Sacred Adornment|121|35|58.5|68|85.17|6.68",
				"Sacred Adornment|121|35|58.5|69|80.16|13.36",
				"Sacred Adornment|121|35|59|71|75.15|3.34",
				"Sacred Adornment|121|35|59.5|71.5|70.14|3.34",
				"Sacred Adornment|121|35|61|72|60.12|3.34",
				"Sacred Adornment|121|35|61.5|72.5|60.12|3.34",
				"Sacred Adornment|121|35|62|73|60.12|20.04",
				"Sacred Adornment|121|35|62.5|76|60.12|3.34",
				"Sacred Adornment|121|35|62.5|76.5|65.13|3.34",
				"Sacred Adornment|121|35|63|77|60.12|3.34",
				"Sacred Adornment|121|35|63.5|77.5|55.11|3.34",
				"Sacred Adornment|121|35|64|78|20.04|3.34",
				"Sacred Adornment|121|35|64|78.5|15.03|3.34"
			},
		},
	},

**Comment by IrcDirk** [comment]
Checked more follow ups and they are too in database... So it seems u got old version of Carbonite.

**Comment by XWingMitch0** [comment]
Will verify - thought I updated it last night - sorry if it was my mistake!

**Comment by XWingMitch0** [comment]
![image](https://user-images.githubusercontent.com/58368127/196047052-d6accb85-f564-4733-96bc-6799453555a7.png)
![image](https://user-images.githubusercontent.com/58368127/196047062-86e4f417-2117-444b-8b77-f39e066109cc.png)
![image](https://user-images.githubusercontent.com/58368127/196047083-bc22a950-106a-4ccc-9078-fb841fd18883.png)

Verified latest version - entire objective tracking is missing/non-functional and it appears that quite a few Zul'Drak quests are in the same boat.

**Comment by IrcDirk** [comment]
I dont have that high levelled character ... Can someone confirm this?

**Comment by XWingMitch0** [comment]
Forgive me if I am barking up the wrong tree as I am far from a code expert but looking through the other quests in the 71-80 data file I am noticing a formatting issue with these and many quests...I am unsure if it is what is causing the issue:

12666
"Quest = [[Preparations for the Underworld**|2|**77|74|12667|0|0]], " is one of the non-functional quests.

(12661)
"Quest = [[Infiltrating Voltarus**|0|**75|74|12669|0|0]]," is a quest that was working. As are many others with that "0" designator.

Could that be causing the issue or am I looking for ghosts in the wrong places?

**Comment by XWingMitch0** [comment]
![image](https://user-images.githubusercontent.com/58368127/196063523-85056fd9-aab7-414a-8a16-f16c749b4b53.png)
![image](https://user-images.githubusercontent.com/58368127/196063529-d5a10f36-8627-423c-9c87-68179b91ee10.png)


Confirmed - the |2| designator in the data folder after the quest text is the issue. Changing the 2 to 0 fixed the issue!

**Comment by IrcDirk** [comment]
@XWingMitch0 Hmmm ok, that's because i doesn't have 80 lvl and i cant debug that :( Thanks for the tip.

Hmmm... and thats FACTION and yes it should be BOTH sides and its 2 so its HORDE only...

Need to fix that as soon as possible.

**Comment by IrcDirk** [comment]
Ok, should be fixed now ;)
