### ISSUE TITLE
Guild Control Issues

### ISSUE THREAD

**Issue by rockett30** [IrcDirk/Carbonite-Classic#269]
I'm having a problem with guild control. initially when I start the game and go into the controls, I get an error popup.

Date: 2022-10-23 09:21:19
ID: 1
Error occured in: Global
Count: 1
Message: Interface_Wrath\FrameXML\FriendsFrame_Wrath.lua line 296:
   Usage: GuildControlGetRankName(index)
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: GuildControlGetRankName()
   [string "@Interface_Wrath\FrameXML\FriendsFrame_Wrath.lua"]:296: GuildControlPopupframe_Update()
   [string "@Interface_Wrath\FrameXML\FriendsFrame_Wrath.lua"]:252: GuildControlPopupFrame_OnShow()
   [string "*:OnShow"]:1:
      [string "*:OnShow"]:1
   [string "=[C]"]: Show()
   [string "@Interface/FrameXML/FriendsFrame_Shared.lua"]:2303: GuildFramePopup_Show()
   [string "*:OnClick"]:4:
      [string "*:OnClick"]:1
Locals:

AddOns:
  Swatter, v3.4.6817 (SwimmingSeadragon)
  AtlasLootClassic, vv3.0.7
  AtlasLootClassicData, vv3.0.7
  AtlasLootClassicDungeonsAndRaids, vv3.0.7
  AucAdvanced, v3.4.6825 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6803 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6805 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6809 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6806 (SwimmingSeadragon)
  AucStatSimple, v3.4.6807 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6808 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6810 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v10.0.2
  Bartender4, v4.12.0
  BasicComboPoints, vv9.2.4
  BeanCounter, v3.4.6811 (SwimmingSeadragon)
  Carbonite, vv3.4.0-00031
  CarboniteNotes, vv3.4.0-00031
  CarboniteQuests, vv3.4.0-00031
  CarboniteSocial, vv3.4.0-00031
  CarboniteWarehouse, vv3.4.0-00031
  DataStore, v2022.06.05
  DataStoreAgenda, v1.14.003
  DataStoreAuctions, v1.14.003
  DataStoreCharacters, v2022.06.05
  DataStoreContainers, v1.14.003
  DataStoreCrafts, v1.14.003
  DataStoreInventory, v1.14.003
  DataStoreMails, v2022.06.05
  DataStoreQuests, v1.14.003
  DataStoreReputations, v1.14.003
  DataStoreSpells, v2022.06.05
  DataStoreTalents, v1.14.003
  DBMCore, v30070dd
  DBMSoundEventsPack, v1.6.18
  DBMStatusBarTimers, v30070dd
  DBMVPVEM, v1b93adf
  Decursive, v2.7.8.9
  Enchantrix, v3.4.6821 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6813 (SwimmingSeadragon)
  HealBot, v3.4.0.14
  HealBotData, v
  HealBotOptions, v
  HealBotPluginThreat, v3.4.0.0
  HealBotTips, v
  Identity2, v4.2.3
  Informant, v3.4.6814 (SwimmingSeadragon)
  Molinari, v90207.85-Release
  Recount, vv3.4.0a
  Scrap, v10.0.1
  SmartBuff, v38.30400
  Stubby, v3.4.6816 (SwimmingSeadragon)
  WeakAuras, v4.1.5
  ZPerl, v6.3.4
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v3.4.0.30400 <none>
  (ck=7f4)

After that the error never shows again, but the guild controls don't work.  All the selections are unchecked and non operational.
The only way I can get into the controls to change anything is to disable Carbonite and re-enable it when I'm done.

Thank you very much for keeping this addon alive, been using it for a dozen years.

**Comment by IrcDirk** [comment]
Damn i need to setup guild on my alt to test this ;)

**Comment by Termalator** [comment]
I "fixed" it bx commenting out the line 869 in the carbonite.lua: 

GuildControlPopupFrame.initialized = 1

The only thing i noticed is that the guild control frame is now behind the carbonite social frame, but i can live with that ;)

**Comment by rockett30** [comment]
Thanks for the work around.  Like you said, I can live with the guild control behind the carbonite frame.

**Comment by IrcDirk** [comment]
Should be fixed now ;)

**Comment by rockett30** [comment]
Not all hero's wear capes!
Thanks. Works great.

**Comment by Termalator** [comment]
I can confirm, yes works fine.
Thank you :)
