### ISSUE TITLE
Quest tracking issues

### ISSUE THREAD

**Issue by syswis** [IrcDirk/Carbonite-Classic#271]
Since one of the last updates I have issues with the automatic tracking quest.
New picked up quests do not get added to the watch list automatically and I have to manually open the carbonite questlog and tick the quest.

Some quests do not even show in the watch window (those not in the db, icecrown is full of them), only by toggling High watch priority shows them, and in that case, every time a quest objective is updated, the quest get automatically removed from the watch window.

I tried checking the Carbonite settings, and the auto track feature is enabled.
I tried to disable/enable the Blizzard tracking feature and nothing changes,

I noticed this issue while leveling my alt in Borean Tundra, and today with the daily quest [Maintaining Discipline] (ID: 13422) in the Storm Peaks.

Edit: Also if I manually unwatch a specific quest (TBC Raid quests ID:10445), after a /reload, it is back to being watched automatically.

**Comment by IrcDirk** [comment]
Yeah, the auto tracking is broken... It will be fixed but i dont know when. Just dont use it. Select quests and quest obectives by hand then it should work fine.

Some quests might not be in quest DB, we are depending on external databases, ill be making update soon.

**Comment by IrcDirk** [comment]
But new quests are added to quest watch window wihout issues on my side ... U sure u are using lates version?

**Comment by IrcDirk** [comment]
hmmm?

**Comment by Warbringer75** [comment]
same here i am having that same tracking issue on mine.  for quest and gathering nodes not showing up

**Comment by IrcDirk** [comment]
@Warbringer75  disable all other addons it might be other addon fault.
