### ISSUE TITLE
Adding pals to friendlist fails in WOTLK

### ISSUE THREAD

**Issue by Termalator** [IrcDirk/Carbonite-Classic#273]
If i try to add a pal to a friendlist (make red to friend) i am getting this:

`2x [string "AddFriend ("XXXX-XXXX")"]:1: attempt to call global 'AddFriend' (a nil value)
[string "AddFriend ("XXXX-XXXX")"]:1: in main chunk
[string "=[C]"]: in function `RunScript'
[string "@FrameXML\ChatFrame.lua"]:2196: in function `?'
[string "@FrameXML\ChatFrame.lua"]:4933: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4596: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4632: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
(*temporary) = nil
(*temporary) = "XXXX-XXXX"
(*temporary) = "attempt to call global 'AddFriend' (a nil value)"
`

i fixed it by changing all "AddFriend" in ~/Carbonite.Social/NxSocial.lua to "C_FriendList.AddFriend".

**Comment by IrcDirk** [comment]
Wil fix that soon. Thanks for the report.

**Comment by Termalator** [comment]
Thank you :)

**Comment by IrcDirk** [comment]
Should be fixed now.

**Comment by Termalator** [comment]
Yes it works, thank you very much :) and sorry for the late reply.
