### ISSUE TITLE
New mining nodes are not added to the database, with German client.

### ISSUE THREAD

**Issue by Termalator** [IrcDirk/Carbonite-Classic#274]
I imported the GatherMate2_Data and they work fine, but nodes that are not in this database wan't be added.

I am using the german client.

**Comment by Termalator** [comment]
sorry, now it worked, but i will look at it :)

**Comment by Termalator** [comment]
I am not sure if it was already there because it was on the border of two zones (appearing disappearing area). The other nodes where  in the middle of Wintergrasp so i am sure that it should be added but it wasn't.

**Comment by IrcDirk** [comment]
Ok, thanks... ill check that.

**Comment by Warbringer75** [comment]
i am having the issue too wit no gather showing up on the carbonite, also i am getting missing info when doing quest or dungeons, would dowb loading the gather addon help this nod issue or just the lib for it?

**Comment by IrcDirk** [comment]
@Termalator Sorry just checked and it records the nodes.

**Comment by Termalator** [comment]
I noticed it in Wintergrasp on some points and it still wan´t record this nodes. Maybe it is an issue with the German localization?

**Comment by IrcDirk** [comment]
Weird but maybe its cause of other client language... cant test it...

**Comment by Termalator** [comment]
is there a trigger that i can print out if new node is found? then i can test it here.

**Comment by IrcDirk** [comment]
Try here => https://github.com/IrcDirk/Carbonite-Classic/blob/3f65772da8b351f7cf270c23308607857c986904/Carbonite/Carbonite.lua#L1150

**Comment by Termalator** [comment]
hmm i added two lines with printouts :
(line 1135 ff)
`function Nx:OnUnit_spellcast_sent (event, arg1, arg2, arg3, arg4)	

    print(Nx:IsGathering(arg2))
	if arg1 == "player" then
		local Nx = Nx
		if Nx:IsGathering(arg2) == "Herb Gathering" then
			Nx.GatherTarget = Nx.TooltipLastText

			if Nx.db.profile.Debug.DBGather then
				Nx.prt (L["Gather"] .. ": %s %s", arg2, Nx.GatherTarget or "nil")
			end

			if Nx.GatherTarget then
				Nx.UEvents:AddHerb (Nx.GatherTarget)
				Nx.GatherTarget = nil
			end

		elseif Nx:IsGathering(arg2) == L["Mining"] then
		    print("Mining node")
			Nx.GatherTarget = Nx.TooltipLastText`

when i was on a German client nothing happened. On English client everything worked as expected.

**Comment by Termalator** [comment]
By the way i deleted all nodes so all nodes are "new"

**Comment by IrcDirk** [comment]
Try dumping all arguments on german client, just after this:

``function Nx:OnUnit_spellcast_sent (event, arg1, arg2, arg3, arg4)``

**Comment by IrcDirk** [comment]
Ohhh ... and u are mining or herbing?

**Comment by Termalator** [comment]
mining at this time

**Comment by Termalator** [comment]
i added print("arg1:" .. arg1 .. " arg2:" .. arg2 .. " arg3:" .. arg3 .. " arg4:" .. arg4) at line 1136 and that is the result:
arg1:player arg2:Titanvorkommen arg3:Cast-3-4460-571-48-50310-0000BC329F arg4:50310

**Comment by IrcDirk** [comment]
Yeah... seams there is no `Titanvorkommen` in Carbonite\Locales\deDE\HarvestNodes.lua

**Comment by Termalator** [comment]
i was looking at this too :)

**Comment by Termalator** [comment]
i will do so :)

**Comment by Termalator** [comment]
Wowhead seems to have correct translations, i will check them and post it here :)

**Comment by Termalator** [comment]
The herbs are looking good so far, but i will observe that, but here are the corrected mines:
`-- Mines
L["Adamantite Deposit"] = "Adamantitablagerung"
L["Ancient Gem Vein"] = "Uraltes Edelsteinvorkommen"
L["Blackrock Deposit"] = "Schwarzfelsvorkommen"
L["Cobalt Deposit"] = "Kobaltablagerung"
L["Copper Vein"] = "Kupfervorkommen"
L["Dark Iron Deposit"] = "Dunkeleisenablagerung"
L["Elementium Vein"] = "Elementiumader"
L["Fel Iron Deposit"] = "Teufelseisenvorkommen"
L["Ghost Iron Deposit"] = "Geistereisenvorkommen"
L["Gold Vein"] = "Goldvorkommen"
L["Incendicite Mineral Vein"] = "Pyrophormineralvorkommen"
L["Indurium Mineral Vein"] = "Induriummineralvorkommen"
L["Iron Deposit"] = "Eisenvorkommen"
L["Khorium Vein"] = "Khoriumvorkommen"
L["Kyparite Deposit"] = "Kyparitvorkommen"
L["Large Obsidian Chunk"] = "Gro\195\159er Obsidianbrocken"
L["Lesser Bloodstone Deposit"] = "Geringe Blutsteinablagerung"
L["Mithril Deposit"] = "Mithrilablagerung"
L["Nethercite Deposit"] = "Netheritablagerung"
L["Obsidium Deposit"] = "Obsidiumvorkommen"
L["Pyrite Deposit"] = "Pyritvorkommen"
L["Rich Adamantite Deposit"] = "Reiche Adamantitablagerung"
L["Rich Blackrock Deposit"] = "Reiches Schwarzfelsvorkommen"
L["Rich Cobalt Deposit"] = "Reiche Kobaltablagerung"
L["Rich Elementium Vein"] = "Reiche Elementiumader"
L["Rich Ghost Iron Deposit"] = "Reiches Geistereisenvorkommen"
L["Rich Kyparite Deposit"] = "Reiches Kyparitvorkommen"
L["Rich Obsidium Deposit"] = "Reiches Obsidiumvorkommen"
L["Rich Pyrite Deposit"] = "Reiches Pyritvorkommen"
L["Rich Saronite Deposit"] = "Reiche Saronitablagerung"
L["Rich Thorium Vein"] = "Reiches Thoriumvorkommen"
L["Rich Trillium Vein"] = "Reiche Trilliumader"
L["Rich True Iron Deposit"] = "Reiches Echteisenvorkommen"
L["Saronite Deposit"] = "Saronitablagerung"
L["Silver Vein"] = "Silbervorkommen"
L["Small Obsidian Chunk"] = "Kleiner Obsidianbrocken"
L["Small Thorium Vein"] = "Kleines Thoriumvorkommen"
L["Smoldering True Iron Deposit"] = "Qualmendes Echteisenvorkommen"
L["Thorium Vein"] = "Thoriumvorkommen" -- Used for Ooze covered even tho it's not a real node
L["Tin Vein"] = "Zinnvorkommen"
L["Titanium Vein"] = "Titanvorkommen"
L["Trillium Vein"] = "Trilliumader"
L["True Iron Deposit"] = "Echteisenvorkommen"
L["Truesilver Deposit"] = "Echtsilberablagerung"
--Legion Mines
L["Felslate Deposit"] = "Teufelsschiefervorkommen"
L["Felslate Seam"] = "Teufelsschieferfl\195\182z"
L["Living Felslate"] = "Lebender Teufelsschiefer"
L["Leystone Deposit"] = "Leysteinvorkommen"
L["Leystone Seam"] = "Leysteinfl\195\182z"
L["Living Leystone"] = "Lebender Leystein"
L["Infernal Brimstone"] = "Infernoschwefel"
-- 7.3 change
L["Empyrium Deposit"] = "Empyriumvorkommen"
L["Rich Empyrium Deposit"] = "Reiches Empyriumvorkommen"
L["Empyrium Seam"] = "Empyriumflöz"`

**Comment by Termalator** [comment]
i think the German names changed at some time.

**Comment by Termalator** [comment]
seems to work now :)

**Comment by Termalator** [comment]
found one herb that was wrong :
-- L["Talandra's Rose"] = "Talandra's Rose"
++ L["Talandra's Rose"] = "Talandras Rose"

**Comment by Termalator** [comment]
Thank you, looks good :)
