### ISSUE TITLE
Interface options frame

### ISSUE THREAD

**Issue by Quer77** [IrcDirk/Carbonite-Classic#276]
Date: 2022-12-02 00:29:25
ID: 1
Error occured in: Global
Count: 1
Message: [string "Interface/AddOns/Carbonite/Taintless.xml:<S..."] line 56:
   attempt to index global 'InterfaceOptionsFrame' (a nil value)
Debug:
   [string "Interface/AddOns/Carbonite/Taintless.xml:<Scripts>"]:56: in main chunk
Locals:
purgeKey = <function> defined Interface/AddOns/Carbonite/Taintless.xml:<Scripts>:11
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = "attempt to index global 'InterfaceOptionsFrame' (a nil value)"

AddOns:
  Swatter, v<%version%> (<%codename%>)
  AddonUsage, v3.1.2
  Auctioneer, v9.1.BETA.5.7 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.7 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.7 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.7 (OneMawTime)
  AutoRepair, v
  BagBrother, v
  Bagnon, v10.0.8
  BagnonGarbage, v2.0.42-Release
  Bartender4, v4.14.3
  BattleGroundEnemies, v10.0.2.2
  BetterWardrobe, v4.4.9
  Capping, vv10.0.9
  Carbonite, vv3.4.0-00040
  MogIt, vv3.9.12
  SlideBar, v<%version%> (<%codename%>)
  Stubby, v9.1.BETA.5.7 (OneMawTime)
  BlizRuntimeLib_enUS v10.0.2.100002 <none>
  (ck=262)

**Comment by IrcDirk** [comment]
Please describe your problem. Pasting only error will not help me fix the issue.

**Comment by Thrumbar** [comment]
Retail as well I think
