### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by Quer77** [IrcDirk/Carbonite-Classic#277]
Date: 2022-12-02 00:29:25
ID: 2
Error occured in: Global
Count: 1
Message: Interface/AddOns/Carbonite.Quests/NxQuest.lua line 6859:
   hooksecurefunc(): WatchFrame_Update is not a function
Debug:
   [string "=[C]"]: hooksecurefunc()
   [string "@Interface/AddOns/Carbonite.Quests/NxQuest.lua"]:6859: in main chunk
Locals:

AddOns:
  Swatter, v<%version%> (<%codename%>)
  AddonUsage, v3.1.2
  Auctioneer, v9.1.BETA.5.7 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.7 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.7 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.7 (OneMawTime)
  AutoRepair, v
  BagBrother, v
  Bagnon, v10.0.8
  BagnonGarbage, v2.0.42-Release
  Bartender4, v4.14.3
  BattleGroundEnemies, v10.0.2.2
  BetterWardrobe, v4.4.9
  Capping, vv10.0.9
  Carbonite, vv3.4.0-00040
  CarboniteNotes, vv3.4.0-00040
  CarboniteQuests, vv3.4.0-00040
  MogIt, vv3.9.12
  SlideBar, v<%version%> (<%codename%>)
  Stubby, v9.1.BETA.5.7 (OneMawTime)
  BlizRuntimeLib_enUS v10.0.2.100002 <none>
  (ck=2a3)

**Comment by IrcDirk** [comment]
Please describe your problem. Pasting only error will not help me fix the issue.

**Comment by IrcDirk** [comment]
Are u playing Classic WOTLK? Because just checked and `WatchFrame_Update` is a function...

**Comment by Thrumbar** [comment]
This is from retail
