### ISSUE TITLE
maps

### ISSUE THREAD

**Issue by Quer77** [IrcDirk/Carbonite-Classic#279]
Date: 2022-12-02 00:55:33
ID: 5
Error occured in: Global
Count: 1
Message: Interface/AddOns/Carbonite/NxOptions.lua line 556:
   bad argument #1 to 'pairs' (table expected, got nil)
Debug:
   [string "=(tail call)"]: ?
   [string "=(tail call)"]: ?
   [string "=[C]"]: pairs()
   [string "@Interface/AddOns/Carbonite/NxOptions.lua"]:556: member()
   [string "@Interface/AddOns/Bartender4/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:215:
      ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:164
   [string "@Interface/AddOns/Bartender4/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1280:
      ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1110
   [string "@Interface/AddOns/Bartender4/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1639: FeedGroup()
   [string "@Interface/AddOns/Bartender4/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1564:
      ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1548
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Bartender4/libs/AceGUI-3.0/AceGUI-3.0.lua"]:66:
      ...ace/AddOns/Bartender4/libs/AceGUI-3.0/AceGUI-3.0.lua:64
   [string "@Interface/AddOns/Bartender4/libs/AceGUI-3.0/AceGUI-3.0.lua"]:300: Fire()
   [string "@Interface/AddOns/Bartender4/libs/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua"]:342: SelectTab()
   [string "@Interface/AddOns/Bartender4/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1675: FeedGroup()
   [string "@Interface/AddOns/Bartender4/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1919: Open()
   [string "@Interface/AddOns/Bartender4/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1947:
      ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1945
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Bartender4/libs/AceGUI-3.0/AceGUI-3.0.lua"]:66:
      ...ace/AddOns/Bartender4/libs/AceGUI-3.0/AceGUI-3.0.lua:64
   [string "@Interface/AddOns/Bartender4/libs/AceGUI-3.0/AceGUI-3.0.lua"]:300: Fire()
   [string "@Interface/AddOns/Bartender4/libs/AceGUI-3.0/widgets/AceGUIContainer-BlizOptionsGroup.lua"]:20:
      ...GUI-3.0/widgets/AceGUIContainer-BlizOptionsGroup.lua:19
   [string "=[C]"]: Show()
   [string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:843: DisplayLayout()
   [string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:802: DisplayCategory()
   [string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:769:
      ...erface/SharedXML/Settings/Blizzard_SettingsPanel.lua:765
   [string "=[C]"]: ?
   [string "@Interface/SharedXML/CallbackRegistry.lua"]:143:
      Interface/SharedXML/CallbackRegistry.lua:142
   [string "=[C]"]: ?
   [string "@Interface/SharedXML/CallbackRegistry.lua"]:146: TriggerEvent()
   [string "@Interface/SharedXML/Settings/Blizzard_CategoryList.lua"]:136:
      ...terface/SharedXML/Settings/Blizzard_CategoryList.lua:134
Locals:
None
AddOns:
  Swatter, v<%version%> (<%codename%>)
  AddonUsage, v3.1.2
  Auctioneer, v9.1.BETA.5.7 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.7 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.7 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.7 (OneMawTime)
  AutoRepair, v
  BagBrother, v
  Bagnon, v10.0.8
  BagnonConfig, v
  BagnonGarbage, v2.0.42-Release
  Bartender4, v4.14.3
  BattleGroundEnemies, v10.0.2.2
  BetterWardrobe, v4.4.9
  Capping, vv10.0.9
  Carbonite, vv3.4.0-00040
  CarboniteNotes, vv3.4.0-00040
  CarboniteQuests, vv3.4.0-00040
  CarboniteSocial, vv3.4.0-00040
  CarboniteWarehouse, vv3.4.0-00040
  Details, v#Details.DF.Wrath.10304.147
  Gathering, v1.88
  GladiatorlosSA2, v4.0
  GSE, v3.1.21
  GSELDB, v3.1.21
  GTFO, v4.69.3
  HandyNotes, vv1.6.13
  HandyNotesDragonflight, v5
  HandyNotesDragonflightTreasures, vv20
  HHTD, v2.4.9.14
  Informant, v<%version%> (<%codename%>)
  MacroToolkit, vv10.0.2-5
  MacroToolkitIcons, vv10.0.2-5
  MogIt, vv3.9.12
  MogItArtifact, vv3.9.12
  MogItMail, vv3.9.12
  MogItOther, vv3.9.12
  MogItRanged, vv3.9.12
  NPCTime, v1.0.10
  Pawn, v2.7.13
  PerlArcaneBar, v
  PerlCombatDisplay, v
  PerlConfig, v
  PerlFocus, v
  PerlParty, v
  PerlPartyPet, v
  PerlPartyTarget, v
  PerlPlayer, v
  PerlPlayerPet, v
  PerlTarget, v
  PerlTargetTarget, v
  PetCare, v6.5.2 100002
  Plater, vPlater-v539-Retail
  Postal, vv3.9.2
  Prat30, v3.9.13
  Prat30Libraries, v
  RangeDisplay, vv5.0.4
  RangeDisplayOptions, vv5.0.4
  RareScanner, v10.0.2.2
  Scrap, v10.0.5
  ScrapConfig, v
  SilverDragon, vv2022.28
  SilverDragonOverlay, vv2022.28
  SilverDragonRangeExtender, vv2022.28
  SimpleItemLevel, v1
  SlideBar, v<%version%> (<%codename%>)
  Spy, v3.9.4
  StealthAlerter, v0.99.32
  Stubby, v9.1.BETA.5.7 (OneMawTime)
  TankMD, vv2.3.12
  Titan, v6.00.09.100002
  TitanBag, v6.00.09.100002
  TitanClock, v6.00.09.100002
  TitanGold, v6.00.09.100002
  TitanLocation, v6.00.09.100002
  TitanLootType, v6.00.09.100002
  TitanPerformance, v6.00.09.100002
  TitanReputations, vv1.34
  TitanVolume, v6.00.09.100002
  TitanXP, v6.00.09.100002
  TomTom, v3.3.5-release
  TradeSkillMaster, vv4.12.4
  BlizRuntimeLib_enUS v10.0.2.100002 <none>
  (ck=891)

**Comment by IrcDirk** [comment]
Same here bartender4.

`[string "@Interface/AddOns/Bartender4/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:215:`
