### ISSUE TITLE
LUA Error with GW2 UI 

### ISSUE THREAD

**Issue by DiscipleDarkfriend** [IrcDirk/Carbonite-Classic#284]
Not sure what this means, it seems to happen on reload UI and on new chars. 

21x Interface\AddOns\Carbonite\NxMap.lua:3185: attempt to index local 'map' (a nil value)
[string "@Interface\AddOns\Carbonite\NxMap.lua"]:3185: in function <Interface\AddOns\Carbonite\NxMap.lua:3166>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:2214: in function `SetUIPanel'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:2059: in function `ShowUIPanel'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:1927: in function <Interface_Wrath\FrameXML\UIParent.lua:1923>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:2733: in function `ShowUIPanel'
[string "@Interface\AddOns\GW2_UI\immersive\skins\worldmap.lua"]:68: in function `func'
[string "@Interface\AddOns\GW2_UI\GW2_ui-1.7.4-Wrath.lua"]:405: in function `RegisterLoadHook'
[string "@Interface\AddOns\GW2_UI\immersive\skins\worldmap.lua"]:237: in function `LoadWorldMapSkin'
[string "@Interface\AddOns\GW2_UI\GW2_ui-1.7.4-Wrath.lua"]:459: in function <Interface\AddOns\GW2_UI\GW2_ui.lua:423>
[string "@Interface\AddOns\GW2_UI\GW2_ui-1.7.4-Wrath.lua"]:826: in function <Interface\AddOns\GW2_UI\GW2_ui.lua:812>

Locals:
orgin = true
map = nil
(*temporary) = <table> {
 Menu_OnTrackPlyr = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2878
 GetInstanceID = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:9382
 ZoneOverlays = <table> {
 }
 GetZoneAchievement = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:11025
 MinimapOwnInit = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:1883
 RestoreBlizzBountyMap = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:3259
 MapLevels = <table> {
 }
 MinimapSetScale = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2507
 OnButToggleGuide = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:1634
 GetWinName = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:1219
 SetToCurrentZone = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:9464
 GetIconStatic = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:8495
 UpdateToolBar = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:1256
 Menu_OnBackgndAlphaFade = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2783
 BlizzToggleWorldMap = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:3286
 Menu_OnMapDebugFullCoords = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2829
 ClipFrameByMapType = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:7120
 ResetIcons = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:8222
 Minimap_OnEvent = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:1974
 UnpackObjective = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:11273
 GetWorldContinentInfo = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:9768
 ReverseTargets = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:10085
 GetWorldZoneScale = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:9832
 GMenu_OnPasteLink = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:3007
 CreateToolBar = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:1226
 GetPlayerMapPosition = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:11581
 RestoreWorldMap = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:11311
 DetachWorldMap = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:1469
 ClearTarget = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:10047
 BGMenu_OnHelp = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:3043
 VerifySettings = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:301
 HideMiniFrames = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:7007
 HideExtraZoneTiles = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:6359
 Menu_OnDetailAlpha = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2779
 IsInstanceMap = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:9709
 EkMapBlks = <table> {
 }
 CheckWorldHotspotsType = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:6197
 BuildPlyrLists = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:8634
 SetMapByID = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:230
 Menu_OnScaleRestore = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2743
 Menu_OnBackgndAlphaFull = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2795
 DraeneiXO = -3500
 SetIconTypeAlpha = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:7863
 CreateIconMenu = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:1266
 ScanContinents = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:5269
 MinimapUpdateMask = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2519
 OLMapBlks = <table> {
 }
 Menu_OnPlyrFollow = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2759
 Menu_OnGetQuests = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2869
 IconOnUpdateTooltip = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:8744
 Init = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:140
 UpdatePlyrHistory = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:5756
 Test = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:483
 Mo

**Comment by IrcDirk** [comment]
Thats not my fault. Ask GW2 UI creators :)

**Comment by DiscipleDarkfriend** [comment]
> Thats not my fault. Ask GW2 UI creators :)

I agree, it seems one can solve the issue by turning off the skin for the world map in GW2 settings, so if another encounters this issue now we know how to fix it in the meantime. Thanks for the quick reply and thank you for the awesome addon.

**Comment by IrcDirk** [comment]
I cant fix all things that other addons do :)

**Comment by DiscipleDarkfriend** [comment]
> I cant fix all things that other addons do :)

I get that I also have mods, I just wanted to let people know who they can have the addons play nice together and share the info so that we have somewhere to direct people. :)
