### ISSUE TITLE
Error When Using Hearth

### ISSUE THREAD

**Issue by Viracoocha** [IrcDirk/Carbonite-Classic#285]
This jsut started showing up since the most recent carbonite update.

Date: 2023-01-09 15:58:02
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite\Carbonite.lua line 3000:
   bad argument #1 to 'ipairs' (table expected, got nil)
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ipairs()
   [string "@Carbonite\Carbonite.lua"]:3000: IsGathering()
   [string "@Carbonite\Carbonite.lua"]:1132: ?()
   [string "@AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:109:
      ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:109
   [string "=[C]"]: ?
   [string "@AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:19:
      ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:15
   [string "@AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:54: Fire()
   [string "@Attune\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:120:
      ...ace\AddOns\Attune\Libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v3.4.6837 (SwimmingSeadragon)
  AdiBags, vv1.10.1
  AdiBagsItemRackSets, vv1.9
  Attune, v309
  AucAdvanced, v3.4.6844 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6803 (SwimmingSeadragon)
  AucScanData, v3.4.6804 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6805 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6809 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6806 (SwimmingSeadragon)
  AucStatSimple, v3.4.6807 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6808 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6810 (SwimmingSeadragon)
  BeanCounter, v3.4.6811 (SwimmingSeadragon)
  BigWigs, vv46.1-classic
  Bistooltip, v7.9
  Carbonite, vv3.4.0-00043
  CarboniteNotes, vv3.4.0-00043
  CarboniteQuests, vv3.4.0-00043
  CarboniteSocial, vv3.4.0-00043
  CarboniteWarehouse, vv3.4.0-00043
  Clique, vv3.4.12-release
  Details, v#Details.DF.Wrath.10403.148
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Dominos, v10.0.16
  DominosCast, v
  DominosConfig, v
  DominosProgress, v
  DominosRoll, v
  Enchantrix, v3.4.6849 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6813 (SwimmingSeadragon)
  GTFO, v5.0
  IceHUD, vv1.14.10
  Informant, v3.4.6850 (SwimmingSeadragon)
  ItemRack, v
  LeatrixPlus, v3.0.78
  LFGBulletinBoard, v3.08
  LibSharedMedia30, v3.0-130
  MRT, v4710
  Myslot, vv5.8.2-v3.4.0
  PallyPower, vv1.5.1-classic
  Pawn, v2.7.14
  ProfessionMaster, v1.6.1
  Questie, v7.4.5
  RXPGuides, vv4.4.10
  Skinner, vbeta10.47215.1
  SlideBar, v3.4.6851 (SwimmingSeadragon)
  SoulSort, v1.2 WOTLK
  Stubby, v3.4.6816 (SwimmingSeadragon)
  TidyPlatesThreatPlates, v11.1.8
  TotemTimers, v3.1.13
  TradeSkillMaster, vv4.12.18
  TradeSkillMasterAppHelper, vv4.12
  TradeSkillWhisper, v1.3.1
  WeakAuras, v5.3.4
  WowSimsExporter, v2.3
  ZPerl, v7.0.2
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v3.4.0.30400 <none>
  (ck=856)

**Comment by IrcDirk** [comment]
Thanks. Ill fix it tomorrow.

**Comment by Viracoocha** [comment]
Still got the error when I tried just now, however, I don't appear to have had an update on curseforge. Do I need to manually download it from here somewhere?

And, Thank you for this addon.  I have been using it forever, and I think it is one of the best out there!!

> Thanks. Ill fix it tomorrow.

**Comment by IrcDirk** [comment]
Fixed in v3.4.0-00044
