### ISSUE TITLE
Error when summoning mount

### ISSUE THREAD

**Issue by Auryannae** [IrcDirk/Carbonite-Classic#286]
This error shows when I summon my mount - not sure what the issue is and does not seem to affect gameplay:

Date: 2023-01-10 14:44:43
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite\Carbonite.lua line 3000:
   bad argument #1 to 'ipairs' (table expected, got nil)
Debug:
   [string "=(tail call)"]: ?
   [string "=(tail call)"]: ?
   [string "=[C]"]: ipairs()
   [string "@Carbonite\Carbonite.lua"]:3000: IsGathering()
   [string "@Carbonite\Carbonite.lua"]:1132: ?()
   [string "@Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119:
      ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [string "=[C]"]: ?
   [string "@Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29:
      ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   [string "@Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: Fire()
   [string "@BagBrother\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120:
      ...AddOns\BagBrother\libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None
AddOns:
  Swatter, v3.4.6837 (SwimmingSeadragon)
  Atlas, vv1.52.05
  AtlasBattlegrounds, vv1.52.01
  AtlasBurningCrusade, vv1.52.01
  AtlasClassicWoW, vv1.52.01
  AtlasDungeonLocs, vv1.52.01
  AtlasOutdoorRaids, vv1.52.02
  AtlasTransportation, vv1.52.01
  AtlasWrathoftheLichKing, vv1.52.01
  AtlasLootClassic, vv3.0.7
  AtlasLootClassicData, vv3.0.7
  AtlasLootClassicDungeonsAndRaids, vv3.0.7
  ATTClassic, v1.3.0
  AucAdvanced, v3.4.6844 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6803 (SwimmingSeadragon)
  AucScanData, v3.4.6804 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6805 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6809 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6806 (SwimmingSeadragon)
  AucStatSimple, v3.4.6807 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6808 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6810 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v10.0.14
  BeanCounter, v3.4.6811 (SwimmingSeadragon)
  Bistooltip, v7.9
  Carbonite, vv3.4.0-00043
  CarboniteNotes, vv3.4.0-00043
  CarboniteQuests, vv3.4.0-00043
  CarboniteSocial, vv3.4.0-00043
  CarboniteWarehouse, vv3.4.0-00043
  Clique, vv3.4.12-release
  Coordinates, v2.4
  DBMCore, vc5d63b5
  DBMStatusBarTimers, vc5d63b5
  DBMVPVEM, vfce23ce
  Enchantrix, v3.4.6849 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6813 (SwimmingSeadragon)
  FishingBuddy, v0.8.4
  GatherMate2, v1.46.3-classic
  HandyNotes, vv1.6.13
  HandyNotesDungeonLocationsClassic, v1.07a
  HandyNotesNPCsClassic, v1.32c
  HandyNotesTravelGuide, vv1.2
  HandyNotesWrathOfTheLichKing, vv10
  Informant, v3.4.6850 (SwimmingSeadragon)
  Outfitter, v3.0.2
  Peggle, v2.3.5
  Recount, vv3.4.0b
  SlideBar, v3.4.6851 (SwimmingSeadragon)
  Stubby, v3.4.6816 (SwimmingSeadragon)
  TradeSkillMaster, vv4.12.18
  WoWTexasHoldem, vwrath3.0.0
  ZPerl, v7.0.2
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v3.4.0.30400 <none>
  (ck=826)

**Comment by IrcDirk** [comment]
Fixed in v3.4.0-00044

**Comment by Auryannae** [comment]
Thank you!
