### ISSUE TITLE
CarboniteClassic-v3.4.0-00043    Errors everytime I shaft to cat or bear form had to go back to the previous file to be able to play 

### ISSUE THREAD

**Issue by F22Astroturf** [IrcDirk/Carbonite-Classic#287]
New install of Carbonite from 2 days ago ( CarboniteClassic-v3.4.0-00043 ) throws Errors when ever changing to either Cat or Bear on my Druid making unplayable had to uninstall and re-install previous version

**Comment by IrcDirk** [comment]
Fixed in v3.4.0-00044
