### ISSUE TITLE
Carbonite doesn't load - Curse Client old version

### ISSUE THREAD

**Issue by Al-Z-Homie** [IrcDirk/Carbonite-Classic#288]
I installed the App with CurseForge. Carbonite simply says, that it's loading in the chat, but nothing ever happens. I can't open the Map at all. I am running the Hardcore Mod, but it doesn't seem to interfere, since I literally turned of every other mod I had and even tried loading every single module of Carbonite 1 by 1, but nothing happens.

**Comment by IrcDirk** [comment]
Carbonite Classic ?

**Comment by Al-Z-Homie** [comment]
Yes

**Comment by IrcDirk** [comment]
Works fine, disable all other addons try only Carbonite + Modules.

**Comment by Al-Z-Homie** [comment]
All other Mods work.

**Comment by Al-Z-Homie** [comment]
Do I need to start the game through CurseForge? I'm starting it through the battle.net launcher, because if I start it with CurseForge it doesn't let me log in.

**Comment by IrcDirk** [comment]
Disable all other addons try only with Carbonite + Modules.

**Comment by Al-Z-Homie** [comment]
![image](https://user-images.githubusercontent.com/122836430/212773507-7effe4fb-9b83-449b-b040-ca53da7bc0f3.png)
![image](https://user-images.githubusercontent.com/122836430/212773554-d688a82e-4d92-44b1-84d5-226858a9e44c.png)
All other Mods are disabled. All I get is the message that it's loading and then nothing, can't open the Map

**Comment by IrcDirk** [comment]
U sure all addons disabled... i see msg from RestedXP. Did u reload after disabling?

**Comment by Al-Z-Homie** [comment]
![image](https://user-images.githubusercontent.com/122836430/212774198-30456a9f-0e5a-4430-9ffb-28a571f85580.png)
everything disabled

**Comment by IrcDirk** [comment]
OK. Your client is in English?

**Comment by Al-Z-Homie** [comment]
yes

**Comment by IrcDirk** [comment]
Try to load Carbonite Maps only... U sure u are on the latest version from Curse=> CarboniteClassic-v3.4.0-00045 ?

**Comment by Al-Z-Homie** [comment]
![image](https://user-images.githubusercontent.com/122836430/212774746-39cb92f9-e581-4bde-810e-e21abfc7dcfc.png)

**Comment by Al-Z-Homie** [comment]
It's sadly the same with maps only. I already tried that before and again just now.

**Comment by IrcDirk** [comment]
Thats some old version... It sould be:

![obraz](https://user-images.githubusercontent.com/1030023/212774913-56fc36f6-1a1f-4387-ad15-75c62ec8bcef.png)

**Comment by Al-Z-Homie** [comment]
Hmmm weird it's doesn't show up in my curseforge list 
![image](https://user-images.githubusercontent.com/122836430/212775017-09874724-c433-4210-bb52-3eac0b4c9ca7.png)

**Comment by IrcDirk** [comment]
Uninstall this old version. Restart Curse Client and search for Carbonite Classic, install latest.

**Comment by Al-Z-Homie** [comment]
I just tried reinstalling CurseForge as it clearly is the Problem here, but it still doesn't show in the App. When I try to run the file from the Homepage
![image](https://user-images.githubusercontent.com/122836430/212776126-6adaabed-4877-43c9-9d62-1a96c097435e.png)
 I get this: 
![image](https://user-images.githubusercontent.com/122836430/212776055-7e9768ce-77c0-4909-9bb4-f383628d4ef0.png)

**Comment by IrcDirk** [comment]
Contact Curse on this issue. I cant help u more with this.

**Comment by Al-Z-Homie** [comment]
Thank you very very much. You helped a lot in identifying the problem. I definitely willing to jump through some hoops, to get my favourite addon :)

**Comment by IrcDirk** [comment]
Let me know if you managed to solve this problem.

**Comment by Al-Z-Homie** [comment]
I didn't get any solution from curseforge yet, so I installed the Addon manually. It works fine, except for Carbonite Quests. I narrowed it down to this by disabling everything else, 1 by 1. Carbonite Quests causes my framerate to drop drastically and after a minute or so I get the following message: 
![image](https://user-images.githubusercontent.com/122836430/212951797-2b8b8ec9-750f-4d8f-b8b3-9713dbe5453d.png)

**Comment by IrcDirk** [comment]
Questie and Carbonite might not work together.

wt., 17 sty 2023, 17:11 użytkownik Al-Z-Homie ***@***.***>
napisał:

**Comment by Al-Z-Homie** [comment]
I disabled everything else, except for Carbonite Maps and Quests. It works fine with just Maps, but as soon as I activate Quests the Framerate drops.

**Comment by Al-Z-Homie** [comment]
Is your latest version for Wotlk Classic? I need the latest version for Vanilla Classic.

**Comment by Al-Z-Homie** [comment]
Do you have an old file that works on vanilla? Not SoM, just vanilla classic.

**Comment by IrcDirk** [comment]
@Al-Z-Homie Try this one => https://www.curseforge.com/wow/addons/carbonite-classic/files/3459172

**Comment by Al-Z-Homie** [comment]
It works!!! Thank you very much.
