### ISSUE TITLE
Question to Alliance Players

### ISSUE THREAD

**Issue by IrcDirk** [IrcDirk/Carbonite-Classic#29]
How do you cross from Duskwood to Elwynn forest or back? Give me coords. Thanks.

**Comment by jerj** [comment]
Do you mean, where do we cross the river while doing the few quests that cross the two zones? For that, for me, it's usally about 77, 16 in Duskwood... Or 80, 88 in Elwynn. Usually only for the Stalvan Mistmantle quest line.

**Comment by chaosrecords** [comment]
There isnt a connection point. People just swim across the river.
Thats why the connection point goes 2x in westfall to elwynn and Duskwood and there is a connector off of redridge mountains area with a bridge.  at 49.46

**Comment by chuman72486** [comment]
Officially there isn't a direct connector between Elwynn and Duskwood, but there is a bridge in Redridge into Duskwood, right at the border with Elwynn.  It's sort of a three-points intersection for the three zones.  That's the only land-based connector aside from traveling through Westfall.

![image](https://user-images.githubusercontent.com/8305657/65290854-d7f26680-db1e-11e9-9a35-c9f4f7237726.png)

**Comment by IrcDirk** [comment]
Ok, thanks all. Just want to find best place to cross between Elwynn and Duskwood.
