### ISSUE TITLE
Warehouse Error after 3.4.1 Update

### ISSUE THREAD

**Issue by Auryannae** [IrcDirk/Carbonite-Classic#293]
I received this error when opening a vendor window:

Date: 2023-01-18 14:05:19
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/Carbonite.Warehouse/NxWarehouse.lua line 3094:
   Usage: GetItemInfo(itemID|"name"|"itemlink")
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: GetItemInfo()
   [string "@Interface/AddOns/Carbonite.Warehouse/NxWarehouse.lua"]:3094: OnMerchant_show()
   [string "@Interface/AddOns/Carbonite.Warehouse/NxWarehouse.lua"]:1099: ?()
   [string "@Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109:
      ...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109
   [string "=[C]"]: ?
   [string "@Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19:
      ...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15
   [string "@Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: Fire()
   [string "@Interface/AddOns/Carbonite/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120:
      .../AddOns/Carbonite/Libs/AceEvent-3.0/AceEvent-3.0.lua:119
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v3.4.6837 (SwimmingSeadragon)
  AtlasLootClassic, vv3.1.0
  AtlasLootClassicData, vv3.1.0
  AtlasLootClassicDungeonsAndRaids, vv3.1.0
  ATTClassic, v1.3.2
  Bistooltip, v7.13
  Carbonite, vv3.4.1-00001
  CarboniteNotes, vv3.4.1-00001
  CarboniteQuests, vv3.4.1-00001
  CarboniteSocial, vv3.4.1-00001
  CarboniteWarehouse, vv3.4.1-00001
  Coordinates, v2.4
  DBMCore, va119c9f
  DBMStatusBarTimers, va119c9f
  DBMVPVEM, v8a47308
  GatherMate2, v1.47-classic
  Recount, vv3.4.1b
  SlideBar, v3.4.6851 (SwimmingSeadragon)
  Stubby, v3.4.6816 (SwimmingSeadragon)
  TradeSkillMaster, vv4.12.25
  ZPerl, v7.0.4
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v3.4.1.30401 <none>
  (ck=3c1)

**Comment by IrcDirk** [comment]
Which vendor?

**Comment by Auryannae** [comment]
I'm sorry I don't remember, I think it was in Silvermoon - if it happens again I'll make note of which one

**Comment by Viracoocha** [comment]
I just got it on Kayren Soothallow (General Goods) in Tarren Mill:

Date: 2023-01-18 19:11:18
ID: 2
Error occured in: Global
Count: 1
Message: Interface/AddOns/Carbonite.Warehouse/NxWarehouse.lua line 3094:
   Usage: GetItemInfo(itemID|"name"|"itemlink")
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: GetItemInfo()
   [string "@Interface/AddOns/Carbonite.Warehouse/NxWarehouse.lua"]:3094: OnMerchant_show()
   [string "@Interface/AddOns/Carbonite.Warehouse/NxWarehouse.lua"]:1099: ?()
   [string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109:
      ...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109
   [string "=[C]"]: ?
   [string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19:
      ...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15
   [string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: Fire()
   [string "@Interface/AddOns/Carbonite/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120:
      .../AddOns/Carbonite/Libs/AceEvent-3.0/AceEvent-3.0.lua:119
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v3.4.6837 (SwimmingSeadragon)
  AdiBags, vv1.10.6
  AdiBagsConfig, vv1.10.6
  BigWigs, vv46.1-classic
  Bistooltip, v7.13
  Carbonite, vv3.4.1-00001
  CarboniteNotes, vv3.4.1-00001
  CarboniteQuests, vv3.4.1-00001
  CarboniteSocial, vv3.4.1-00001
  CarboniteWarehouse, vv3.4.1-00001
  Clique, vv3.4.12-release
  Dominos, v10.0.16
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  GTFO, v5.0
  IceHUD, vv1.14.11
  LeatrixPlus, v3.0.83
  LibSharedMedia30, v3.0-130
  MRT, v4720
  Pawn, v2.7.15
  Plater, vPlater-v548-Wrath
  ProfessionMaster, v1.6.1
  Questie, v7.4.7
  RXPGuides, vv4.4.12
  Skinner, vbeta10.47215.1
  SlideBar, v3.4.6851 (SwimmingSeadragon)
  SoulSort, v1.3 WOTLK
  Stubby, v3.4.6816 (SwimmingSeadragon)
  TotemTimers, v3.1.14
  TradeSkillMaster, vv4.12.25
  TradeSkillMasterAppHelper, vv4.12
  WeakAuras, v5.3.5
  ZPerl, v7.0.4
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v3.4.1.30401 <none>
  (ck=48a)

**Comment by IrcDirk** [comment]
Download version from this repo to test it.
