### ISSUE TITLE
Carbonite Notes error on setting/record Favs

### ISSUE THREAD

**Issue by Limperate** [IrcDirk/Carbonite-Classic#295]
Can't record any Fav Waypoints. throws errors at me.

54x Carbonite.Notes/NxFav.lua:1135: bad argument #8 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@Carbonite.Notes/NxFav.lua"]:1135: in function `CreateItem'
[string "@Carbonite.Notes/NxFav.lua"]:1255: in function `Record'
[string "@Carbonite/NxMap.lua"]:10004: in function `SetTarget'
[string "@Carbonite/NxMap.lua"]:10124: in function `SetTargetAtClick'
[string "@Carbonite/NxMap.lua"]:2711: in function `Func'
[string "@Carbonite/NxUI.lua"]:4968: in function <Carbonite/NxUI.lua:4938>

Locals:
(*temporary) = "%s~%c~%s~%s|%s|%s|%s"
(*temporary) = "T"
(*temporary) = 35
(*temporary) = "Goto 78, 25"
(*temporary) = "118"
(*temporary) = "77.765969062127"
(*temporary) = "24.621672857498"
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by Limperate** [comment]
Still same problem

**Comment by Limperate** [comment]
its also always the same coordinates and Zone ID in the Error

**Comment by IrcDirk** [comment]
Please check now.

**Comment by Limperate** [comment]
Great Job, it's working
