### ISSUE TITLE
Large map opening in mini map, and error when trying to move mini map

### ISSUE THREAD

**Issue by Viracoocha** [IrcDirk/Carbonite-Classic#296]
Date: 2023-02-04 11:31:28
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/Carbonite/NxUI.lua line 560:
   attempt to compare nil with number
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Carbonite/NxUI.lua"]:560: Util_IsMouseOver()
   [string "@Interface/AddOns/Carbonite/NxUI.lua"]:3146:
      Interface/AddOns/Carbonite/NxUI.lua:3122
Locals:
(*temporary) = 0.017000
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v3.4.6921 (SwimmingSeadragon)
  AdiBags, vv1.10.7
  AtlasLootClassic, vv3.1.1
  AtlasLootClassicData, vv3.1.1
  AtlasLootClassicDungeonsAndRaids, vv3.1.1
  BigWigs, vv47-classic
  Bistooltip, v7.16
  Carbonite, vv3.4.1-00005
  CarboniteNotes, vv3.4.1-00005
  CarboniteQuests, vv3.4.1-00005
  CarboniteSocial, vv3.4.1-00005
  CarboniteWarehouse, vv3.4.1-00005
  Clique, vv3.4.14-release
  Details, v#Details.DF.Wrath.10410.148
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v13.21
  ElvUILibraries, v1.00
  Gargul, v5.1.4
  GTFO, v5.0.4
  IceHUD, vv1.14.15
  LeatrixPlus, v3.0.102
  LibSharedMedia30, v3.0-132
  MoveAny, v1.0.46
  Pawn, v2.7.16
  Plater, vPlater-v552-Wrath
  ProfessionMaster, v1.6.3
  Questie, v7.4.12
  SoulSort, v1.3 WOTLK
  Stubby, v3.4.6920 (SwimmingSeadragon)
  TacoTip, v0.3.5
  TradeSkillMaster, vv4.12.32
  TradeSkillMasterAppHelper, vv4.12
  WeakAuras, v5.3.7
  BlizRuntimeLib_enUS v3.4.1.30401 <none>
  (ck=3f9)

**Comment by IrcDirk** [comment]
I don't see any of your problems and no one reported them. 

Please disable all other addons, check with only Carbonite and Modules enabled.

**Comment by Viracoocha** [comment]
I did have the same issue with Carbonite as the only addon that was enabled.  I went into the carbonite settings, turned off the minimap merge function, and set it to use the game map when M is pressed.  No issues then.  Once I went back in and re-activated the merge map and carbonite map using M, it seemd to correct the issue.

**Comment by IrcDirk** [comment]
So its resolved?
