### ISSUE TITLE
Missing feature to change the color of tracked quests

### ISSUE THREAD

**Issue by CristenPerret** [IrcDirk/Carbonite-Classic#297]
I currently use a backported version of the old version of 3.3.5, and it has the option to individually adjust the colors for each quest's painted "watch" box over the minimap/world map. Currently I have an issue even seeing the box zones, and them overlapping. Is there any particular reason it was cut, or am I missing where this feature was moved to?

I would greatly appreciate any response.

(also it seems the /nx command was removed too....)

**Comment by IrcDirk** [comment]
Thanks for the report. Didnt saw that and that was a bug after updating Ace3 libs. Should be fixed now.

What /nx commands did u use?

**Comment by CristenPerret** [comment]
Thanks for the quick answer and fix! o.o ❤️
/nx is a quick shorthand command for access to the Carbonite addon. I usually use /nx options / goto. 
I modded my copy to accept the /nx options instead. I've just used it for so long just was figured to mention too.

**Comment by IrcDirk** [comment]
If u have any other fixes u can make pull request :)
