### ISSUE TITLE
Carbonite not working on wow classic vanilla(1.14.3)

### ISSUE THREAD

**Issue by JSibecas** [IrcDirk/Carbonite-Classic#298]
Hello, I started playing vanilla wow again after a while and I noticed carbonite isnt working anymore there. I hope there is an easy way to update it to the new version of the game.

**Comment by IrcDirk** [comment]
Sorry vanilla is not supported any more.

**Comment by IrcDirk** [comment]
=> https://github.com/IrcDirk/Carbonite-Classic/issues/187
