### ISSUE TITLE
Opening Carbonite quest window opens the standard window in the background

### ISSUE THREAD

**Issue by aSnejbjerg** [IrcDirk/Carbonite-Classic#299]
Hey,

Whenever I open the Carbonite quest window the standard quest window opens as well but it's invisible.
That means it block me from opening any other window until I've opened the standard window with Alt-L  or opened the main menu by clicking the button in the bar (I can't press esc to open it)

**Comment by IrcDirk** [comment]
U sure that's not a fault caused by other addon? I don't see any problems opening other windows while Carbonite Quest window is open. Try disabling all addons except Carbonite + Modules and try again.

**Comment by aSnejbjerg** [comment]
I tried disabling all other addons than Carbonite, closing the game, starting it up again. The bug persists.
I've spoken with a few guildies who use the addon and they are experiencing it as well.

**Comment by IrcDirk** [comment]
Seriously i dont know whats the problem. Please provide me screenshots and example when it happens. All works fine on my side.

And u are playing WOTLK right?

**Comment by aSnejbjerg** [comment]
I find it kind of hard to screenshot something not visible but here's what I can see with my skills page :D 
Image 1 is my skills page without ever having opened the Carbonite quest log
Image 2 is when I've opened the carbonite quest log and closed it again
Yes, I am playing WotLK
![image](https://user-images.githubusercontent.com/42168095/227138330-d82908f2-1159-4202-945e-6db5f4344659.png)
![image](https://user-images.githubusercontent.com/42168095/227138460-190413a9-1407-4e75-a6b8-20a800c1a4a0.png)

**Comment by IrcDirk** [comment]
Hmmm... let me check this.

**Comment by IrcDirk** [comment]
Ok, got the same behaviour. But windows are usable, just moved...

**Comment by aSnejbjerg** [comment]
Also, when you get into this behaviour, you won't be able to hit Esc to open the game menu.

**Comment by aSnejbjerg** [comment]
Yep, it works! 
Awesome job :)
