### ISSUE TITLE
Gathering Icons

### ISSUE THREAD

**Issue by Swash1972** [IrcDirk/Carbonite-Classic#30]
Can't seem to get gathering icons to show at all.
Enabled in carbonite options, and even tried loading classic GatherMate2 addon.

**Comment by IrcDirk** [comment]
Not working yet... working on it.

**Comment by Jon-Murray** [comment]
Hi IrcDirk. Thanks for putting this in. I can confirm that this is working with herb/mining, but the treasure map option does not seem to display (the gathermate data is there though). Should i open a new issue here?

**Comment by IrcDirk** [comment]
Yes please open new issue.
