### ISSUE TITLE
Carbonite Locking down the LFG system 

### ISSUE THREAD

**Issue by Kamiklees** [IrcDirk/Carbonite-Classic#300]
Ongoing issiue i've had with Carbonite for months now, when engaging in any of the search function with classics LFG system this error will eventually occur, which locks down the entire search function, you can't view any groups or people listed in the LFG system untill a /reload or relog is done.

```
1x [ADDON_ACTION_BLOCKED] AddOn 'Carbonite' tried to call the protected function 'Search()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `Search'
[string "@Blizzard_LookingForGroupUI/Blizzard_LFGBrowse.lua"]:226: in function `LFGBrowse_DoSearch'
[string "@Blizzard_LookingForGroupUI/Blizzard_LFGBrowse.lua"]:179: in function `SearchActiveEntry'
[string "@Blizzard_LookingForGroupUI/Blizzard_LFGParentFrame.lua"]:92: in function `LFGParentFrame_SearchActiveEntry'
[string "@Blizzard_LookingForGroupUI/Blizzard_LFGListing.lua"]:69: in function <...s/Blizzard_LookingForGroupUI/Blizzard_LFGListing.lua:51>
```

![Screenshot_3](https://user-images.githubusercontent.com/128751130/227370447-58dd2ce5-2397-48d4-b9c6-d9837cef9cbd.jpg)

**Comment by IrcDirk** [comment]
Works fine on my side. Disable all addons, just leave Carbonite + Modules enabled and check again.

**Comment by IrcDirk** [comment]
ew
