### ISSUE TITLE
spam error.

### ISSUE THREAD

**Issue by Andoido1** [IrcDirk/Carbonite-Classic#301]
1972x Carbonite/NxTravel.lua:389: attempt to index local 'dstInfo' (a nil value)
[string "@Carbonite/NxTravel.lua"]:389: in function `MakePath'
[string "@Carbonite/NxMap.lua"]:5914: in function `CalcTracking'
[string "@Carbonite/NxMap.lua"]:5867: in function `?'
[string "@Carbonite/NxMap.lua"]:5045: in function `Update'
[string "@Carbonite/NxMap.lua"]:3933: in function <Carbonite/NxMap.lua:3817>

Locals:
self = <table> {
 LegionFlyName = ""
 CaptureTaxi = <function> defined @Carbonite/NxTravel.lua:102
 UnregisterAllEvents = <function> defined @AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 MakePath = <function> defined @Carbonite/NxTravel.lua:374
 OnTaximap_opened = <function> defined @Carbonite/NxTravel.lua:89
 FindConnection = <function> defined @Carbonite/NxTravel.lua:736
 TaxiFindNodeFromRouteXY = <function> defined @Carbonite/NxTravel.lua:239
 DebugCaptureTaxi = <function> defined @Carbonite/NxTravel.lua:837
 Travel = <table> {
 }
 TaxiCalcTime = <function> defined @Carbonite/NxTravel.lua:167
 FindFlight = <function> defined @Carbonite/NxTravel.lua:597
 Add = <function> defined @Carbonite/NxTravel.lua:55
 RegisterMessage = <function> defined @AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 VisitedMapIds = <table> {
 }
 GetRidingSkill = <function> defined @Carbonite/NxTravel.lua:889
 SendMessage = <function> defined @AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49
 TaxiSaveTime = <function> defined @Carbonite/NxTravel.lua:334
 FindClosest = <function> defined @Carbonite/NxTravel.lua:682
 Speed = 0.222222
 Init = <function> defined @Carbonite/NxTravel.lua:30
 RegisterEvent = <function> defined @AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterAllMessages = <function> defined @AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 FlyingMount = false
 TaxiFindConnectionTime = <function> defined @Carbonite/NxTravel.lua:260
 PandariaFlyName = ""
 WrathFlyName = "Cold Weather Flying"
 DraenorFlyName = ""
 AzerothFlyName = ""
 TakeTaxiNode = <function> defined @Carbonite/NxTravel.lua:134
 TaxiTimer = <function> defined @Carbonite/NxTravel.lua:319
 UnregisterEvent = <function> defined @AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 OrigTakeTaxiNode = <function> defined @ZygorGuidesViewerClassicTBC/Libs/LibTaxi-1.0/LibTaxi-1.0.lua:1002
}
tracking = <table> {
}
srcMapId = 1434
srcX = 2070.695324
srcY = 2122.038302
dstMapId = 947
dstX = 0
dstY = 0
targetType = "Goto"
Map = <table> {
 Menu_OnTrackPlyr = <function> defined @Carbonite/NxMap.lua:2862
 GetInstanceID = <function> defined @Carbonite/NxMap.lua:9373
 ZoneOverlays = <table> {
 }
 GetZoneAchievement = <function> defined @Carbonite/NxMap.lua:11020
 MinimapOwnInit = <function> defined @Carbonite/NxMap.lua:1861
 RestoreBlizzBountyMap = <function> defined @Carbonite/NxMap.lua:3243
 MapLevels = <table> {
 }
 MinimapSetScale = <function> defined @Carbonite/NxMap.lua:2491
 OnButToggleGuide = <function> defined @Carbonite/NxMap.lua:1612
 GetWinName = <function> defined @Carbonite/NxMap.lua:1212
 SetToCurrentZone = <function> defined @Carbonite/NxMap.lua:9455
 GetIconStatic = <function> defined @Carbonite/NxMap.lua:8472
 UpdateToolBar = <function> defined @Carbonite/NxMap.lua:1249
 Menu_OnBackgndAlphaFade = <function> defined @Carbonite/NxMap.lua:2767
 BlizzToggleWorldMap = <function> defined @Carbonite/NxMap.lua:3270
 Menu_OnMapDebugFullCoords = <function> defined @Carbonite/NxMap.lua:2813
 ClipFrameByMapType = <function> defined @Carbonite/NxMap.lua:7097
 ResetIcons = <function> defined @Carbonite/NxMap.lua:8199
 Minimap_OnEvent = <function> defined @AddOn

**Comment by IrcDirk** [comment]
Closing since i dont have the info to debug this issue.
