### ISSUE TITLE
Carbonite-Classic Game Version: 3.4.1  on Curseforge

### ISSUE THREAD

**Issue by datgrl** [IrcDirk/Carbonite-Classic#302]
I installed the addon in _classic-era_ .  I can't interact with the Carbonite map icon using any combination of mouse buttons. I only had the gather guide, map and quest functions enabled.  I disabled all other addons and it didn't correct the issue.  I have a Steelcase Aerox 3 mouse if that helps.

**Comment by IrcDirk** [comment]
I only support Wotlk version of Classic Wow. Sorry.

pt., 28 kwi 2023, 17:43 użytkownik datgrl ***@***.***>
napisał:

**Comment by IrcDirk** [comment]
But maybe folder version still works in classic-era. Look in issues someone wrote about that some time ago.
