### ISSUE TITLE
Carbonite update for Classic WOW version 1.14.3/4

### ISSUE THREAD

**Issue by Carician** [IrcDirk/Carbonite-Classic#303]
Hello,
         Carbonite has been one of my favorite mods. mostly cause the maps and quest helper built in. I am trying to play some classic doing Hardcore runs and I can say I'm feeling extremely lonely with out being able to use Carbonite due to multiple errors. What ya say can I look forward to an update? Below are screen shots on what errors I am getting and list of addons I have active at the time of said errors. Looking at the errors I would disable said addon Carbonite is having issues with but more and more errors keeps showing up. Thanks!

![WowClassic_8NKZ9DLrPj](https://github.com/IrcDirk/Carbonite-Classic/assets/133024394/b56940dc-2767-4a85-a809-4619d4baf709)
![WowClassic_VIwXUXAK76](https://github.com/IrcDirk/Carbonite-Classic/assets/133024394/dea80aef-177d-4bd3-b40d-816a4a9e21d9)
![WowClassic_KeuLXM47iR](https://github.com/IrcDirk/Carbonite-Classic/assets/133024394/8b4bfa42-b620-452f-ac86-80c1ded5bc16)
![WowClassic_DGPWa2o3DH](https://github.com/IrcDirk/Carbonite-Classic/assets/133024394/94ac2161-7124-446b-983f-facd24b0785e)
![WowClassic_3t07q9Cjrl](https://github.com/IrcDirk/Carbonite-Classic/assets/133024394/c725c376-8741-4072-995b-4230419d6a8f)
![WowClassic_YW04nZ4ulB](https://github.com/IrcDirk/Carbonite-Classic/assets/133024394/2459aa4a-0b4a-4847-a871-86f79fd18614)
![WowClassic_ftypaMI8VC](https://github.com/IrcDirk/Carbonite-Classic/assets/133024394/be8a58d6-5879-4064-8a21-37726d1ec7f7)
![WowClassic_flZgpvw0dH](https://github.com/IrcDirk/Carbonite-Classic/assets/133024394/c2405688-e30d-41d0-af36-0a82b73c2cdf)

**Comment by IrcDirk** [comment]
I only support Wotlk right now. Sorry...

wt., 9 maj 2023, 16:42 użytkownik Carician ***@***.***>
napisał:

**Comment by IrcDirk** [comment]
U can try your luck with this https://github.com/IrcDirk/Carbonite-Classic/issues/187 but i dont know if that still work.

**Comment by artscout** [comment]
It works, I checked two weeks ago.
