### ISSUE TITLE
various bugs in Classic Era 

### ISSUE THREAD

**Issue by WoWEye** [IrcDirk/Carbonite-Classic#306]
I have the latest version but its gone buggy. Attaching all errors for each option.
Left click on the minimap button does not open the map - no error
Alt Left click to open the Watchlist results in this error:
Date: 2023-06-17 23:28:02
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite\Carbonite.lua line 3621:
   attempt to index local 'w' (a nil value)
Debug:
   [string "=[C]"]: ?
   [string "@Carbonite\Carbonite.lua"]:3621: NXOnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:

AddOns:
  Swatter, v1.13.6652 (SwimmingSeadragon)
  Ace3, vr1304
  AdiBags, vv1.10.7
  AdiBagsBetterCategories, v0.3.1-classic
  Altoholic, v1.14.005
  AraBrokerGuildFriends, vr95
  Armory, vv1.11.2
  AucAdvanced, v1.13.6717 (SwimmingSeadragon)
  AucFilterBasic, v1.13.6680 (SwimmingSeadragon)
  AucStatHistogram, v1.13.6681 (SwimmingSeadragon)
  AucStatiLevel, v1.13.6705 (SwimmingSeadragon)
  AucStatPurchased, v1.13.6672 (SwimmingSeadragon)
  AucStatSimple, v1.13.6634 (SwimmingSeadragon)
  AucStatStdDev, v1.13.6635 (SwimmingSeadragon)
  AucUtilFixAH, v1.13.6608 (SwimmingSeadragon)
  Auctionator, v10.1.7
  BeanCounter, v1.13.6682 (SwimmingSeadragon)
  BlizzMove, vv3.5.11
  BrokerEverything, v4.2.9-release
  Carbonite, v@project-version@
  CarboniteNotes, v@project-version@
  CarboniteQuests, v@project-version@
  CTBarMod, v10.0.7.2
  CTBottomBar, v10.0.5.2
  CTCore, v10.0.2.5
  CTLibrary, v10.1.0.1
  CTMailMod, v10.0.7.1
  CTMapMod, v10.0.5.2
  DataStore, v2023.05.04
  DataStoreAgenda, v2023.05.18
  DataStoreAuctions, v1.14.003
  DataStoreCharacters, v2023.05.03
  DataStoreContainers, v1.14.003
  DataStoreCrafts, v1.14.003
  DataStoreInventory, v1.14.003
  DataStoreMails, v2023.05.04
  DataStoreQuests, v1.14.003
  DataStoreReputations, v1.14.003
  DataStoreSpells, v2023.05.03
  DataStoreTalents, v1.14.003
  DBMCore, vabd1a2e
  DBMStatusBarTimers, vabd1a2e
  DBMVPVEM, v5b8dc58
  Details, v#Details.20230520.11023.151
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DropTheCheapestThing, vv2023.2
  Enchantrix, v1.13.6731 (SwimmingSeadragon)
  FishingBuddy, v0.9.2
  FleecingTip, v113.1770(200720)
  GatherMate2, v1.47-classic
  GTFO, v5.0.5
  Guildbook, v4.99412
  Informant, v1.13.6729 (SwimmingSeadragon)
  LeatrixMaps, v1.14.112
  MageButtons, v1.04
  MobInfo2, v10.1.15
  Pawn, v2.8.1
  PLG, v3.0
  PortalMage, v2.1.6-classic
  RatingBuster, v
  ReagentRecipeClassic, v1.6.5
  RecipeRadarClassic, v1.0.0.23
  SheepMonitor, v1.24
  SilverDragon, vv2023.6.1
  SilverDragonOverlay, vv2023.6.1
  SilverDragonRangeExtender, vv2023.6.1
  SmartBuff, v41.11403
  SmexyMats, vClassic + TBC
  StatLogic, v
  Stubby, v1.13.6614 (SwimmingSeadragon)
  TipTac, v22.09.02
  TipTacItemRef, v22.09.02
  TitanClassic, v1.3.1.11403
  TitanClassicBag, v1.3.1.11403
  TitanClassicGold, v1.3.1.11403
  TitanClassicLootType, v1.3.1.11403
  TitanClassicRepair, v1.3.1.11403
  TitanClassicXP, v1.3.1.11403
  TitanProfessionsMulti, vv9.2.4
  TomTom, vv3.3.9-release
  WaterDispenser, v1.11
  WhatsTraining, v4.0.5
  WIM, v3.10.12
  WoWPro, v2023.05.11.Aelease 2023.01.25.A
  WoWProAchievements, v2023.05.11.A
  WoWProDailies, v2023.05.11.A
  WoWProLeveling, v2023.05.11.A
  WoWProProfession, v2023.05.11.A
  WoWProWorldEvents, v2023.05.11.A
  XLoot, v9.2.7-1
  XLootFrame, v9.2.7-1
  XLootGroup, v9.2.7-1
  XLootMonitor, v9.2.7-1
  ZPerl, v7.0.7
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerPet, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v1.14.3.11403 <none>
  (ck=bc9)

Middle click to toggle guide gives:
Date: 2023-06-17 23:29:19
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite\Carbonite.lua line 3628:
   attempt to index a nil value
Debug:
   [string "=[C]"]: ?
   [string "@Carbonite\Carbonite.lua"]:3628: NXOnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:

And Right click for guide gives nothing

**Comment by IrcDirk** [comment]
I only support Carbonite Classic for WOTLK.

For Classic Era check this => https://github.com/IrcDirk/Carbonite-Classic/issues/303
