### ISSUE TITLE
Stranglehorn Vale Missing quest not in database

### ISSUE THREAD

**Issue by Spydereagle** [IrcDirk/Carbonite-Classic#308]
Serval quests says it's not in the data base 
[37] The Stone of the Tides
[38] Kurzen's Mystery
[38] Special Forces 
[37] Water Elementals 
[40] Colonel Kurzen
and most of the Catlyn blade chain quests are not showing up either.
Hope you can fix them soon...

**Comment by IrcDirk** [comment]
All those quest are in database, just checked the files. 
Maybe u got some errors and quest database is not fully loaded? 
Or u configured quest module this way and so your database is not fully loaded?

**Comment by IrcDirk** [comment]
Can someone else check those quests on ally side? I dont have ally char at this level.

**Comment by Spydereagle** [comment]
I have A Brother i talk to every day He lives in a Different state he has the same problems with the same quests when trying to do the quests they don't show up but once the quests are completed they show up on were to turn then in the just don't show where the needed area is

**Comment by IrcDirk** [comment]
Please show me your Quest Module => Database options:

![obraz](https://github.com/IrcDirk/Carbonite-Classic/assets/1030023/b0961b42-6359-4116-ae25-b9451cc4ed2f)

**Comment by Spydereagle** [comment]
![image](https://github.com/IrcDirk/Carbonite-Classic/assets/98191579/658c6b14-d916-4185-9fff-5d075e54400e)

**Comment by IrcDirk** [comment]
Ok, im making DK with ally race so ill debug it soon.

Your Quest Module options seems fine.

**Comment by IrcDirk** [comment]
Found the bug. Should be fixed now :)

**Comment by Spydereagle** [comment]
it is now working ty
