### ISSUE TITLE
Carbonite Classic Era - 1.14.4 update - PR?

### ISSUE THREAD

**Issue by Kaboca** [IrcDirk/Carbonite-Classic#313]
I updated the source code released for game version 1.13.4 (Carbonite-Classic-1.02.zip (04/11/2022) , but I can't find the related github project to make a pull request.

**Comment by IrcDirk** [comment]
Oh... ok thanks, here is new branch for Classic-Era => https://github.com/IrcDirk/Carbonite-Classic/tree/classic-era

**Comment by IrcDirk** [comment]
Or just zip it and attach here and ill upload it where it should be ;)

**Comment by Kaboca** [comment]
Ok, I downloaded the classic-era branch, but it doesn't match the one you can download from corseforge, so I'm attaching it rather than a zip. 
[Carbonite.zip](https://github.com/IrcDirk/Carbonite-Classic/files/12526149/Carbonite.zip)
[Carbonite.Quests.zip](https://github.com/IrcDirk/Carbonite-Classic/files/12526156/Carbonite.Quests.zip)

**Comment by Kaboca** [comment]
I only updated the two modules that I usually use.

**Comment by IrcDirk** [comment]
Uploaded those two to Classic Era branch.
