### ISSUE TITLE
Addon action Blocked

### ISSUE THREAD

**Issue by Raven427** [IrcDirk/Carbonite-Classic#314]
69x [ADDON_ACTION_BLOCKED] AddOn 'Carbonite.Quests' tried to call the protected function 'WatchFrame:Hide()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `Hide'
[string "@Carbonite.Quests/NxQuest.lua"]:6860: in function <Carbonite.Quests/NxQuest.lua:6860>
[string "=[C]"]: in function `WatchFrame_Update'
[string "@Interface_Wrath/FrameXML/WatchFrame.lua"]:254: in function <Interface_Wrath/FrameXML/WatchFrame.lua:224>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507

**Comment by Gh0styyy** [comment]
Also been having this issue alot. Along with instance maps and Wintergrasp maps not loading at all.
