### ISSUE TITLE
LFG Instance Eye not showing

### ISSUE THREAD

**Issue by sennellin** [IrcDirk/Carbonite-Classic#316]
Upon joining an instance group with the new dungeon LFG tool in WotLK Classic, the "eye" bubble that gives options to teleport in/out of the instance and leave the instance group does not appear in the carbonite sidebar. Requires disabling carbonite and using standard minimap eye to drop group after completion.

**Comment by ArthyrWOWClassic** [comment]
Myself and 3 other family members are also having this issue.

**Comment by IrcDirk** [comment]
Im not at home, ill try to fix it when im back.

sob., 14 paź 2023, 12:22 użytkownik ArthyrWOWClassic <
***@***.***> napisał:

**Comment by ChickenStrudel** [comment]
Solution:
In NxMap.lua  Line 10531.  Add ["MiniMapLFGFrame",] to the end of the string.  This adds LFG icon to variable [local mmOwnerNames]
Below is the full string modified.
"NXMiniMapBut","GameTimeFrame","TimeManagerClockButton","MiniMapWorldMapButton","MiniMapMailFrame","MiniMapTracking","MiniMapVoiceChatFrame","QueueStatusMinimapButton","MiniMapInstanceDifficulty","GarrisonLandingPageMinimapButton","MiniMapLFGFrame",
