### ISSUE TITLE
Carbonite map will not open - Classic Era

### ISSUE THREAD

**Issue by sogah87** [IrcDirk/Carbonite-Classic#319]
I do not know what else I can do.  I have looked through every option, disabled all other addons, re-centered UI.  I cannot get the carbonite map to open.  Pressing 'M' makes the map opening sound, but no map opens.  Minimap also does not change.  It remains the standard map..  I used to love using this app and I'm happy to see it updated.  Does anyone have any advice or ideas? Thank you.

**Comment by IrcDirk** [comment]
U are using it on WOTLK?

**Comment by sogah87** [comment]
> U are using it on WOTLK? If so then disable all other addons just leave Carbonite + Modules. If this will fix the issue then its another addon thats incompatibile with Carbonite.

Hey sorry I should have specified, I am on Classic Era, thank you.  I will try this fix as well.

**Comment by IrcDirk** [comment]
Only WOTLK is supported. But someone made pull request for fix for Classic Era and u can download it here https://github.com/IrcDirk/Carbonite-Classic/tree/classic-era
