### ISSUE TITLE
Carbonite Classic ERA not functional (Normal/SoD/HC)

### ISSUE THREAD

**Issue by dtnadevops** [IrcDirk/Carbonite-Classic#321]
When trying to use Carbonite in Hardcore classic the maps do not work at all.  Completely non functional.  Is this something that there is any plan to correct?

**Comment by IrcDirk** [comment]
ONLY Wotlk is supported.

**Comment by IrcDirk** [comment]
U can check Classic Era branch but its not my fix someone else made it => https://github.com/IrcDirk/Carbonite-Classic/tree/classic-era

**Comment by dtnadevops** [comment]
That leads to a functional map but none of the quests link to what I have in my quest log or what I have completed.  Sad to see I cannot use it, This is the best quest tracking tool in WoW for me.  Thanks for the info.

**Comment by Morrowdays** [comment]
pay you 100 dollars to fix carbonite for season of discovery, I do not want to be parted from one of my favorite addons ever during this adventure.

**Comment by Morrowdays** [comment]
Deal?

**Comment by IrcDirk** [comment]
Contact me by email.

**Comment by noahgithub** [comment]
I’ll pitch in another $20 if it works for HC as well. I feel blind without this tool. Questie and Tomtom don’t even come close to getting the job done.

**Comment by Morrowdays** [comment]
Morrowdays@rocketmail.com

**Comment by IrcDirk** [comment]
> I’ll pitch in another $20 if it works for HC as well. I feel blind without this tool. Questie and Tomtom don’t even come close to getting the job done.

It should work for both SoD and Hardcore.

**Comment by noahgithub** [comment]
Thank you. Sent the promised amount. Will test it let you know if anything isn’t working.

**Comment by Morrowdays** [comment]
oh sweet, you got it fixed? I just saw. do I send through donation?

**Comment by Morrowdays** [comment]
Sent, thanks for Carbonite and keep up the good work.

**Comment by IrcDirk** [comment]
Ok, u can find it here => https://github.com/IrcDirk/Carbonite-Classic/tree/classic-era

After tests ill upload it to Curse/WowInterface

**Comment by IrcDirk** [comment]
@noahgithub No errors? Works fine on my side. Try only with Carbonite + Modules.

**Comment by IrcDirk** [comment]
@noahgithub @dtnadevops U sure there are no errors? Try removing all saved variables related to Carbonite.

**Comment by IrcDirk** [comment]
This is the latest release for 1.15.0 => https://legacy.curseforge.com/wow/addons/carbonite-classic/files/4925855

**Comment by Hordehero** [comment]
@IrcDirk this one works like a charm! :D <3 thank you!  i've been feeling naked without Carbonite and Questie, as useful as it is, just has so much junk on your map it's stressful lol

Anywho, thanks a bunch!

**Comment by noahgithub** [comment]
I went to Carbonite / Profiles and Clicked reset profiles.  Still not showing quests in the list.  Is there another place to remove saved variables?

**Comment by IrcDirk** [comment]
@noahgithub Did u tried with all addons disabled only carbonite + modules? Do u use all modules?

**Comment by Vermistra** [comment]
I've noticed with using the new version for SoD, quest markers for quests you have not picked up yet do not show on the map at all. It does show the turn in location for the quest but no starting exclamation marks

**Comment by noahgithub** [comment]
I renamed the WTF Folder for my character name.  Disabled every other Addon and logged in.  Same thing.

**Comment by Decoy77** [comment]
Not sure what this update did but it had been working previously flawlessly on SoD, now after the update I'm just getting errors left and right.

**Comment by IrcDirk** [comment]
> Not sure what this update did but it had been working previously flawlessly on SoD, now after the update I'm just getting errors left and right.

I did not update anything ... there is only one version for 1.15.0

**Comment by Decoy77** [comment]
> > Not sure what this update did but it had been working previously flawlessly on SoD, now after the update I'm just getting errors left and right.
> 
> I did not update anything ... there is only one version for 1.15.0

I had been using some older previous version that worked without any errors, curseforge updated today and now doesn't work and just error after error.  Said that the version I had was possibly corrupt.

**Comment by IrcDirk** [comment]
@Decoy77 I just fixed your issue. But u need to download the newest version from this repo => https://github.com/IrcDirk/Carbonite-Classic/archive/refs/heads/classic-era.zip

**Comment by IrcDirk** [comment]
@noahgithub I think its some kind of bug with Quests, but u are not receiving any errors? Do u have BugGrabber and BugSack?

**Comment by IrcDirk** [comment]
@noahgithub and try the latest version from this repo it has some fixes => https://github.com/IrcDirk/Carbonite-Classic/archive/refs/heads/classic-era.zip

**Comment by noahgithub** [comment]
I have not downloaded the new one yet, Will try that, Tried to run the Previous version to see how it went, it stuttered a lot and gave me the message about it causing a lot of errors and offered to disable it.  I could not find the errors to send them though.  Will download your update and see if it makes a difference.

**Comment by noahgithub** [comment]
We appear to have a winner! No stuttering, the quests show up in the tracker and I can click on them for pathing that works! Looks good!  Will let you know if I find any other problems!

**Comment by noahgithub** [comment]
From my side of things, this appears to work normally in HC.  Money well spent on my favorite AddOn.  I don't see anything preventing updating Curseforge for HC.

**Comment by IrcDirk** [comment]
@noahgithub Great!!! So im uploading this fixed version to Curse :) Thanks for testing @Decoy77 and @noahgithub

**Comment by IrcDirk** [comment]
Im closing this thread. If any more problems just open new issue (one problem one issue).
