### ISSUE TITLE
Wotlk Classic - Disappearing Minimap when using "Combine Blizzard Minimap with Carbonite Minimap" option

### ISSUE THREAD

**Issue by Mugafo** [IrcDirk/Carbonite-Classic#322]
I just started playing classic for the first time so I had a fresh install of this through curseforge.

I noticed when I went to Dalaran the minimap would disappear unless I mouse over the carbonite map far enough outside the city. I saw this behavior in Iron Forge and the Death Knight starter area as well. Dungeons and Raids don't seem to have this problem.

I was able to repeat this behavior with the only addon enabled being carbonite and with fresh settings (deleted the SavedVariables). I loaded the game in the Death Knight area with no SavedVariables, I clicked yes to combine the maps, then once the reload happened, the minimap was hidden unless I mouse far enough to the west on the map outside of the instance map. None of the settings in the options appeared to fix the problem, maybe I am missing some setting.

As a local fix for myself, I commented out the following code and it stops the minimap from disappearing. Though this forces it to stay visible when the full size map is open.
https://github.com/IrcDirk/Carbonite-Classic/blob/44bb85e10b7d19feb9273bf041364ff45e3909cb/Carbonite/NxMap.lua#L2426-L2443

**Comment by IrcDirk** [comment]
Cant reproduce this issue :/

**Comment by IrcDirk** [comment]
@Mugafo Ohh and "Hide The Minimap when Fullsize" then u will have what u want ;)

**Comment by Mugafo** [comment]
@IrcDirk okay, strange I still get it no matter what I try, but I came up with a code change that made it work for me so I'll stick with that. Thanks for taking a look.
