### ISSUE TITLE
Feature Request: Uncombine Blizzard Minimap and Carbonite Minimap?

### ISSUE THREAD

**Issue by Havenloft** [IrcDirk/Carbonite-Classic#324]
After agreeing to combining the Blizzard Minimap with the Carbonite Minimap my other addons (elvui) became incompatible. I do not see an option to rescind or nullify the decision? I would like to use Carbonite for tradeskills and to view unexplored zones but unfortunately without the ability to revert back to the uncombined settings I am unable to.

**Comment by IrcDirk** [comment]
As to ElvUI u need to go to ElvUI options and go to Map -> Minimap settings then disable "enable" checkbox and all will be working again.
