### ISSUE TITLE
New Global Error At Login - Possible Addon Conflict (Spy addon)

### ISSUE THREAD

**Issue by jerj** [IrcDirk/Carbonite-Classic#33]
Date: 2019-09-20 09:32:47
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite\NxMap.lua line 3145:
   attempt to index local 'map' (a nil value)
Debug:
   Carbonite\NxMap.lua:3145:
      Carbonite\NxMap.lua:3131
   [C]: ?
   [C]: Show()
   Spy\Spy.lua:1484:
      Spy\Spy.lua:1483
   [C]: ?
   ...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:65
   ...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:498: InitializeAddon()
   ...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:613:
      ...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:605
Locals:
orgin = true
map = nil
(*temporary) = <table> {
 Menu_OnTrackPlyr = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2843
 GetInstanceID = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:9293
 ZoneOverlays = <table> {
 }
 GetZoneAchievement = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:10936
 MinimapOwnInit = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:1867
 RestoreBlizzBountyMap = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:3215
 MapLevels = <table> {
 }
 MinimapSetScale = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2485
 OnButToggleGuide = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:1633
 MinimapOnMouseDown = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:1983
 SetToCurrentZone = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:9375
 GetIconStatic = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:8406
 UpdateToolBar = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:1255
 Menu_OnBackgndAlphaFade = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2748
 BlizzToggleWorldMap = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:3242
 Menu_OnMapDebugFullCoords = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2794
 ClipFrameByMapType = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:7031
 ZandalarMapBlks = <table> {
 }
 ResetIcons = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:8133
 Minimap_OnEvent = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:1956
 UnpackObjective = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:11184
 GetWorldContinentInfo = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:9679
 ReverseTargets = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:9996
 GetWorldZoneScale = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:9743
 GetIconCnt = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:7851
 CreateToolBar = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:1225
 GetPlayerMapPosition = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:11492
 RestoreWorldMap = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:11222
 DetachWorldMap = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:1468
 ClearTarget = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:9958
 BGMenu_OnHelp = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:3008
 VerifySettings = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:300
 HideMiniFrames = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:6918
 HideExtraZoneTiles = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:6270
 Menu_OnDetailAlpha = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2744
 IsInstanceMap = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:9620
 EkMapBlks = <table> {
 }
 CheckWorldHotspotsType = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:6109
 BuildPlyrLists = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:8545
 SetMapByID = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:229
 Menu_OnScaleRestore = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2708
 Menu_OnBackgndAlphaFull = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2760
 DraeneiXO = -3500
 SetIconTypeAlpha = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:7774
 CreateIconMenu = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:1265
 ScanContinents = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:5205
 MinimapUpdateMask = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2496
 OLMapBlks = <table> {
 }
 Menu_OnPlyrFollow = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2724
 Menu_OnGetQuests = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2834
 IconOnUpdateTooltip = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:8655
 Init = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:140
 UpdatePlyrHistory = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:5688
 NazjatarBlks = <table> {
 }
 Test = <fun
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.1.12
  AtlasLootClassicMaps, vv1.0.0
  AucAdvanced, v8.2.6420 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BadBoy, vv1-classic
  Bagnon, v8.2.13
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  BrokerEverything, v3.5.15-release
  Carbonite, v@project-version@
  CarboniteQuests, v@project-version@
  CarboniteSocial, v@project-version@
  CarboniteWarehouse, v@project-version@
  ClassicCastbars, vv1.0.6
  ClassicCastbarsOptions, v
  DBMCore, v1.13.9
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Dominos, v8.2.28
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  IceHUD, v1.12.4
  Mapster, v1.8.4
  MaxCam, vv2.4.2
  MikScrollingBattleText, v5.7.149
  MobInfo2Classic, v11302.04
  Prat30, v3.7.36
  Prat30Libraries, v
  Questie, v4.1.1 BETA
  Recount, vv1.13.2c
  SexyMap, vv3-classic
  ShadowedUnitFrames, vv4.2-Classic-Beta7
  Spy, v1.0.6
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=51b)

**Comment by IrcDirk** [comment]
Ill check łatwe if we have good version of wow ace3 in carbonite.

**Comment by IrcDirk** [comment]
Spy addon has older Ace3 libraries. U can use our Nx.Social module to dectect enemy players it should be fixed by now :) Closing.

**Comment by IrcDirk** [comment]
Thats not Spy addon thats Bagon!!!
