### ISSUE TITLE
nothing work (???????????????????????)

### ISSUE THREAD

**Issue by Enraiha10** [IrcDirk/Carbonite-Classic#330]
I don't understand any of this, I just know that the carbonite isn't working

this dialog box and the mensage

Message: Interface/AddOns/Carbonite/Carbonite.lua:1925: bad argument #2 to 'min' (number expected, got nil)
Time: Sun Dec 17 20:45:46 2023
Count: 1
Stack: Interface/AddOns/Carbonite/Carbonite.lua:1925: bad argument #2 to 'min' (number expected, got nil)
[string "=[C]"]: in function `min'
[string "@Interface/AddOns/Carbonite/Carbonite.lua"]:1925: in function `PackXY'
[string "@Interface/AddOns/Carbonite/Carbonite.lua"]:2139: in function `AddEvent'
[string "@Interface/AddOns/Carbonite/Carbonite.lua"]:2179: in function `AddInfoEvent'
[string "@Interface/AddOns/Carbonite/Carbonite.lua"]:2509: in function `AddInfo'
[string "@Interface/AddOns/Carbonite/Carbonite.lua"]:1176: in function `?'
[string "@Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: (*temporary) = 100
(*temporary) = nil
(*temporary) = "number expected, got nil"

Message: Interface/AddOns/Carbonite/Carbonite.lua:1925: bad argument #2 to 'min' (number expected, got nil)
Time: Sun Dec 17 20:45:46 2023
Count: 1
Stack: Interface/AddOns/Carbonite/Carbonite.lua:1925: bad argument #2 to 'min' (number expected, got nil)
[string "=[C]"]: in function `min'
[string "@Interface/AddOns/Carbonite/Carbonite.lua"]:1925: in function `PackXY'
[string "@Interface/AddOns/Carbonite/Carbonite.lua"]:2139: in function `AddEvent'
[string "@Interface/AddOns/Carbonite/Carbonite.lua"]:2179: in function `AddInfoEvent'
[string "@Interface/AddOns/Carbonite/Carbonite.lua"]:2509: in function `AddInfo'
[string "@Interface/AddOns/Carbonite/Carbonite.lua"]:1176: in function `?'
[string "@Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: (*temporary) = 100
(*temporary) = nil
(*temporary) = "number expected, got nil"

![Sem título](https://github.com/IrcDirk/Carbonite-Classic/assets/154100495/8e5c89d0-be55-4a48-9ef9-3b19e05b33dc)

**Comment by IrcDirk** [comment]
Which WOW version which Carbonite version?

**Comment by IrcDirk** [comment]
Closing since there's no answer.

**Comment by Enraiha10** [comment]
Last version for wow Classic 3.4.3

**Comment by IrcDirk** [comment]
Disable all other addons try only Carbonite with Modules.
