### ISSUE TITLE
Minimap buttons not being shown in the Carbonite menu - Classic ERA

### ISSUE THREAD

**Issue by Loko89** [IrcDirk/Carbonite-Classic#331]
Carbonite Minimap Icons are missing from the Carbonite menu entirely. 
![WoWScrnShot_123023_105104](https://github.com/IrcDirk/Carbonite-Classic/assets/1134946/cd343135-a518-4072-8a43-83e516547e99)
These icons around the Blizzard minmap should go here 
![WoWScrnShot_020421_234647](https://github.com/IrcDirk/Carbonite-Classic/assets/1134946/7a87dbc6-ed38-4b76-a102-b23a7a6ca822)
but instead the menu look like this
![WoWScrnShot_123023_105145](https://github.com/IrcDirk/Carbonite-Classic/assets/1134946/3f5b9cb4-0df8-423d-95b4-2786acdfb30f)
...Season Of Discovery...

**Comment by IrcDirk** [comment]
Works with no issues on my side in SOD:

![obraz](https://github.com/IrcDirk/Carbonite-Classic/assets/1030023/badc30c5-6d24-4ee3-a4d2-8db4e2e0c653)

Try only with Carbonite + Modules, then enable other mods one by one, maybe its incompatibility with other addon.

If this will not help then try resetting all settings of Carbonite or/and clear them in WTF folder.
