### ISSUE TITLE
How to not display minimap when map is maximized?

### ISSUE THREAD

**Issue by Walayimuna** [IrcDirk/Carbonite-Classic#333]
Went through the options like 5-6 times and still can't find it

**Comment by Walayimuna** [comment]
You know what? the amount of problems this addon has is not worth the tracker on minimap

**Comment by IrcDirk** [comment]
Right click Carbonite map:

![obraz](https://github.com/IrcDirk/Carbonite-Classic/assets/1030023/60b6e6db-d42e-4a51-a8eb-22c7230d8788)

![obraz](https://github.com/IrcDirk/Carbonite-Classic/assets/1030023/15464f25-0fd9-4186-bf4b-bf7be1081bbf)

Lower this value ^^
