### ISSUE TITLE
Carbonite spamming /played every 60 seconds

### ISSUE THREAD

**Issue by ELepianka1** [IrcDirk/Carbonite-Classic#336]
![image](https://github.com/IrcDirk/Carbonite-Classic/assets/58861946/a798a21a-92de-46ca-a52e-8796841e0030)
Wow classic era - using the latest from https://www.curseforge.com/wow/addons/carbonite-classic
i disabled all the privacy ones and many of the quest options as i figured those were broadcasting.

**Comment by IrcDirk** [comment]
I cant reproduce. All fine on my side.

Disable all other addons just leave Carbonite enabled. If that not helps reset all settings or remove them form WTF folder.

**Comment by IrcDirk** [comment]
It might be other addon that triggers those messages. Try disabling one by one.

**Comment by dartworth** [comment]
hmm...seems to be AutoBiographer

https://www.curseforge.com/wow/addons/autobiographer

**Comment by IrcDirk** [comment]
Seems it was not updated for Cataclysm yet, that may be the problem... Dont know really, it triggers some event that it should not and thats why it spams this message.

**Comment by dartworth** [comment]
This is in classic era

**Comment by IrcDirk** [comment]
Still its not Carbonite fault.

**Comment by IrcDirk** [comment]
No problem. 

U can disable this message by commenting one line in the code: https://github.com/IrcDirk/Carbonite-Classic/blob/9e9c7d255bece64e747fd93f17e943da3aa7fd77/Carbonite.Warehouse/NxWarehouse.lua#L1128
