### ISSUE TITLE
Lastest patch problems/errors - WOTLK Classic

### ISSUE THREAD

**Issue by Spydereagle** [IrcDirk/Carbonite-Classic#339]
updated today now every time i put mouse on quest Log it disappears with error:

Date: 2024-02-15 09:08:38
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/Carbonite/NxMap.lua line 10122:
   attempt to index field 'LOpts' (a nil value)
Debug:
   [string "@Interface/AddOns/Carbonite/NxMap.lua"]:10122: ClearTargets()
   [string "@Interface/AddOns/Carbonite/NxMap.lua"]:10060:
      Interface/AddOns/Carbonite/NxMap.lua:10045
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/Carbonite.Quests/NxQuest.lua"]:10484: TrackOnMap()
   [string "@Interface/AddOns/Carbonite.Quests/NxQuest.lua"]:10288: CalcAutoTrack()
   [string "@Interface/AddOns/Carbonite.Quests/NxQuest.lua"]:9164: UpdateList()
   [string "@Interface/AddOns/Carbonite.Quests/NxQuest.lua"]:9077: func()
   [string "@Interface/AddOns/DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua"]:57:
      .../AddOns/DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:50
Locals:
self = <table> {
 Menu_OnTrackPlyr = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2884
 GetInstanceID = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9454
 ZoneOverlays = <table> {
 }
 GetZoneAchievement = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:11183
 MinimapOwnInit = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1883
 RestoreBlizzBountyMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3265
 MapLevels = <table> {
 }
 MinimapSetScale = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2513
 OnButToggleGuide = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1634
 GetWinName = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1234
 SetToCurrentZone = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9536
 GetIconStatic = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:8503
 UpdateToolBar = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1271
 Menu_OnBackgndAlphaFade = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2789
 BlizzToggleWorldMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3292
 Menu_OnMapDebugFullCoords = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2835
 GotoPlayer = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9674
 ResetIcons = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:8230
 Minimap_OnEvent = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1974
 UnpackObjective = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:11431
 GetWorldContinentInfo = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9849
 ReverseTargets = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:10174
 GetWorldZoneScale = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9913
 GMenu_OnPasteLink = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3013
 ContCnt = 4
 CreateToolBar = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1241
 PlyrNamesTipStr = ""
 GetPlayerMapPosition = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:11739
 RestoreWorldMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:11469
 DetachWorldMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1484
 ClearTarget = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:10136
 BGMenu_OnHelp = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3049
 UnregisterAllEvents = <function> defined @Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 VerifySettings = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:323
 HideMiniFrames = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:7015
 HideExtraZoneTiles = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:6367
 Menu_OnDetailAlpha = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2785
 IsInstanceMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9790
 EkMapBlks = <table> {
 }
 CheckWorldHotspotsType = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:6205
 BuildPlyrLists = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:8642
 SetMapByID = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:230
 ScrollScale = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3816
 Menu_OnBackgndAlphaFull = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2801
 DraeneiXO = -3500
 SetIconTypeAlpha = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:7871
 MMMenuIFull = <table> {
 }
 CreateIconMenu = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1281
 ScanContinents = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:5275
 MinimapUpdateMask = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2525
 OLMapBlks = <table> {
 }
 Menu_OnPlyrFollow = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2765
 Menu_OnGetQuests = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2875
 __index = <table> {
 }
 IconOnUpdateTooltip = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:8779
 Init = <function> defined @Interface/AddOns/Carbonite/NxMap.
AddOns:
  MoncaiCompare, v7.2.0
  Swatter, v3.4.6977 (SwimmingSeadragon)
  Altoholic, v3.4.014
  AucAdvanced, v3.4.6952 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6941 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6928 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6913 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6910 (SwimmingSeadragon)
  AucStatSimple, v3.4.6911 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6912 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6914 (SwimmingSeadragon)
  Auctionator, v10.2.24
  AutoCompare, v1.0
  AutoShop, v1.2.2
  BagBrother, v
  Bagnon, v10.2.19
  BagnonMasque, v10
  Bartender4, v4.14.14
  BeanCounter, v3.4.6983 (SwimmingSeadragon)
  BlizzBuffsFacade, v10.0.0
  Carbonite, vv3.4.3-00008
  CarboniteNotes, vv3.4.3-00008
  CarboniteQuests, vv3.4.3-00008
  CarboniteWarehouse, vv3.4.3-00008
  ChatSoundCustomizer, vv2.0.5
  ChatCopyPaste, v1.19
  CooldownCount, v9.0.2
  DataStore, v2023.11.17
  DataStoreAchievements, v2023.12.29
  DataStoreAgenda, v2023.11.17
  DataStoreAuctions, v2023.11.17
  DataStoreCharacters, v2023.12.17
  DataStoreContainers, v2023.11.17
  DataStoreCrafts, v2023.11.26
  DataStoreCurrencies, v2023.11.06
  DataStoreInventory, v2023.11.17
  DataStoreMails, v2023.11.17
  DataStoreQuests, v2023.12.17
  DataStoreReputations, v2023.11.20
  DataStoreSpells, v2023.11.17
  DataStoreTalents, v2023.11.20
  DBMCore, v7a0680c
  DBMFlightTimers, v@project-version@
  DBMStatusBarTimers, v7a0680c
  DBMVPVEM, v9705bdd
  DetailedDurability, v2.6
  Details, v#Details.20240213.12307.155
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v3.4.6979 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6917 (SwimmingSeadragon)
  GatherMate2, v1.47.2-classic
  GSE, v3.1.54
  GSELDB, v3.1.54
  HealBot, v3.4.3.20
  HealBotData, v
  HealBotOptions, v
  HealBotTips, v
  Informant, v3.4.6980 (SwimmingSeadragon)
  Masque, v10.2.5
  MasqueCirque, v10.2.5
  MasqueDominos, v10.2.5
  MasqueGears, v10.2.5
  MasqueSquat, v1.12.1
  Pawn, v2.8.9
  Poisoner, v3.4.2.1-wotlk
  Postal, vv4.1.1
  Questie, v9.4.1
  RandomMount, v0.0.15
  RareScanner, v3.4.3.4
  Scrap, v10.2.7
  SexyMap, vv10.2.5
  SlideBar, v3.4.6919 (SwimmingSeadragon)
  StatPriorityTracker, v0.1.9-WOTLKC
  Stubby, v3.4.6920 (SwimmingSeadragon)
  SunnArt, v3.91
  SunnArtLauncher, v1.20
  SunnArtPack1, v1.34
  SunnArtPack2, v1.34
  SunnArtPack3, v1.33
  SunnArtPack4, v1.3
  SunnArtPack5, v1.29
  SunnArtPack6, v1.29
  SunnArtPack9, v1.29
  TacoTip, v0.4.3
  Talented, vv221207
  TalentedSpecTabs, v
  TitanClassic, v1.5.11.30403
  TitanClassicClock, v1.5.11.30403
  TitanClassicLocation, v1.5.11.30403
  TitanClassicLootType, v1.5.11.30403
  TitanClassicPerformance, v1.5.11.30403
  TitanClassicRegen, v1.5.11.30403
  TitanClassicXP, v1.5.11.30403
  TomTom, vv3.5.5-release
  WeakAuras, v5.10.1
  WeakAurasArchive, v5.10.1
  ZPerl, v7.2.2
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlTarget, v
  BlizRuntimeLib v3.4.3.52237(US) <enUS>
  (ck=c04)

**Comment by Panerdar** [comment]
Everything worked fine yesterday. Today, me and friend get:

2x Carbonite/NxMap.lua:10122: attempt to index field 'LOpts' (a nil value)
[string "@Carbonite/NxMap.lua"]:10122: in function `ClearTargets'
[string "@Carbonite/NxMap.lua"]:10060: in function <Carbonite/NxMap.lua:10045>
[string "=(tail call)"]: ?
[string "@Carbonite.Quests/NxQuest.lua"]:10484: in function `TrackOnMap'
[string "@Carbonite.Quests/NxQuest.lua"]:10026: in function `Set'
[string "@Carbonite.Quests/NxQuest.lua"]:9919: in function `UserFunc'
[string "@Carbonite/NxUI.lua"]:6542: in function `UserFunc'
[string "@Carbonite/NxUI.lua"]:3706: in function <Carbonite/NxUI.lua:3688>

Locals:
self = <table> {
 Menu_OnTrackPlyr = <function> defined @Carbonite/NxMap.lua:2884
 GetInstanceID = <function> defined @Carbonite/NxMap.lua:9454
 ZoneOverlays = <table> {
 }
 GetZoneAchievement = <function> defined @Carbonite/NxMap.lua:11183
 MinimapOwnInit = <function> defined @Carbonite/NxMap.lua:1883
 RestoreBlizzBountyMap = <function> defined @Carbonite/NxMap.lua:3265
 MapLevels = <table> {
 }
 MinimapSetScale = <function> defined @Carbonite/NxMap.lua:2513
 OnButToggleGuide = <function> defined @Carbonite/NxMap.lua:1634
 GetWinName = <function> defined @Carbonite/NxMap.lua:1234
 SetToCurrentZone = <function> defined @Carbonite/NxMap.lua:9536
 GetIconStatic = <function> defined @Carbonite/NxMap.lua:8503
 UpdateToolBar = <function> defined @Carbonite/NxMap.lua:1271
 Menu_OnBackgndAlphaFade = <function> defined @Carbonite/NxMap.lua:2789
 BlizzToggleWorldMap = <function> defined @Carbonite/NxMap.lua:3292
 Menu_OnMapDebugFullCoords = <function> defined @Carbonite/NxMap.lua:2835
 GotoPlayer = <function> defined @Carbonite/NxMap.lua:9674
 ResetIcons = <function> defined @Carbonite/NxMap.lua:8230
 Minimap_OnEvent = <function> defined @Carbonite/NxMap.lua:1974
 UnpackObjective = <function> defined @Carbonite/NxMap.lua:11431
 GetWorldContinentInfo = <function> defined @Carbonite/NxMap.lua:9849
 ReverseTargets = <function> defined @Carbonite/NxMap.lua:10174
 GetWorldZoneScale = <function> defined @Carbonite/NxMap.lua:9913
 GMenu_OnPasteLink = <function> defined @Carbonite/NxMap.lua:3013
 ContCnt = 4
 CreateToolBar = <function> defined @Carbonite/NxMap.lua:1241
 PlyrNamesTipStr = ""
 GetPlayerMapPosition = <function> defined @Carbonite/NxMap.lua:11739
 RestoreWorldMap = <function> defined @Carbonite/NxMap.lua:11469
 DetachWorldMap = <function> defined @Carbonite/NxMap.lua:1484
 ClearTarget = <function> defined @Carbonite/NxMap.lua:10136
 BGMenu_OnHelp = <function> defined @Carbonite/NxMap.lua:3049
 UnregisterAllEvents = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 VerifySettings = <function> defined @Carbonite/NxMap.lua:323
 HideMiniFrames = <function> defined @Carbonite/NxMap.lua:7015
 HideExtraZoneTiles = <function> defined @Carbonite/NxMap.lua:6367
 Menu_OnDetailAlpha = <function> defined @Carbonite/NxMap.lua:2785
 IsInstanceMap = <function> defined @Carbonite/NxMap.lua:9790
 EkMapBlks = <table> {
 }
 CheckWorldHotspotsType = <function> defined @Carbonite/NxMap.lua:6205
 BuildPlyrLists = <function> defined @Carbonite/NxMap.lua:8642
 SetMapByID = <function> defined @Carbonite/NxMap.lua:230
 ScrollScale = <function> defined @Carbonite/NxMap.lua:3816
 Menu_OnBackgndAlphaFull = <function> defined @Carbonite/NxMap.lua:2801
 DraeneiXO = -3500
 SetIconTypeAlpha = <function> defined @Carbonite/NxMap.lua:7871
 MMMenuIFull = <table> {
 }
 CreateIconMenu = <function> defined @Carbonite/NxMap.lua:1281
 ScanContinents = <function> defined @Carbonite/NxMap.lua:5275
 MinimapUpdateMask = <function> defined @Carbonite/NxMap.lua:2525
 OLMapBlks = <table> {
 }
 Menu_OnPlyrFollow = <function> defined @Carbonite/NxMap.lua:2765
 Menu_OnGetQuests = <function> defined @Carbonite/NxMap.lua:2875
 __index = <table> {
 }
 IconOnUpdateTooltip = <function> defined @Carbonite/NxMap.lua:8779
 Init = <function> defined @Carbonite/NxMap.lua:140

**Comment by IrcDirk** [comment]
Ill look into it in spare time. For now just use previous version.

**Comment by IrcDirk** [comment]
Just made commit. Please download version from this Repository and check if the error is fixed. Please report back.

**Comment by Panerdar** [comment]
Just tested it, seems to be working for me. Not getting any error when I try and select a quest to go to now.

**Comment by Spydereagle** [comment]
stilll getting same errors

Date: 2024-02-15 23:20:16
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/Carbonite/NxMap.lua line 10122:
   attempt to index field 'LOpts' (a nil value)
Debug:
   [string "@Interface/AddOns/Carbonite/NxMap.lua"]:10122: ClearTargets()
   [string "@Interface/AddOns/Carbonite/NxMap.lua"]:10060:
      Interface/AddOns/Carbonite/NxMap.lua:10045
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/Carbonite.Quests/NxQuest.lua"]:10484: TrackOnMap()
   [string "@Interface/AddOns/Carbonite.Quests/NxQuest.lua"]:10288: CalcAutoTrack()
   [string "@Interface/AddOns/Carbonite.Quests/NxQuest.lua"]:9164: UpdateList()
   [string "@Interface/AddOns/Carbonite.Quests/NxQuest.lua"]:9077: func()
   [string "@Interface/AddOns/DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua"]:57:
      .../AddOns/DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:50
Locals:
self = <table> {
 Menu_OnTrackPlyr = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2884
 GetInstanceID = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9454
 ZoneOverlays = <table> {
 }
 GetZoneAchievement = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:11183
 MinimapOwnInit = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1883
 RestoreBlizzBountyMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3265
 MapLevels = <table> {
 }
 MinimapSetScale = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2513
 OnButToggleGuide = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1634
 GetWinName = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1234
 SetToCurrentZone = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9536
 GetIconStatic = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:8503
 UpdateToolBar = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1271
 Menu_OnBackgndAlphaFade = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2789
 BlizzToggleWorldMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3292
 Menu_OnMapDebugFullCoords = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2835
 GotoPlayer = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9674
 ResetIcons = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:8230
 Minimap_OnEvent = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1974
 UnpackObjective = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:11431
 GetWorldContinentInfo = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9849
 ReverseTargets = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:10174
 GetWorldZoneScale = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9913
 GMenu_OnPasteLink = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3013
 ContCnt = 4
 CreateToolBar = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1241
 PlyrNamesTipStr = ""
 GetPlayerMapPosition = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:11739
 RestoreWorldMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:11469
 DetachWorldMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1484
 ClearTarget = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:10136
 BGMenu_OnHelp = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3049
 UnregisterAllEvents = <function> defined @Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 VerifySettings = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:323
 HideMiniFrames = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:7015
 HideExtraZoneTiles = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:6367
 Menu_OnDetailAlpha = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2785
 IsInstanceMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9790
 EkMapBlks = <table> {
 }
 CheckWorldHotspotsType = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:6205
 BuildPlyrLists = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:8642
 SetMapByID = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:230
 ScrollScale = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3816
 Menu_OnBackgndAlphaFull = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2801
 DraeneiXO = -3500
 SetIconTypeAlpha = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:7871
 MMMenuIFull = <table> {
 }
 CreateIconMenu = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1281
 ScanContinents = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:5275
 MinimapUpdateMask = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2525
 OLMapBlks = <table> {
 }
 Menu_OnPlyrFollow = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2765
 Menu_OnGetQuests = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2875
 __index = <table> {
 }
 IconOnUpdateTooltip = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:8779
 Init = <function> defined @Interface/AddOns/Carbonite/NxMap.

**Comment by IrcDirk** [comment]
Did u used version from this repository?

pt., 16 lut 2024, 05:25 użytkownik Spydereagle ***@***.***>
napisał:

**Comment by Spydereagle** [comment]
working with 3.4.3-00009.zip ty
