### ISSUE TITLE
Crash to desktop when asking a guard for directions.

### ISSUE THREAD

**Issue by mwd637** [IrcDirk/Carbonite-Classic#34]
Problem repeated several time with multiple guards in  Orgrimar.

**Comment by IrcDirk** [comment]
For me WoW crashes with the same guards in Orgrimmar even with Carbonite disabled... so its Blizz bug!

**Comment by IrcDirk** [comment]
Nope something weird is happening need to investigate more...

**Comment by kenhwong** [comment]
Test a guard in stormwind, client alive. 
but the flag of answer location is not shown on minimap.
