### ISSUE TITLE
Carbonite Map Issues for SOD (1.15.2)

### ISSUE THREAD

**Issue by Hordehero** [IrcDirk/Carbonite-Classic#342]
Title says it all, basically after the new patch today (now game is at 1.15.2) it seems that carbonite is "out of date" and I can't seem to get any function out of it again.  Similar to SOD release prior to your fix, can't open the carbonite map or built in game map with carbonite turned on, cant open any of the carbonite settings in game either.  tried to clear and fresh install already with no such luck.

**Comment by IrcDirk** [comment]
Fixed.

**Comment by Hordehero** [comment]
Confirmed fixed!  Thanks bud! <3
