### ISSUE TITLE
Carbonite broken with latest Classic HC release

### ISSUE THREAD

**Issue by noahgithub** [IrcDirk/Carbonite-Classic#346]
Maps no longer work, tracker no longer comes up, just busted. Please fix!

**Comment by IrcDirk** [comment]
Working without problems... What version u are using? Update it from Curse.

**Comment by noahgithub** [comment]
Is there a new version? I was using the same release you fixed last time. Will check if there’s a new version on curse.

**Comment by IrcDirk** [comment]
This works for me without any problems => https://www.curseforge.com/wow/addons/carbonite-classic/files/5232038 

Maybe other addon is a problem not Carbonite ;)

**Comment by noahgithub** [comment]
Will check this tomorrow. I have been using the same set of add-ons for months now with no issues.  It just stopped working when the HC client was upgraded. No other changes. It broke on 2 different machines that same way so it’s odd if you did not have the same result.  Hopefully your suggestion fixes it that easily.

**Comment by IrcDirk** [comment]
This version works fine on my HC.

**Comment by noahgithub** [comment]
Thank you, that was indeed the fix.
