### ISSUE TITLE
Carbonite broken with Cataclsym Classic pre-patch launch

### ISSUE THREAD

**Issue by aSnejbjerg** [IrcDirk/Carbonite-Classic#347]
As title, Carbonite is no longer working after the pre-patch launched.

**Comment by IrcDirk** [comment]
I know i need to wait a bit for the update.

**Comment by IrcDirk** [comment]
First Cata release available: https://github.com/IrcDirk/Carbonite-Classic/releases/latest

Keep in mind its still WIP, please report any problems.

**Comment by aSnejbjerg** [comment]
It doesn't work:
`Date: 2024-05-01 12:34:50
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/Carbonite/NxMap.lua line 268:
   attempt to index local 'mapInfo' (a nil value)
Debug:
   [string "@Interface/AddOns/Carbonite/NxMap.lua"]:268: GetMapInfo()
   [string "@Interface/AddOns/Carbonite/NxMap.lua"]:11714: GetMapNameByID()
   [string "@Interface/AddOns/Carbonite/NxMap.lua"]:9755: IdToName()
   [string "@Interface/AddOns/Carbonite/NxMapGuide.lua"]:2045: UpdateVisitedVendors()
   [string "@Interface/AddOns/Carbonite/NxMapGuide.lua"]:474: Create()
   [string "@Interface/AddOns/Carbonite/NxMap.lua"]:1201: Create()
   [string "@Interface/AddOns/Carbonite/NxMap.lua"]:317: Open()
   [string "@Interface/AddOns/Carbonite/Carbonite.lua"]:823: SetupEverything()
   [string "@Interface/AddOns/Carbonite/Carbonite.lua"]:1282: NXOnUpdate()
   [string "*Carbonite.xml:16_OnUpdate"]:1:
      [string "*Carbonite.xml:16_OnUpdate"]:1
Locals:
self = <table> {
 Menu_OnTrackPlyr = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2889
 GetInstanceID = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9457
 ZoneOverlays = <table> {
 }
 GetZoneAchievement = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:11186
 MinimapOwnInit = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1888
 RestoreBlizzBountyMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3270
 MapLevels = <table> {
 }
 MinimapSetScale = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2518
 OnButToggleGuide = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1634
 GetWinName = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1234
 SetToCurrentZone = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9539
 GetIconStatic = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:8508
 UpdateToolBar = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1271
 Menu_OnBackgndAlphaFade = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2794
 BlizzToggleWorldMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3297
 Menu_OnMapDebugFullCoords = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2840
 GotoPlayer = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9677
 ResetIcons = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:8235
 Minimap_OnEvent = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1979
 UnpackObjective = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:11434
 GetWorldContinentInfo = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9852
 ReverseTargets = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:10177
 GetWorldZoneScale = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9916
 GMenu_OnPasteLink = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3018
 ContCnt = 5
 CreateToolBar = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1241
 PlyrNamesTipStr = ""
 GetPlayerMapPosition = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:11742
 RestoreWorldMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:11472
 DetachWorldMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1484
 ClearTarget = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:10139
 BGMenu_OnHelp = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3054
 UnregisterAllEvents = <function> defined @Interface/AddOns/AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 VerifySettings = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:323
 HideMiniFrames = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:7020
 HideExtraZoneTiles = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:6372
 Menu_OnDetailAlpha = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2790
 IsInstanceMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9793
 EkMapBlks = <table> {
 }
 CheckWorldHotspotsType = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:6210
 BuildPlyrLists = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:8647
 SetMapByID = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:230
 ScrollScale = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3821
 Menu_OnBackgndAlphaFull = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2806
 DraeneiXO = -3500
 SetIconTypeAlpha = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:7876
 MMMenuIFull = <table> {
 }
 CreateIconMenu = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1281
 KezanMapBlks = <table> {
 }
 MinimapUpdateMask = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2530
 OLMapBlks = <table> {
 }
 Menu_OnPlyrFollow = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2770
 DrawTracking = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:5971
 __index = <table> {
 }
 IconOnUpdateTooltip = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:8784
 Init = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:140
 UpdatePlyrHistory = <function> defined @Interfac
AddOns:
  Carbonite, vv4.4.0-00001
  CarboniteQuests, vv4.4.0-00001
  CarboniteWarehouse, vv4.4.0-00001
  BlizRuntimeLib v4.4.0.54481(EU) <enUS>
  (ck=57e)

`

**Comment by IrcDirk** [comment]
What Zone are you in?

**Comment by IrcDirk** [comment]
You are in Kezan... Download this version and try again, just added few missing zones: https://github.com/IrcDirk/Carbonite-Classic/archive/refs/heads/master.zip

**Comment by aSnejbjerg** [comment]
I was in Stormwind bank :)
Downloaded, installed, bug:
Date: 2024-05-01 12:51:12
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/Carbonite/NxMap.lua line 268:
   attempt to index local 'mapInfo' (a nil value)
Debug:
   [string "@Interface/AddOns/Carbonite/NxMap.lua"]:268: GetMapInfo()
   [string "@Interface/AddOns/Carbonite/NxMap.lua"]:11714: GetMapNameByID()
   [string "@Interface/AddOns/Carbonite/NxMap.lua"]:9755: IdToName()
   [string "@Interface/AddOns/Carbonite/NxMapGuide.lua"]:2045: UpdateVisitedVendors()
   [string "@Interface/AddOns/Carbonite/NxMapGuide.lua"]:474: Create()
   [string "@Interface/AddOns/Carbonite/NxMap.lua"]:1201: Create()
   [string "@Interface/AddOns/Carbonite/NxMap.lua"]:317: Open()
   [string "@Interface/AddOns/Carbonite/Carbonite.lua"]:823: SetupEverything()
   [string "@Interface/AddOns/Carbonite/Carbonite.lua"]:1282: NXOnUpdate()
   [string "*Carbonite.xml:16_OnUpdate"]:1:
      [string "*Carbonite.xml:16_OnUpdate"]:1
Locals:
self = <table> {
 Menu_OnTrackPlyr = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2889
 GetInstanceID = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9457
 ZoneOverlays = <table> {
 }
 GetZoneAchievement = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:11186
 MinimapOwnInit = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1888
 RestoreBlizzBountyMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3270
 MapLevels = <table> {
 }
 MinimapSetScale = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2518
 OnButToggleGuide = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1634
 GetWinName = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1234
 SetToCurrentZone = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9539
 GetIconStatic = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:8508
 UpdateToolBar = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1271
 Menu_OnBackgndAlphaFade = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2794
 BlizzToggleWorldMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3297
 Menu_OnMapDebugFullCoords = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2840
 GotoPlayer = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9677
 ResetIcons = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:8235
 Minimap_OnEvent = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1979
 UnpackObjective = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:11434
 GetWorldContinentInfo = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9852
 ReverseTargets = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:10177
 GetWorldZoneScale = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9916
 GMenu_OnPasteLink = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3018
 ContCnt = 5
 CreateToolBar = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1241
 PlyrNamesTipStr = ""
 GetPlayerMapPosition = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:11742
 RestoreWorldMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:11472
 DetachWorldMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1484
 ClearTarget = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:10139
 BGMenu_OnHelp = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3054
 VerifySettings = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:323
 HideMiniFrames = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:7020
 HideExtraZoneTiles = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:6372
 Menu_OnDetailAlpha = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2790
 IsInstanceMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9793
 EkMapBlks = <table> {
 }
 CheckWorldHotspotsType = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:6210
 BuildPlyrLists = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:8647
 SetMapByID = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:230
 ScrollScale = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3821
 Menu_OnBackgndAlphaFull = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2806
 DraeneiXO = -3500
 SetIconTypeAlpha = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:7876
 MMMenuIFull = <table> {
 }
 CreateIconMenu = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1281
 KezanMapBlks = <table> {
 }
 MinimapUpdateMask = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2530
 OLMapBlks = <table> {
 }
 Menu_OnPlyrFollow = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2770
 DrawTracking = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:5971
 __index = <table> {
 }
 IconOnUpdateTooltip = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:8784
 Init = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:140
 UpdatePlyrHistory = <function> defined @Interfac

**Comment by aSnejbjerg** [comment]
I'm not sure why you marked this as completed? :D
As shown in my comment above, I'm still experiencing issues

**Comment by aSnejbjerg** [comment]
For good measure, here's another log: 

Message: Interface/AddOns/Carbonite/NxMap.lua:268: attempt to index local 'mapInfo' (a nil value)
Time: Sat May  4 09:06:19 2024
Count: 1
Stack: Interface/AddOns/Carbonite/NxMap.lua:268: attempt to index local 'mapInfo' (a nil value)
[string "@Interface/AddOns/Carbonite/NxMap.lua"]:268: in function `GetMapInfo'
[string "@Interface/AddOns/Carbonite/NxMap.lua"]:11750: in function `GetMapNameByID'
[string "@Interface/AddOns/Carbonite/NxMap.lua"]:9791: in function `IdToName'
[string "@Interface/AddOns/Carbonite/NxMapGuide.lua"]:2045: in function `UpdateVisitedVendors'
[string "@Interface/AddOns/Carbonite/NxMapGuide.lua"]:474: in function `Create'
[string "@Interface/AddOns/Carbonite/NxMap.lua"]:1222: in function `Create'
[string "@Interface/AddOns/Carbonite/NxMap.lua"]:317: in function `Open'
[string "@Interface/AddOns/Carbonite/Carbonite.lua"]:823: in function `SetupEverything'
[string "@Interface/AddOns/Carbonite/Carbonite.lua"]:1282: in function `NXOnUpdate'
[string "*Carbonite.xml:16_OnUpdate"]:1: in function <[string "*Carbonite.xml:16_OnUpdate"]:1>

Locals: self = <table> {
 Menu_OnTrackPlyr = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2925
 GetInstanceID = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9493
 ZoneOverlays = <table> {
 }
 GetZoneAchievement = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:11222
 MinimapOwnInit = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1924
 RestoreBlizzBountyMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3306
 MapLevels = <table> {
 }
 MinimapSetScale = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2554
 OnButToggleGuide = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1670
 GetWinName = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1255
 SetToCurrentZone = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9575
 GetIconStatic = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:8544
 UpdateToolBar = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1292
 Menu_OnBackgndAlphaFade = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2830
 BlizzToggleWorldMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3333
 Menu_OnMapDebugFullCoords = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2876
 GotoPlayer = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9713
 ResetIcons = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:8271
 Minimap_OnEvent = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2015
 UnpackObjective = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:11470
 GetWorldContinentInfo = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9888
 ReverseTargets = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:10213
 GetWorldZoneScale = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:9952
 GMenu_OnPasteLink = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3054
 ContCnt = 5
 CreateToolBar = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1262
 PlyrNamesTipStr = ""
 GetPlayerMapPosition = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:11778
 RestoreWorldMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:11508
 DetachWorldMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:1505
 ClearTarget = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:10175
 BGMenu_OnHelp = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:3090
 UnregisterAllEvents = <function> defined @Interface/AddOns/Carbonite/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 VerifySettings = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:323
 HideMiniFrames = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:7056
 HideExtraZoneTiles = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:6408
 Menu_OnDetailAlpha = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:2826
 IsInstanceMap = <function> defined @Interface/AddOns/Carbonite/NxMap.lua:98

**Comment by IrcDirk** [comment]
No one else reports this issue.

U are using official Cata release not on private server? What version of Carbonite are u using? Where are u (Zone) when this happens?

**Comment by aSnejbjerg** [comment]
I'm using the latest version of Carbonite on official servers.
It happened no matter where I was.

I have fixed it myself though. After I spend some time trying to debug what was going on I found out it had something to do with the saved variables, so I went and deletes Carbonite.lua in WTF/Account/[AccountName]/SavedVariables
After I deleted that it worked again. Thank you for your work though :)

**Comment by IrcDirk** [comment]
Great to hear that this solved the issue. I will remember that if someone
else will have problem with starting Carb on Cata.

niedz., 5 maj 2024, 07:33 użytkownik aSnejbjerg ***@***.***>
napisał:
