### ISSUE TITLE
Crash to desktop.

### ISSUE THREAD

**Issue by wtfaatp** [IrcDirk/Carbonite-Classic#35]
Getting a memory error when playing with carbonite enabled. As soon as I get into game I get a memory instruction error. I have three PC's in the house playing wow with mod and it is happening on 2 of them.. All using same mods.. So it's a little weird for me..

![crash](https://user-images.githubusercontent.com/7692617/65368190-cf2b8e80-dc0b-11e9-9cc7-c6bff1ebf839.png)

**Comment by IrcDirk** [comment]
Disable all addon just leave Carbonite + Modules enabled and check again it might be incompatibility with other addon.

**Comment by wtfaatp** [comment]
i did still happened

**Comment by IrcDirk** [comment]
Need to investigate more... Something is wrong.

**Comment by IrcDirk** [comment]
Please check now.

**Comment by wtfaatp** [comment]
Hasn't happened again so far. I will now update all other PC's in my house and will continue to test thank you!
