### ISSUE TITLE
Quest locations are not where they really are.

### ISSUE THREAD

**Issue by Bowiee17** [IrcDirk/Carbonite-Classic#350]
Quest locations are off, probably it shows the locations for some quests where it was before the shattering. I attached a screenshot of what i mean exactly.

![WoWScrnShot_050124_191738](https://github.com/IrcDirk/Carbonite-Classic/assets/93541870/12f72de3-586b-4df2-81fc-36ee7b12d772)

**Comment by IrcDirk** [comment]
First Quest Database update pushed. Please check and let me know.

**Comment by Bowiee17** [comment]
It seems to be good now.
