### ISSUE TITLE
Was working fine in Cata Classic Pre Patch right up until the update via Curseforge

### ISSUE THREAD

**Issue by tankspank** [IrcDirk/Carbonite-Classic#353]
As the title implies, was working beautifully without any updates at all for the last day or so with pre patch.  Updated it less than an hour ago, now it's broken.  Any links to the previous update while we all wait for the fix here??

**Comment by tankspank** [comment]
here's some swatter details, let me know if you need all the locals...I can't imagine you would though...

Date: 2024-05-01 20:37:11
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/Carbonite/NxMap.lua line 1954:
   attempt to call method 'SetQuestBlobRingAlpha' (a nil value)
Debug:
   [string "@Interface/AddOns/Carbonite/NxMap.lua"]:1954: ?()
   [string "@Interface/AddOns/Carbonite/NxMap.lua"]:1229: Create()
   [string "@Interface/AddOns/Carbonite/NxMap.lua"]:317: Open()
   [string "@Interface/AddOns/Carbonite/Carbonite.lua"]:823: SetupEverything()
   [string "@Interface/AddOns/Carbonite/Carbonite.lua"]:1282: NXOnUpdate()
   [string "*Carbonite.xml:16_OnUpdate"]:1:
      [string "*Carbonite.xml:16_OnUpdate"]:1

**Comment by IrcDirk** [comment]
Previous release is available here in releases or on Curse.

**Comment by IrcDirk** [comment]
Fixed.
