### ISSUE TITLE
The map should always show city maps

### ISSUE THREAD

**Issue by mixels** [IrcDirk/Carbonite-Classic#355]
Hi! Thank you for porting this mod to Classic. It's truly wonderful.

One aspect about the map that is hard to work with is that city maps are not visible unless you mouse over them. However, on the world map, there are big sections of empty space which the city maps seem to fit pretty well into. I don't see a reason to auto hide city maps when you mouse over a different part of the map.

Would you please consider either disabling this auto hide city maps feature or, alternatively, adding a configuring option to allow players to disable it?

Thank you!

**Comment by IrcDirk** [comment]
That how its is for years in Carbonite. I will not change that, also i dont have time to implement it as an option.
