### ISSUE TITLE
Kindly please consider adding dungeon entrance icons to mark dungeon entrances

### ISSUE THREAD

**Issue by mixels** [IrcDirk/Carbonite-Classic#357]
Especially in Season of Discovery, the lack of a Dungeon Finder or Summoning Stones means players have to actually run to dungeon entrances. For this reason it would be very nice if Carbonite could show dungeon entrances via icons on the map.

Bonus points if clicking the dungeon entrance icon would show an overlay of the actual dungeon interior map.

Thank you!

**Comment by IrcDirk** [comment]
U mean SOD/HC Classic?
