### ISSUE TITLE
Gathermate2 Module missing

### ISSUE THREAD

**Issue by CodeGuro** [IrcDirk/Carbonite-Classic#36]
The Carbonite.Gathermate2_data module is missing. Please see the below link.
![image](https://user-images.githubusercontent.com/2359168/65378810-f033c400-dc8b-11e9-9397-b5e2a8ef4ab0.png)

Steps to reproduce:
From the Interface menu, click "Import mines from GatherMate2_Data".
![image](https://user-images.githubusercontent.com/2359168/65378827-38eb7d00-dc8c-11e9-971b-523859821e47.png)

I highly recommend using Spinx's distrobution of gathermate2_data because this has all of the nodes in classic. The zones that were torn apart with the release of Cataclysm (v4) were then re-organised in BfA (v8). Classic was released subsequently with old maps but new attributes meaning that neither the retail nor the old Classic data points for gathering were correct.

**Comment by CodeGuro** [comment]
Sphinx's distrobution: https://www.curseforge.com/wow/addons/spinx-gathermate2-data-classic

**Comment by IrcDirk** [comment]
Yes i know this data is missing. This is work in progress. Just wait a bit more.

**Comment by IrcDirk** [comment]
Added Carbonite.Gathermate2_Data with gather data for Classic (Mining and Herbalism not from Sphinx) should be accurate.

**Comment by CodeGuro** [comment]
Well done. You have to right-click the map and select "Show Mining Locations".
I did not test the herbs but I assume they as well. I also double-checked to see if the gathermate2_data between sphinx's and your editions match up and they seem to.
Attaching results and closing issue.
![image](https://user-images.githubusercontent.com/2359168/65399590-83075800-dd8b-11e9-8752-9cf74c5dc864.png)

**Comment by IrcDirk** [comment]
Some of Sphinx nodes were of the overlays so this looked weird on Carbonite. Good that i have some older data archived ;)
