### ISSUE TITLE
Maps and Questwatch

### ISSUE THREAD

**Issue by KimmyT66** [IrcDirk/Carbonite-Classic#364]
The latest version 4.0.00 seems to be broken. There are no maps in the folder. No many how many times I delete and reinstall there are no map files at all. Searched my entire computer files in case it unzipped it into the wrong location but there is nothing. Also, the questwatch is not showing on my screen at all, maybe it is linked with maps? Please fix, this is the only addon I use for questing.

**Comment by IrcDirk** [comment]
No one reports problems. There is no 4.0.00 version. Whats your source of Carbonite?

**Comment by KimmyT66** [comment]
Sorry, I put in the wrong version. It is 4.4.0 from Curseforge

**Comment by IrcDirk** [comment]
???
