### ISSUE TITLE
Carbonite not working in WoW Cata Classic

### ISSUE THREAD

**Issue by thelitsune** [IrcDirk/Carbonite-Classic#365]
Titler says it all. addon is installed. nothing works. Please help thanks!

**Comment by IrcDirk** [comment]
Works fine without any issues on Cata. What other addons do u use? Try with only Carbonite + Modules enabled. Are there any errors?

**Comment by thelitsune** [comment]
My source for carbonite is curseforge. Uninstalled and did fresh install. I use quite a few other addons I don’t have the whole list on hand at the moment. Also I have not checked for errors but what I do know is carbonite doesn’t load at all. Like when I hit escape, go to main settings where you can edit your wow settings themselves and click the add on tab it doesn’t show.

**Comment by thelitsune** [comment]
Carbonite map doesn’t show. Quest log. Etc.

**Comment by IrcDirk** [comment]
Did u install it trough Curse client or "by the hand"?

**Comment by IrcDirk** [comment]
???
