### ISSUE TITLE
[Cata Classic] Carbonite not displaying Quest Givers/Handy Notes/Nodes/NPCs

### ISSUE THREAD

**Issue by L3ps0n** [IrcDirk/Carbonite-Classic#366]
Hello,

Everything seems to work fine form my friend playing in the same server/zone (he is able to see the quest givers for example), beside that and some small issues with tracking hud Carbonite is working fine (thanks for great work).

I tried to disable all addons and load only Carbonite and also to reinstall Carbonite and WoW istelf (I'm desperate 🦺 ).
Do you have any idea how to approach to that issue?

![image](https://github.com/IrcDirk/Carbonite-Classic/assets/170576923/837d6b0b-2bad-45ef-b762-dcf4a731c029)

I currently completed all the quest whlie taking SS, but watches seems to be set up correctly.
![image](https://github.com/IrcDirk/Carbonite-Classic/assets/170576923/c0c1e359-31ad-4c99-95b2-5dc1a8940105)

**Comment by IrcDirk** [comment]
Try removing all Carbonite settings from WTF folder. This should reset it to defaults.

**Comment by IrcDirk** [comment]
As to nodes u need to import them.

**Comment by IrcDirk** [comment]
As to quest givers maybe no more quest in the zone or carbonite database doesnt have more.

**Comment by IrcDirk** [comment]
??

**Comment by IrcDirk** [comment]
Or as simply it sounds just zoom in to show them ;)

**Comment by Mugafo** [comment]
L3ps0n doesn't seem to have the show herb/mining checked, but Cata nodes do seem to be missing. 
https://github.com/IrcDirk/Carbonite-Classic/blob/master/Carbonite/NxOptions.lua#L3422 I moved this comment down to line 3501 to before the `ghost` ore to get the options back, then I also had to add the missing ores to this object to get them back on the map https://github.com/IrcDirk/Carbonite-Classic/blob/master/Carbonite/Carbonite.lua#L2860-L2888
also updated the gathermate data files with what's available from that addon and then imported those.

haven't done herbalism yet, but looks like the same problem

**Comment by IrcDirk** [comment]
Ohh... Cata nodes not there yet... ill be updating that in days.

**Comment by L3ps0n** [comment]
Sorry for the late response. 

All functionality was tested when I had herbalism. I would not raise this topic but I saw all these functions visible on my firend's pc on the same server, so I assume the problem lies on my side.

I know how to zoom in xD. I can make a video explaining all this if you want.

**Comment by IrcDirk** [comment]
Video would help a lot to understand your problem :)

**Comment by L3ps0n** [comment]
Hey,

I deleted WTF folder, disabled Plater addon and everything works. Strange things, sorry that i took your time.

Dzięki wielkie za prowadzenie tak wspaniałego addona.

**Comment by IrcDirk** [comment]
Good to hear that it works now :) No worries. Have a great day/night.
