### ISSUE TITLE
Quest announce keep silent in party

### ISSUE THREAD

**Issue by kenhwong** [IrcDirk/Carbonite-Classic#38]
Announce option checked, but none happens in all time.
On some scene(i.e. a party member shared a quest), my completed quest announced. confusing trigger..)

**Comment by Rhendak** [comment]
Can confirm the same, would love for this feature to work.

**Comment by Rhendak** [comment]
Can confirm that this is fixed. Working correctly now.

**Comment by kenhwong** [comment]
confirm fixed.
