### ISSUE TITLE
SOD/Era - attempt to call GetMouseFocus (a nil value)

### ISSUE THREAD

**Issue by Farsyte** [IrcDirk/Carbonite-Classic#385]
Observed on Classic servers, including Seasonal servers.

This does not happen on Cataclysm servers (smells like the classic servers got an update
that makes them look like Cata servers, but I've not peeked at the version checking bits
in the addon's code, much less instrumented them).

The count rises rapidly if my mouse is over the map.

```
Message: Interface/AddOns/Carbonite/NxUI.lua:3149: attempt to call global 'GetMouseFocus' (a nil value)
Time: Mon Sep 30 19:54:33 2024
Count: 78
Stack: Interface/AddOns/Carbonite/NxUI.lua:3149: attempt to call global 'GetMouseFocus' (a nil value)
[string "@Interface/AddOns/Carbonite/NxUI.lua"]:3149: in function <Interface/AddOns/Carbonite/NxUI.lua:3122>

```

**Comment by boxcutter411** [comment]
The above observed behaviour is what's occurring in Era, SoD and most likely HC.  The fix pushed is for Cata Classic as far as I can see.  Great addon btw.

**Comment by IrcDirk** [comment]
Ohhh... sorry. I dont know if when i will have time to update SOD version.

**Comment by Raven427** [comment]
352x Carbonite/NxUI.lua:3149: attempt to call global 'GetMouseFocus' (a nil value)
[string "@Carbonite/NxUI.lua"]:3149: in function <Carbonite/NxUI.lua:3122>

Locals:
self = NxMap1 {
 PixelSnapDisabled = true
 NxMap = <table> {
 }
 Center = Texture {
 }
 NxWin = <table> {
 }
 RightEdge = Texture {
 }
 BottomEdge = Texture {
 }
 TopRightCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 BottomLeftCorner = Texture {
 }
 TopEdge = Texture {
 }
 TopLeftCorner = Texture {
 }
 backdropInfo = <table> {
 }
 LeftEdge = Texture {
 }
}
elapsed = 0.003000
this = NxMap1 {
 PixelSnapDisabled = true
 NxMap = <table> {
 }
 Center = Texture {
 }
 NxWin = <table> {
 }
 RightEdge = Texture {
 }
 BottomEdge = Texture {
 }
 TopRightCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 BottomLeftCorner = Texture {
 }
 TopEdge = Texture {
 }
 TopLeftCorner = Texture {
 }
 backdropInfo = <table> {
 }
 LeftEdge = Texture {
 }
}
win = <table> {
 TitleFStr = <table> {
 }
 BorderW = 7
 BorderH = 7
 ButClose = <table> {
 }
 Border = true
 BackgndAlphaDiff = 1
 BackgndAlphaMin = 0
 BackgndFadeOut = 0
 SaveData = <table> {
 }
 LayoutModeNormal = ""
 TitleH = 12
 TitleLineH = 10
 Closer = true
 User = <table> {
 }
 LayoutMode = "Max"
 MovSizing = false
 BackgndFadeTarget = 0
 TopH = 19
 ChildFrms = <table> {
 }
 BackgndFadeIn = 1
 Name = "NxMap1"
 Frm = NxMap1 {
 }
 BackgndFade = 0.000100
 TitleLines = 1
 ButW = 12.500000
 Sizeable = true
}
secureOk = true
x = 940.666602
(*temporary) = nil

**Comment by Raven427** [comment]
this error pops when you mouse over the map...

**Comment by IrcDirk** [comment]
@artscout fixed it on https://github.com/IrcDirk/Carbonite-Classic/tree/classic-era branch u can download and check if its fixed.

**Comment by boxcutter411** [comment]
Downloaded - Increasing error count on moving mouse on map has stopped.  Have this error on load on Era - 

[string "Carbonite/Taintless.xml:<S..."]:56: attempt to index global 'InterfaceOptionsFrame' (a nil value)
[string "Carbonite/Taintless.xml:<Scripts>"]:56: in main chunk

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'InterfaceOptionsFrame' (a nil value)"

**Comment by IrcDirk** [comment]
Great ill push this to Curse in near future. As to other error please open new issue.
