### ISSUE TITLE
SOD/Era - attempt to index global 'InterfaceOptionsFrame' (a nil value)

### ISSUE THREAD

**Issue by boxcutter411** [IrcDirk/Carbonite-Classic#388]
Have this error on load on Era, most likely same on SoD and HC.  -

[string "Carbonite/Taintless.xml:<S..."]:56: attempt to index global 'InterfaceOptionsFrame' (a nil value)
[string "Carbonite/Taintless.xml:"]:56: in main chunk

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'InterfaceOptionsFrame' (a nil value)"

**Comment by IrcDirk** [comment]
Need to update this file.

**Comment by IrcDirk** [comment]
Try now.

**Comment by boxcutter411** [comment]
Replaced Taintless.xml with your update into the @artscout branch.  Looks to be all fixed and working as intended on Era so far. Very nice!

**Comment by Farsyte** [comment]
Curse seems to be stuck at CarboniteClassicERA_SOD_HC-v1.15.2-00005.zip
released 2024-04-03. Should I be attempting to install the Cata version
on my Era install?

**Comment by IrcDirk** [comment]
Download from here Classic Era branch.

pt., 11 paź 2024, 04:37 użytkownik Greg Limes ***@***.***>
napisał:

**Comment by IrcDirk** [comment]
Will upload this version to Curse when i have time.

**Comment by Farsyte** [comment]
Thanks -- got it loaded up (with no other Add-Ons) and the problem is fixed.
