### ISSUE TITLE
[Quest] Sacred Fire (Part 2 of 2) Quest objective doesn't show in carbonite map

### ISSUE THREAD

**Issue by sungerbob** [IrcDirk/Carbonite-Classic#41]
Wowhead: https://classic.wowhead.com/quest=5062/sacred-fire

![Sacred Fire - 1](https://user-images.githubusercontent.com/31207969/65462684-fa59ec00-de5e-11e9-895d-dd7718e566cb.png)
![Sacred Fire -2](https://user-images.githubusercontent.com/31207969/65462685-faf28280-de5e-11e9-903f-768e9ddb7910.png)
![Sacred Fire -3](https://user-images.githubusercontent.com/31207969/65462686-fb8b1900-de5e-11e9-948f-f37cca51dd01.png)

**Comment by IrcDirk** [comment]
Quest data is scrapped from wowhead. No data on wowhead = no objective in quwsts module.
