### ISSUE TITLE
Many quests with mob drops as criteria are not displaying map info

### ISSUE THREAD

**Issue by pistolwhip-dev** [IrcDirk/Carbonite-Classic#46]
I've noticed that many quests where specific mob drops are a requirement of completion do not have any track/map data available.

And example of this is the Alliance quest "The Totem of Infliction" in Duskwood.
The goal of said quest is to obtain a number of mob dropped items from various locations in the zone.

I assume the issue is that the wowhead page for the quest only gives pins/location info for the quest giver/turn in rather than the specific mobs that drop each of the required items.  The items themselves are linked on the page, but you have to drill quite a few links down to get locations for said mobs.  The flow is roughly Quest Page-->Goal Item Page-->Dropped By listing-->Specific mob Page
This will get you locations for one of the possible mobs that may drop one of the required items.

Are there plans to include this information to provide locations for quests like this?

**Comment by IrcDirk** [comment]
You are 100% right. Quest objectives doesnt show up becouse they are not available on WoWheads quest page (not shown on quests map). 

Scrapping WoWhead for quest data takes about 8-10 hours and thats only pages with quests. Making it work in the way you described its possible but its not so easy and will increase this time drasticly. Ill think about it...

**Comment by chuman72486** [comment]
Is there a way to have Carbonite gather data from gameplay?  Like, if I kill a monster and it drops the quest item, log the coordinates it happened at and let us upload those findings to compile your quest data faster than waiting for WoWHead to find it.

**Comment by IrcDirk** [comment]
Yes, there is a way built in Carbonite already. But im updating quest database from other source, it will not be perfect but still more that from WoWHead. Just wait little more.
