### ISSUE TITLE
Functionality with Classic Codex

### ISSUE THREAD

**Issue by Paranic89** [IrcDirk/Carbonite-Classic#47]
So i use the addon ClassicCodex and it does not seem to be properly working with your addon. Probably cause you change the whole minimap/map into your custom one.

The problem is Classic Codex usually shows you all the available quest givers on the map and also puts dots on the spawnpoints of certain quest related mobs/items etc. The spanpoints are lined up in a straight line under your minimap icons tooltip

![WoWScrnShot_092519_073136](https://user-images.githubusercontent.com/55778566/65572216-aa1a8100-df67-11e9-8f45-92678c130a1b.jpg)

It seems like the monimap is being hidden in your regular map under your current location but by crolling up and down that can happen

![WoWScrnShot_092519_073212](https://user-images.githubusercontent.com/55778566/65572262-de8e3d00-df67-11e9-82fe-8a094bdbd33a.jpg)

and as you can see the actual objectives are still shown on the minimap just not on the global map

![WoWScrnShot_092519_073402](https://user-images.githubusercontent.com/55778566/65572305-f82f8480-df67-11e9-8940-a551e02553a6.jpg)

I would very much like to use your addon but its just far to inconvenient right now without seeing the actual positions of the quest givers

Sorry its my first time doing this so i hope you get my problem

**Comment by IrcDirk** [comment]
U can have quest givers with Carbonite => https://github.com/IrcDirk/Carbonite-Classic/issues/28 

I dont have time to make all avaiable addons compatibile with Carbonite Map. Maybe someday that will happen but for now there are more important issues to fix.

**Comment by Paranic89** [comment]
thx that helped. i just separated carbonite from ingame(leatrix maps) map and moved minimap to keep both advantages
