### ISSUE TITLE
Carbonite doesn't check current quest progress on quest givers

### ISSUE THREAD

**Issue by Rhendak** [IrcDirk/Carbonite-Classic#49]
It seems that the quest givers on the map do not keep up to date with current quest progress. As can be seen in the screenshot below, I've already accepted the quests from this NPC, but they still show up on the map as acceptable quests. 

![image](https://user-images.githubusercontent.com/1855295/65593166-3b055280-df90-11e9-999f-dfb296f9465a.png)

In the screenshot below it seems like progress is not tracked and maybe showing future available quests, which are currently not available to me because I've not done the prequest? It also shows another quest which is not available at the NPC because I have already completed it. 

![image](https://user-images.githubusercontent.com/1855295/65593351-99323580-df90-11e9-957e-356da6fb1f0c.png)

**Comment by IrcDirk** [comment]
This option always shows quest all quest givers, not those that are available. It doesnt hide quest "!" when u complete. only quest title changes to green. Thats all. It works as intended.

**Comment by Rhendak** [comment]
Didn't Carbonite used to load in a quest database and check how many quests were done by the player, then filter those quests out, causing them to not show on the map anymore?

**Comment by Kabulla** [comment]
>  
> When logging in or reloading it would say in chat:
> "Marked < x amount > of quests as done."

Which means, "marking them as green", if I understand correctly...

**Comment by IrcDirk** [comment]
> Didn't Carbonite used to load in a quest database and check how many quests were done by the player, then filter those quests out, causing them to not show on the map anymore?

Was but this was changed becouse in this way low level quests wasnt visible.

**Comment by IrcDirk** [comment]
Ok. Checked all and u need to check "Get Completed Quest Information on Login" then Quest Giver with **All Completed** quests will not show "!" on map.

**Comment by Rhendak** [comment]
Seems like I already had that option enabled, but still the same thing. 

![image](https://user-images.githubusercontent.com/1855295/65604055-081a8900-dfa7-11e9-9ddf-777178001238.png)

I turned in the quest (as can be seen in chat) then did a /reload (also seen in chat), it marked the completed quest as gray colored, but did not remove it from my (mini)map when I hover over the quest giver.
![image](https://user-images.githubusercontent.com/1855295/65604030-fe912100-dfa6-11e9-82fb-f1a944b1b737.png)


Also, side note: Is it worth creating 1 ticket that we can report all the missing quests in? Or should we just ignore the missing quests for now?

**Comment by IrcDirk** [comment]
Everything works fine u have to give up "Fuel for the Zapping" then "!" should hide.

I may did get wrong colors: 
- green is quest in progress
- grey quest done and given up
- white is quest that can be accepted.

**Comment by Rhendak** [comment]
Below are my threshold settings. I don't believe that that has anything to do with it. "Zapped Giants" and "Again With the Zapped Giants" just were not in the Carbonite database.

![image](https://user-images.githubusercontent.com/1855295/65607587-15d30d00-dfad-11e9-9011-b7c0567ef18d.png)

But what I really meant is that as can be seen in the chat, I've turned in "Zapped Giants", but it's still showing on the quest NPC. 

This might have not been the best example, since the quest names are very similar. But they are seperate quests. "Zapped Giants" has been completed and should thus not be showing if I'm correct. Currently it's marked as grey which also means it's done, which I guess is fine too.

**Comment by IrcDirk** [comment]
> But what I really meant is that as can be seen in the chat, I've turned in "Zapped Giants", but it's still showing on the quest NPC.

Thats weird. I didnt had that on my side. Was questing today and i would pay attention if that would happen. That may be other addon. Disable all addons just leave Carb + modules and check again.

> Strange thing is, only when ALL Quests from a specific NPC are completed, then the NPC quest giver disappears from the map. But before that stage is reached, completed quests are not filtered out. Only when all quests from the same quest giver have been completed, the quest giver will be filtered out entirely of the map.

Yes, thats how it was working since WoTLK, but maybe it should mimic more blizz like behaviour.
