### ISSUE TITLE
Minimap and Map zoomed out to continent level

### ISSUE THREAD

**Issue by Rezanow** [IrcDirk/Carbonite-Classic#51]
When I press M the map shows up zoomed out showing both continents, very small. The same happens in the minimap -- minimap is docked, and continent shows (again, small). Autosize is doing nothing. 

I started using Carbonite yesterday and it was fine until now.

**Comment by Rezanow** [comment]
![carbonite](https://user-images.githubusercontent.com/5447622/65640781-fda8c100-df9f-11e9-9dc6-9bb6c70da083.PNG)

**Comment by Rezanow** [comment]
![carbonite2](https://user-images.githubusercontent.com/5447622/65640824-12855480-dfa0-11e9-96c9-830b42484ce0.PNG)

**Comment by IrcDirk** [comment]
Auto Scale doesnt work becouse u have it disabled. Should be like this:

!(https://i.imgur.com/b7vpYYI.png)[auto scale]

**Comment by IrcDirk** [comment]
Also u can use also always right click map **Restore Map Scale** then **Save Map Scale**:

![r](https://i.imgur.com/z00zvw4.jpg)

**Comment by Rezanow** [comment]
I tried it with autoscale on and off. Restore map scale was making no difference either. When I have a chance today, I will remove other add-ons to see if there's any conflicts.

**Comment by IrcDirk** [comment]
Yes, check with all other addons disabled.

**Comment by Rezanow** [comment]
Indeed, it is a conflict.  The only change I made yesterday was updating ElvUI. Prior to their update, I had managed to get the two working together rather well. Now I can't. Not your fault or problem. =)

**Comment by IrcDirk** [comment]
Also using ElvUI no problems... It might be ElvUI+Carbonite+OTHER  addon ;)

**Comment by Rezanow** [comment]
Fair enough. I do have over 50 addons. 
![addons](https://user-images.githubusercontent.com/5447622/65694911-730da380-e02b-11e9-8c5b-e5a121da9c75.PNG)

Do you have the Carbonite map replacing ElvUI's maps? I tried replacing and coexisting (Alt+M for Carb stuffs).

**Comment by IrcDirk** [comment]
I use Carbonite Map as Main Map addon with combined Minimap and in ElvUI disabled Minimap integration. Then if i need i use Alt+M for Blizz map.

**Comment by Rezanow** [comment]
Does Carbonite put quest data in the tooltips? I wasn't seeing it, but that could be yet another conflict. haha

**Comment by IrcDirk** [comment]
Not yet. Questie does.

**Comment by Rezanow** [comment]
Yes, and I've already found that Questie doesn't like Carbonite. I wish they all could just get along. ;)
