### ISSUE TITLE
settings->map->setting map

### ISSUE THREAD

**Issue by Mackiavelly** [IrcDirk/Carbonite-Classic#52]
<img width="320" alt="123" src="https://user-images.githubusercontent.com/11190487/65675796-6f901180-e057-11e9-9d21-3e0d5faf6a20.png">
setting don't work

**Comment by IrcDirk** [comment]
Works with no problem.

At 6:
![at 6](https://i.imgur.com/cuEGuvB.jpg)

At 12:
![at 12](https://i.imgur.com/sHQPjNZ.jpg)

**Comment by Mackiavelly** [comment]
<img width="718" alt="234" src="https://user-images.githubusercontent.com/11190487/65679729-576fc080-e05e-11e9-9686-e80c4b9d1dd3.png">
-download last version
-restart client wow
-disable all other addon
-reset addon setting
-set 40
-reload ui
-don't work

**Comment by Mackiavelly** [comment]
i test in MAC client maybe some problem here

**Comment by IrcDirk** [comment]
I dont see map details on your screenshot. So u dont understand what is that setting for. See my screenshots. U need to zoom in to show minimap like details or set Right Click Map -> Scale -> Details at Scale to 0.5.

**Comment by Mackiavelly** [comment]
sorry realy
THX!
