### ISSUE TITLE
In party quest reporting issue

### ISSUE THREAD

**Issue by dalesnail** [IrcDirk/Carbonite-Classic#54]
When I have the quest reporting activated to announce in party chat, it sometimes goes into a state where it will report all of my current quests, and their objectives, over and over again in chat. 

I will try my best to narrow it down to a more specific event, and report more here.

**Comment by IrcDirk** [comment]
It would be nice to have more info. Did not happened to me but i hardly play party.

**Comment by dalesnail** [comment]
I will try and pinpoint exactly when it happens in the next day or so, and grab some screenshots then. Very sorry, as I'm at work this morning and completely forgot to post here last night. 

**It seemed to happen in 2 instances:**

**1.** When a new member joined the party, and then picked up quest items, and then each time after they picked up a new quest item. 

**2.** When I had completed one objective, it seemed to bug and then report all at the same time, each time I looted a quest item. And by all at the same time I mean all of my quests from all zones, not just all from one quest. 

I know you need more to go off of, and I will be trying my best to recreate it for you to help.

**Comment by IrcDirk** [comment]
The problem is that i need to test it my self and i doesnt have party members avaiable. Where do you play? Maybe u can help debug this?

**Comment by dalesnail** [comment]
I'd be willing to help sure. I've got your email I think, I'll reply to you there to coordinate.

**Comment by kensonxa** [comment]
I am of course willing to help as well. Horde on Pyrewood Village (EU, en)

**Comment by IrcDirk** [comment]
Contact me through mail please :) Only EU players, dont have US accont ;)

**Comment by IrcDirk** [comment]
Got another account to test this. But cant reproduce, maybe i fixed it? Please check on your side and report back.

**Comment by axlekitty** [comment]
seems fixed for me now after update
