### ISSUE TITLE
Warsong Supplies - Ashenvale - Objectives labeled incorrectly

### ISSUE THREAD

**Issue by dalesnail** [IrcDirk/Carbonite-Classic#55]
For the quest Warsong Supplies in Ashenvale the areas highlighted for the objectives seem to be labeled incorrectly. Confirmed with 2 friends using the addon as well that theirs shows this too. 

Instead of **Warsong Oil** it is showing **Warsong Saw Blades**. 
Instead of **Logging Rope** it is showing **Warsong Axe Shipment**. 

Not of high importance, just something we noticed.

**Comment by IrcDirk** [comment]
Quest data was scrapped from here: https://classic.wowhead.com/quest=6571/warsong-supplies , as u cane se those items are there...

**Comment by dalesnail** [comment]
It's showing the areas in game, but they are just labeled as the wrong item. 

I finished the quest without screenshots unfortunately, and just remembered at work this morning. I will try and get some screenshots of this in game as well, I apologize. 

![Oil](https://user-images.githubusercontent.com/20726565/65697142-6ea3b380-e048-11e9-8311-80b5c7dedd83.png)

![Rope](https://user-images.githubusercontent.com/20726565/65697143-6ea3b380-e048-11e9-95ce-c12135146b95.png)

**Comment by IrcDirk** [comment]
Yes, i have noticed that, WoWHead is not 100% accurate place to scrap data but maybe in future ill combine wowhead with other source.

**Comment by IrcDirk** [comment]
Quest Database updated from new source. Check now should be better.
