### ISSUE TITLE
Map issues with closing and resizing..

### ISSUE THREAD

**Issue by wtfaatp** [IrcDirk/Carbonite-Classic#56]
While in combat the minimap/large map will not swap and if you resize the minimap the box surrounding minimap change and the map doesn't..

Will upload a photo @ a Later time.

**Comment by wtfaatp** [comment]
Sorry didn't realize I didnt upload image. 
![WoWScrnShot_092719_143329](https://user-images.githubusercontent.com/7692617/65796917-e0a8f500-e13b-11e9-8965-68fc009ca9ad.jpg)

**Comment by dalesnail** [comment]
I've experienced similar, but only while in combat. It will freeze the game for about a half second or more every time I try to resize or open the map as well.

**Comment by wtfaatp** [comment]
That's my issue all be it not huge. The problem startes when you're auto running and opening the map to look @ something the same time something agro's you and the game freezes for a sec.. It freaked me out and I spammed M tring to close the big map and when the game came back to focus I was dead.

**Comment by IrcDirk** [comment]
Closing. Working for me ;)
