### ISSUE TITLE
Round minimap indoors and outdoors

### ISSUE THREAD

**Issue by ArcaneDraco** [IrcDirk/Carbonite-Classic#60]
So i have a round minimap indoors, and a darkened circle when outdoors.. any way to fix this

**Comment by ArcaneDraco** [comment]
![WoWScrnShot_092819_130202](https://user-images.githubusercontent.com/43486186/65821880-8cac1800-e1f0-11e9-881a-8855814493a2.jpg)
![WoWScrnShot_092819_130235](https://user-images.githubusercontent.com/43486186/65821881-8cac1800-e1f0-11e9-8d20-b9a7037215f5.jpg)

**Comment by IrcDirk** [comment]
Reset Carbonite settings would be the simplest way.
