### ISSUE TITLE
Warehouse does not show reagents.

### ISSUE THREAD

**Issue by cylismaori** [IrcDirk/Carbonite-Classic#61]
In Classic, the reagent bank does not exist, so reagents are stored in inventory or regular bank, The warehouse asks to to check your reagent bank, and does not display any flowers, ore, cloth, or enchanting supplies.

**Comment by IrcDirk** [comment]
Ok, will check that.

**Comment by IrcDirk** [comment]
Reagent bank doesnt exist so i removed this from Warehouse. Reagents in Classic are named Trade Goods so new group named this way will show all those items.
