### ISSUE TITLE
Watch all quests does nothing

### ISSUE THREAD

**Issue by dlecina** [IrcDirk/Carbonite-Classic#62]
I used "Remove All Watches" by accident and then tried to use "Watch All Quests" in order to restore them, but it does nothing.

- Please fix Watch all quests
- ~Is there a way to watch quests after they have been removed?~
edit: I see it is possible to watch quests manually by using the Carbonite quest log, rather than the standard one.

Thanks

**Comment by IrcDirk** [comment]
Will check this issue in near future.

**Comment by axlekitty** [comment]
i had to delete my carbonite settings files and reset my default game settings. fixed it, just a setting conflict im assuming.

**Comment by IrcDirk** [comment]
Itmight help to reset Carbonite, but it should work without doing this. On my side it doesnt work too, so ill need to fix it.

**Comment by dlecina** [comment]
Fix confirmed!
