### ISSUE TITLE
QuestLog opens first after two times click

### ISSUE THREAD

**Issue by avecsr** [IrcDirk/Carbonite-Classic#63]
The QuestLog on the taskbar at the bottom only opens after two clicks on it.

**Comment by IrcDirk** [comment]
This only happens when addon is not fully loaded. I dont find this is an issue.

**Comment by avecsr** [comment]
How to load it "fully" ? I have load all the carbonite modules.

**Comment by IrcDirk** [comment]
You didnt wrote what modules u use so im assuming ALL ;) Please describle your issues well.

**Comment by avecsr** [comment]
I have carbonite addon and all modules loaded.

**Comment by IrcDirk** [comment]
So wait till: [QUEST LOADER] 4126 Quests Loaded. After that clicking QuestLog icon works with no problems. 

Also keep in ming that other addons might be the problem. Check always with only Carbonite + Modules enabled.

**Comment by avecsr** [comment]
hey, after restarting WoW no more probs thanks! I just wanna thank you for doing this. Carbonite for classic my most favorite addon ever. Maybe i quit retail years ago because i was carbonite missing!
