### ISSUE TITLE
Quest not postable

### ISSUE THREAD

**Issue by avecsr** [IrcDirk/Carbonite-Classic#64]
If you post a quest of the questlog in your party or whatever, the name of the Quest not showing

**Comment by IrcDirk** [comment]
Needs fixing.

**Comment by IrcDirk** [comment]
Ok, Fixed but classic doesnt allow to link quests in chat ... so i need to disable it in menu.

**Comment by avecsr** [comment]
Better not link quest, instead of link just write the name of the quest -> this would be the best option here!

**Comment by IrcDirk** [comment]
Yeah fixed it, now it just shows it as text, in this way this works.

**Comment by avecsr** [comment]
Works - but its not showing the group my progress ... (example: 8/15 ogres killed)

**Comment by IrcDirk** [comment]
As to Quest name not in your language thats true this needs fix.

But progress? This is not the same issue u reported...
