### ISSUE TITLE
NxQuest error at login.

### ISSUE THREAD

**Issue by breakone9r** [IrcDirk/Carbonite-Classic#66]
Date: 2019-09-29 13:31:55
ID: 1
Error occured in: Global
Count: 5
Message: ..\AddOns\Carbonite.Quests\NxQuest.lua line 7874:
   attempt to index local 'quest' (a nil value)
Debug:
   Carbonite.Quests\NxQuest.lua:7874: UpdateIcons()
   Carbonite\NxMap.lua:4944: Update()
   Carbonite\NxMap.lua:3904:
      Carbonite\NxMap.lua:3788
Locals:
self = <table> {
 IconTracking = <table> {
 }
 UnpackCategory = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10595
 DailyTypes = <table> {
 }
 IsTargeted = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10361
 Menu_OnTrack = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3241
 GetQuestReward = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3295
 DecodeComRcv = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11231
 MsgNotInDB = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5253
 Watch = <table> {
 }
 PartyStartSend = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11493
 SortQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4328
 NullQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11641
 CheckQuestSE = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3179
 GetFromPlyr = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5067
 Custom = <table> {
 }
 TTChange = <table> {
 }
 TooltipProcess2 = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5362
 IdToCurQ = <table> {
 }
 PerColors = <table> {
 }
 GetClosestObjectivePos = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10875
 RecordQuestsLog = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3481
 ExtractTitle = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4304
 CalcCNumMax = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4112
 UnpackObjective = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10633
 GetQuestObjectiveInfo = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4270
 ClearCaptured = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5087
 TooltipProcess = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5338
 SelectBlizz = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3349
 UnpackNext = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10586
 ShowUIPanel = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5867
 CapturePlyrData = <table> {
 }
 GetObjectiveType = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10646
 PartyUpdateTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11486
 MapChanged = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4004
 OnParty_members_changed = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11327
 TrackedAchievements = <table> {
 }
 UpdateQuestDetails = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8308
 DailyIds = <table> {
 }
 CalcDesc = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4252
 QLocColors = <table> {
 }
 CalcPreviousDone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4155
 AccessAllQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3429
 IconOnMouseDown = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8253
 OnProfileChanged = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:2159
 WatchAtLogin = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4898
 CreateLink = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4296
 LightHeadedAttach = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5935
 RecordQuestAcceptOrFinish = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4450
 Goto = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4928
 InitQuestCharacter = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:2170
 RealQEntries = 15
 AcceptQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3275
 GetHistoryTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4205
 Requirements = <table> {
 }
 TellPartyOfChanges = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.1.12
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  AutoBarClassic, v1.13.2.04
  BagBrother, v
  Bagnon, v8.2.15
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  Carbonite, v@project-version@
  CarboniteNotes, v@project-version@
  CarboniteQuests, v@project-version@
  ClassicCastbars, vv1.0.8
  ClassicCastbarsOptions, v
  ClassicLFG, v1.1.0
  ConROC, v1.13.23
  ConROCWarrior, v1.13.5
  Details, v
  DetailsTinyThreat, v
  DismountMe, v1.1
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  Fizzle, v80200-4
  GatherMate2, v1.45.4
  GTFO, v4.50
  HandyNotes, vv1.5.6
  HandyNotesDungeonLocationsClassic, v1.03
  HandyNotesFlightMastersClassic, v1.06
  HandyNotesNPCsClassic, v1.16
  HandyNotesTravelGuideClassic, vv2.1.4
  InFlightLoad, v1.13.003
  Informant, v8.2.6374 (SwimmingSeadragon)
  LibClassicDurations, v1.19
  NeatPlates, v1.13.2.35
  NeatPlatesAlvara, v5a
  NeatPlatesBlizzardPlates, v1.5
  NeatPlatesClassicPlates, v
  NeatPlatesGraphite, v
  NeatPlatesGrey, v
  NeatPlatesNeon, v
  NeatPlatesQuatre, v
  NeatPlatesRenaitre, vv7.0.3
  NeatPlatesRoth, v
  NeatPlatesSimple, v7.3.0
  NeatPlatesSlimHorizontal, v2.2
  NeatPlatesSlimVertical, v2.2
  NeatPlatesHub, v
  NeatPlatesWidgets, v
  OmniCC, v8.2.5
  outofrange13, vv1.3
  Prat30, v3.7.36
  Prat30Libraries, v
  Questie, v4.1.1 BETA
  RealMobHealth, v2.13
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TitanClassic, v1.1.1.11302
  TitanClassicAmmo, v1.1.1.11302
  TitanClassicBag, v1.1.1.11302
  TitanClassicClock, v1.1.1.11302
  TitanClassicGold, v1.1.1.11302
  TitanClassicItemDed, v1.0.0.2
  TitanClassicLocation, v1.1.1.11302
  TitanClassicLootType, v1.1.1.11302
  TitanClassicMail, v1.0.0.0
  TitanClassicPerformance, v1.1.1.11302
  TitanClassicReagentTracker, v1.13.2
  TitanClassicRegen, v1.1.0.11302
  TitanClassicRepair, v1.1.1.11302
  TitanClassicVolume, v1.1.1.11302
  TitanClassicXP, v1.1.1.11302
  TitanSocial, v1.13.2
  UnitFramesPlus, v1.29
  UpRank, v1.0
  WeakAuras, v2.15.1
  zzMiscHelper, v
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=995)

**Comment by IrcDirk** [comment]
U have many addons there might be some incompatibility. Disable all, just leave Carbonite + Modules enabled. Recheck and report back :)

**Comment by breakone9r** [comment]
> U have many addons there might be some incompatibility. Disable all, just leave Carbonite + Modules enabled. Recheck and report back :)

Seems to only show up when AuctioneerAdvanced is enabled.  Which is strange since it shouldnt be doing anything with the quest global.....

**Comment by breakone9r** [comment]
Date: 2019-09-29 14:05:08
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite.Quests\NxQuest.lua line 7874:
   attempt to index local 'quest' (a nil value)
Debug:
   Carbonite.Quests\NxQuest.lua:7874: UpdateIcons()
   Carbonite\NxMap.lua:4944: Update()
   Carbonite\NxMap.lua:3904:
      Carbonite\NxMap.lua:3788
Locals:
self = <table> {
 IconTracking = <table> {
 }
 UnpackCategory = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10595
 DailyTypes = <table> {
 }
 AcceptPool = <table> {
 }
 Menu_OnTrack = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3241
 GetQuestReward = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3295
 DecodeComRcv = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11231
 MsgNotInDB = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5253
 Watch = <table> {
 }
 PartyStartSend = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11493
 SortQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4328
 NullQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11641
 CheckQuestSE = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3179
 GetFromPlyr = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5067
 Custom = <table> {
 }
 TTChange = <table> {
 }
 OldMap = 0
 IdToCurQ = <table> {
 }
 PerColors = <table> {
 }
 GetClosestObjectivePos = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10875
 RecordQuestsLog = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3481
 ExtractTitle = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4304
 CalcCNumMax = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4112
 ScanBlizzQuestDataZone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4027
 GetQuestObjectiveInfo = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4270
 FindCur = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4791
 TooltipProcess = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5338
 SelectBlizz = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3349
 UnpackNext = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10586
 ShowUIPanel = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5867
 CapturePlyrData = <table> {
 }
 GetObjectiveType = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10646
 PartyUpdateTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11486
 MapChanged = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4004
 GetQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11623
 AlchemistsApprenticeData = <table> {
 }
 UpdateQuestDetails = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8308
 DailyIds = <table> {
 }
 CalcDesc = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4252
 QLocColors = <table> {
 }
 CalcPreviousDone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4155
 AccessAllQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3429
 IconOnMouseDown = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8253
 OnProfileChanged = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:2159
 WatchAtLogin = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4898
 CreateLink = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4296
 LightHeadedAttach = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5935
 RecordQuestAcceptOrFinish = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4450
 ExpandQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3359
 InitQuestCharacter = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:2170
 RealQEntries = 16
 AcceptQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3275
 GetHistoryTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4205
 Requirements = <table> {
 }
 TellPartyOfChanges = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4713
 Cols = <table> {
 }
 CreateGiverIconMenu = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10180
 ScanBlizzQues
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Carbonite, v@project-version@
  CarboniteNotes, v@project-version@
  CarboniteQuests, v@project-version@
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=bf)

There. Now it's only doing it with those addons: Swatter and Carbonite.

**Comment by IrcDirk** [comment]
Hmmm... ok. Thats weird. Will check this.

**Comment by IrcDirk** [comment]
Do you use latest version from github?

**Comment by IrcDirk** [comment]
Closing since there is no more feedback and no one else is reporting this problem
