### ISSUE TITLE
"Add note" over a Quest-Area is doing nothing

### ISSUE THREAD

**Issue by avecsr** [IrcDirk/Carbonite-Classic#72]
"Add note" over a Quest-Area is doing nothing

**Comment by TULOA** [comment]
Looks like the changes in the Notes from in Carbonite.Notes\NxFav.lua @ Line 170  has somehow broken it.

Reverting it back to Carbonite 8.3 version code in that area fixes this.

Attached is fixed NxFav.lua which is zipped. Its in the Nx.Notes:Init() function
[NxFav.zip](https://github.com/IrcDirk/Carbonite-Classic/files/4828517/NxFav.zip)

I do need to see if we can fix the icon size though. At max scale it still seems slightly small.
