### ISSUE TITLE
Unavailable quests are displayed

### ISSUE THREAD

**Issue by o0shojo0o** [IrcDirk/Carbonite-Classic#74]
Hello, 
I have the problem that all quest are shown to me as available (!). 
Even if I cannot accept them yet, 
because it's an episode quest or something. 

Or do I have a setting fault here?

**Comment by IrcDirk** [comment]
Where are displayed? On map? Use setting Load quest by threshold. By default all quests are loaded.

**Comment by IrcDirk** [comment]
Keep in mind this is not Leveling addon... i will show u quests for other classes, profesions etc.

**Comment by o0shojo0o** [comment]
Ok, thanks for clarifying.
