### ISSUE TITLE
Messed-up Eastern Plagueland map

### ISSUE THREAD

**Issue by rd553** [IrcDirk/Carbonite-Classic#76]
My Carbonite map is extremely broken in the Eastern Plaguelands. Each map chunk seems to be slightly misaligned, leading to roads that vanish into nothing and landmarks that are shown far away from their actual location. The entire area also shows as dark and unexplored, with a handful of lighter spots.

![WoWScrnShot_100419_053436](https://user-images.githubusercontent.com/6574336/66181456-c05fc580-e668-11e9-80cb-caeed4b7011d.jpg)

**Comment by IrcDirk** [comment]
Thanks for reporting. Should be fine now. Check and report back.

**Comment by rd553** [comment]
Everything seems fixed now. Checked a couple of landmarks just to be sure, and it looks like it's all good.
