### ISSUE TITLE
Transparent Minimap with Carbonite-Classic-0.9

### ISSUE THREAD

**Issue by Kozrek** [IrcDirk/Carbonite-Classic#77]
Update 0.9 from today changed the carbonite minimap into a transparent minimap, I don't want a transparent minimap, how can I get that one from 0.8 back?

**Comment by dalesnail** [comment]
Are you downloading and using the files from here, direct from source? Or are you just using 3rd party site downloads (curse, wowinterface etc.)?

I had this issues a little while ago, and it was resolved, but it wasn't packaged in a release yet as far as I know.

**Comment by Kozrek** [comment]
Downloaded from curse with twitch app.

**Comment by Kozrek** [comment]
Got it, set transparent the 3rd option to 1,00

**Comment by IrcDirk** [comment]
Yes, default is semi transparent when mouse out: Right Click carbonite map -> Transparency -> Fade out transparency 1.0.

**Comment by Galenthor** [comment]
thank you!
