### ISSUE TITLE
LUA errors on party accept/logins

### ISSUE THREAD

**Issue by Jashina** [IrcDirk/Carbonite-Classic#78]
Getting this error evertime I join a party or someone else joins or leaves the party. 

Message: Interface\AddOns\Carbonite.Quests\NxQuest.lua:4267: attempt to compare two nil values
Time: Mon Oct  7 22:46:03 2019
Count: 1
Stack: Interface\AddOns\Carbonite.Quests\NxQuest.lua:4267: attempt to compare two nil values
[C]: ?
Interface\AddOns\Carbonite.Quests\NxQuest.lua:4267: in function `CalcDesc'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:11541: in function `func'
...\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:57: in function <...\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

**Edit** After further trial and error, I realise that this error pops up everytime I talk to a quest giver, Look at a new quest, and accept a new quest

**Comment by IrcDirk** [comment]
Update to latest version from github. Check again and report back.

**Comment by IrcDirk** [comment]
Please write what quests that was.

**Comment by Jashina** [comment]
Currently most quests in Arathi Highlands, but it doesn't seem to matter all quests give the same error.
I get it everytime I log in now. Have tried disabling every addon except Carbonite. Have tried uninstalling everything except carbonie. it still shows up

**Comment by Jashina** [comment]
I have the latest version and I'm still getting the Lua error.

**Comment by IrcDirk** [comment]
Sorry cant reproduce... All works fine on my side in party and solo. Anyone has this problem too?

**Comment by Jashina** [comment]
I don't understand it either, I'm playing mostly with a friend and we have basically the same add-on folder, and he doesn't have the same problem at all.. thanks for trying, I'm gonna try a complete reinstall to see if I can get rid of the issue.

**Comment by IrcDirk** [comment]
Try removing Carbonite settings from SavedVariables in WTF folder after closing WoW.

**Comment by IrcDirk** [comment]
Closing since no more info about it. No one other reporting this.
