### ISSUE TITLE
quest pack

### ISSUE THREAD

**Issue by Devilishly02** [IrcDirk/Carbonite-Classic#79]
i just downloaded carbonate today 10-08-2019 and the quest portion is not allowing me to accept quest or turn in. i have to disable the quest mod part to turn in and pick up any quest

**Comment by IrcDirk** [comment]
Disable all other addons and try only Carbonite + Modules. It could be other addon incompatibility.

**Comment by Devilishly02** [comment]
Immersion addon was causing the issue. Have disabled immersion and now works fine

**Comment by IrcDirk** [comment]
Works with immersion with no problems.

**Comment by IrcDirk** [comment]
Closing. No more info.
