### ISSUE TITLE
Carbonite Minimap button constantly flashes

### ISSUE THREAD

**Issue by jerj** [IrcDirk/Carbonite-Classic#8]
The button flashes white/black/white/black nonstop. I just disabled the button in the options for now. Not a big problem.

**Comment by IrcDirk** [comment]
Thats normal when new information is not read, right then click "Whats new!"

**Comment by qwksilver** [comment]
Is there a way to turn notifications off permanatly, some may not want or need this.

**Comment by IrcDirk** [comment]
I will not post those updates. So it will not flash... thinking of removing this feature.

**Comment by someolguy** [comment]
I rather appreciate having the info there, perhaps maybe changing it's color instead of flash when new info?

**Comment by qwksilver** [comment]
I don't mind the flash now that i know to click "what's new" a the bottom, I think when it's in notification mode, clicking it opens the notice, might be more intuitive.

**Comment by im-n1** [comment]
The flashing made me remove whole addon because I wasnt able to find out why it flashes.

**Comment by KoolKeith** [comment]
I also removed the Button alltogether, the flashing is way too aggressive. Will try "What's new" until this gets tamed.

Thank you very very much for Carbonite Dirk !!! Can't live without it.
