### ISSUE TITLE
Atlas Map in Classic

### ISSUE THREAD

**Issue by DarrenWillows** [IrcDirk/Carbonite-Classic#80]
Is it possible to make it use the Atlas_ClassicWoW maps instead for higher resolution maps?

**Comment by IrcDirk** [comment]
U mean for instances?

**Comment by DarrenWillows** [comment]
I mean for the world map, where I highlight over an area it looks like https://i.imgur.com/5XE82op.jpg .

Partially complete even tough I have been to the area and only partly using the higher texture.
Is it possible to make this always visible and cover the whole area.

**Comment by DarrenWillows** [comment]
Ignore this comment. Another addon was causing Carbonite to not work.

**Comment by IrcDirk** [comment]
Ohhh ok 👍
