### ISSUE TITLE
When carbonite and handynotes are enabled, handynotes only show up on bliz minimap while moving.

### ISSUE THREAD

**Issue by breakone9r** [IrcDirk/Carbonite-Classic#81]
Title is self-explanatory. When I enable Carbonite, my HandyNotes notes all disappear from the blizzard minimap.  Unless I start moving, at which point, the notes all show up. until I stop moving.

Disabling the Carbonite Notes module solves this glitch.

Toggling the "Show Handynotes" option does not help with the issue.

**Comment by IrcDirk** [comment]
Handynotes + Carbonite Classic works like fine, no problems on my side. All works fine when moving. Icons are showed on Carbonite Map and on Blizz orginal map.

Which plugin for Handynotes you are using?

**Comment by IrcDirk** [comment]
Sorry u wrote Blizz minimap. U need them to show on minimap while u have them on Carbonite? If not just disable Handynotes and they will not show on Blizz minimap but will stay on Carbonite map.

![https://i.imgur.com/jnJqGYI.png](screenshot)

**Comment by breakone9r** [comment]
I use the minimap for "right here" mapping, while I use the minimized carbonite map as an overview/guide map.

I want the icons on the minimap. I couldnt care less if they're on the carbonite map, disabling handynotes does the exact opposite of what I want.

**Comment by IrcDirk** [comment]
Notes Module is mainy used for HandyNotes and your own notes. For now just disable it if u dont use notes. Maybe ill work on this in future.

**Comment by msoky** [comment]
this is bug and author does not understand problem probably...when you use carbonite + handynotes addons together, then handynotes does not work when you stay on place (icons not show on minimap) but when you move, everything is okay and icons is showing on minimap
