### ISSUE TITLE
Map Zoom

### ISSUE THREAD

**Issue by Stellartois** [IrcDirk/Carbonite-Classic#82]
When you zoom all the way in the map is clear and focused / when you zoom far far out the map is focused and clear // but in the middle is when the map is all blurry... please advise how to fix this issue

**Comment by IrcDirk** [comment]
Please provide screenshot... I dont realy understand whats the issue.

**Comment by Stellartois** [comment]
OK in files attached...
Map01 is a Zoom out and it is clear; 
Map02 is midway between zoom out and zoom in and it is blurred; 
Map03 is the equivilent to the Blizzards minimap it is clear again

Also how can i access the quest database, i am having a problem with an NPC that does not have a quest available but should have, and i was just wanting to see if i completed it in the past and forgot about it

![Map01](https://user-images.githubusercontent.com/56514352/66719075-71bcd480-eda8-11e9-8cdd-842c7e8a5956.PNG)
![Map02](https://user-images.githubusercontent.com/56514352/66719080-771a1f00-eda8-11e9-9848-4f3c555dbb95.PNG)
![Map03](https://user-images.githubusercontent.com/56514352/66719082-7d100000-eda8-11e9-8b31-c1c806be344e.PNG)

**Comment by IrcDirk** [comment]
Disable all other addons try only with Carbonite + Modules enabled. It might be incompatibility with other addon.

**Comment by Stellartois** [comment]
Disabled all addons and still same issue

**Comment by IrcDirk** [comment]
Sorry cant reproduce. Zoom out map should show Overlay not minimap.

**Comment by Jashina** [comment]
How do you get that zoom out image? All I get when i zoom out is the standard "world map" texture in mine

**Comment by IrcDirk** [comment]
@Jashina Right Click Map -> Scale... -> Details at Scale set it to lowest value.
