### ISSUE TITLE
Lua-error when loading carbonite/make progess in quest

### ISSUE THREAD

**Issue by Blackbird102** [IrcDirk/Carbonite-Classic#83]
Get the following error:

> Message: Interface\AddOns\Carbonite.Quests\NxQuest.lua:4267: attempt to compare two nil values
Time: Sun Oct 13 18:40:21 2019
Count: 1
Stack: Interface\AddOns\Carbonite.Quests\NxQuest.lua:4267: attempt to compare two nil values

I think its an error when he tries to share quest progress.
I have this quest: https://classic.wowhead.com/quest=8470/deadwood-ritual-totem
Because the repation progress has a **/** in it, there comes an error when the code tries to parse the strings as integers.

in function Nx.Quest:CalcDesc (qId, objI, cnt, total)

local desc, _, _ = strmatch (odesc or "", "(.+): (%d+)/(%d+)")

**Comment by IrcDirk** [comment]
Should be fixed in https://github.com/IrcDirk/Carbonite-Classic/commit/d9ddbf4d809eef8b948bd1a3f638cbe8883e7cf7 use latest version from Github and report back.

**Comment by Blackbird102** [comment]
Error seems to be fixed. Thanks 👍
