### ISSUE TITLE
Instance maps not working? And unable to use "google style" minimap

### ISSUE THREAD

**Issue by Jashina** [IrcDirk/Carbonite-Classic#84]
Whenever I get close to a dungeon or am inside a dungeon the Map turn black/grey
![image](https://user-images.githubusercontent.com/56277655/66877115-96859780-efb4-11e9-9d2b-a1896a76783b.png)
 or looks like this
![image](https://user-images.githubusercontent.com/56277655/66877126-a3a28680-efb4-11e9-8a75-830c4c7008dc.png)
Also, I want to have the "google style" map not the regular map on Carbonite, is there a way to make it possible without having to zoom in so hard?
![image](https://user-images.githubusercontent.com/56277655/66877166-c5037280-efb4-11e9-8062-2af8d113e2cc.png)
Here it is not working

and this is when zoomed in
![image](https://user-images.githubusercontent.com/56277655/66877186-d2206180-efb4-11e9-9fc9-0fb5b50f70e7.png)

**Comment by IrcDirk** [comment]
Duplicate #7 

Dont mix issues/questions.

**Comment by IrcDirk** [comment]
Answer to your second issue is in #82 .
