### ISSUE TITLE
Quest areas totally off

### ISSUE THREAD

**Issue by erebusxx** [IrcDirk/Carbonite-Classic#85]
Some of the quests in starter areas (havent made it too far yet) are way off. Multiple quests were showing me an area covering all of trisfall glades when in fact they were single areas or a solo person to kill that were stationary.

**Comment by Kiefy** [comment]
No, theres deffinately something up.

https://i.imgur.com/djJNI7n.jpg

Wowhead is actually very accurate, only showing the areas around fargodeep mines. Ive noticed this in a lot of zones recently, but it was fine when I was playing a previous character.
