### ISSUE TITLE
Nx.Social.PunksHUD:Remove invoked when Punks system disabled

### ISSUE THREAD

**Issue by SpareSimian** [IrcDirk/Carbonite-Classic#86]
Line 2225 in NxSocial.lua fails with a nil dereference when the Punks System is disabled.

In OnUpdateTimer at line 1877, gate CalcPunks() like this:

   if Nx.scdb.profile.Social.PunkEnable then
      self:CalcPunks()
   end

**Comment by IrcDirk** [comment]
U can make pull request for those like fixes. Just fork my repository then make changes and make pull request ;)
