### ISSUE TITLE
Mail counts in warehouse are corrupted

### ISSUE THREAD

**Issue by SpareSimian** [IrcDirk/Carbonite-Classic#87]
I'm seeing huge numbers in my waremail DB instead of reasonable item counts. I'm still looking at the code to see where the count might get corrupted. The number isn't an item ID.

**Comment by SpareSimian** [comment]
The signature of GetInboxItem (used in NxWarehouse.lua at line 2826 changed. An itemID value was inserted after the name, so the addon is using the texture instead of the count. 

Classic API signature: https://wow.gamepedia.com/API_GetInboxItem
Signature assumed by addon: https://vanilla-wow.fandom.com/wiki/API_GetInboxItem

Change the line to this:

local name, _, _, count = GetInboxItem (n, i)

**Comment by IrcDirk** [comment]
Submit your changes to repository. As i did wrote in other issue u can make pull request for those kind of changes ;)
