### ISSUE TITLE
Smoldering Coal not in quest database

### ISSUE THREAD

**Issue by SpareSimian** [IrcDirk/Carbonite-Classic#89]
It looks like the entry in the quest database is wrong for this quest:

https://classic.wowhead.com/quest=4784/components-for-the-enchanted-gold-bloodrobe#comments

File is Quests32-40.lua. I think the objective[1] is actually for the coals and should be objective[2], while objective[1] should be Xizx Goodstitch in Booty Bay, who provides the gold thread in an instant sub-quest.

https://classic.wowhead.com/quest=4785/fine-gold-thread

I don't understand the format of the objective entries or I'd provide one.

**Comment by IrcDirk** [comment]
All quest data is from what WoWHead provides in map data. Its around "var myMapper = new Mapper...". Bad data there and thats why this happens.

Im working on new source for Quest DB.

**Comment by IrcDirk** [comment]
Quest Database updated from new source. Check now should be better.

**Comment by SpareSimian** [comment]
Thanks, I'm still seeing the same issue. The quest requires three items, fine gold thread (collected by a sub-quest in Booty Bay), smoldering coals (drop from fire elementals in Arathi), and a soul shard (created by the warlock). When I click the silver button for the thread in the quest tracker, it shows me the path to the location of the coals in Arathi. Clicking the reddish button next to the coals tells me the item is not in the database.  So it's like everything's off by one and the data for the gold thread is missing.

**Comment by IrcDirk** [comment]
Both quest databases (old and new) doesnt have locations of objective 1 and 3 for 4784 :(

**Comment by IrcDirk** [comment]
Order of objectives should be fixed.

**Comment by SpareSimian** [comment]
Item order seems to be fixed. Now it's the gold thread not in the DB and the smoldering coals are correctly showing in Arathi. Thanks!
