### ISSUE TITLE
Slow map/framerate

### ISSUE THREAD

**Issue by Seawood23** [IrcDirk/Carbonite-Classic#90]
The movement of the carbonite map seems capped at a very low framerate. Zooming in and out feels very rough as does the autocentering of the map when you move. The tracking HUD arrow also seems to suffer from this issue Other aspects of the addon don't feel slow or limited in this way such as the menu/options or text on the map itself (objectives, coordinate, etc)

**Comment by IrcDirk** [comment]
Sorry dont see any problems as u described. Disable all other addons, check only with Carb + Modules.

**Comment by IrcDirk** [comment]
Closing since there is no more info about this problem.
