### ISSUE TITLE
Error: ..\AddOns\Carbonite.Quests\NxQuest.lua line 4267

### ISSUE THREAD

**Issue by evilmaran** [IrcDirk/Carbonite-Classic#92]
Date: 2019-10-18 15:30:52
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite.Quests\NxQuest.lua line 4267:
   attempt to compare two nil values
Debug:
   ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:582:
      ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:542
   [C]: ?
   Carbonite.Quests\NxQuest.lua:4267: CalcDesc()
   Carbonite.Quests\NxQuest.lua:11541: func()
   ...s\ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:57:
      ...s\ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:50
Locals:
errMsg = "Interface\AddOns\Carbonite.Quests\NxQuest.lua:4267: attempt to compare two nil values"
tsmErrMsg = nil
oldModule = nil
private = <table> {
 AddonBlockedEvent = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:334
 num = 0
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:116
 hitInternalError = false
 errorFrame = <unnamed> {
 }
 origErrorHandler = <function> defined @Interface\AddOns\Decursive\Dcr_DIAG.lua:590
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:349
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:342
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:312
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:280
}
MAX_STACK_DEPTH = 50
TSM = <table> {
}

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AddOnSkins, v4.31
  AtlasLootClassic, vv1.3.1
  AtlasLootClassicData, vv1.3.1
  AtlasLootClassicDungeonsAndRaids, vv1.3.1
  ATTClassic, v0.1.2
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  Carbonite, v@project-version@
  CarboniteNotes, v@project-version@
  CarboniteQuests, v@project-version@
  CarboniteSocial, v@project-version@
  CarboniteWarehouse, v@project-version@
  ClassicSpellActivations, v
  Clique, vv1.0.3-classic
  DBMCore, v1.13.16
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.4
  ElvUI, v1.14
  ElvUIExtraActionBars, v2.37
  ElvUILocationPlus, v1.00
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  ExtendedCharacterStats, v1.5
  GatherMate2, v1.45.5
  GTFO, v4.51
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LeatrixPlus, v1.13.35
  Mapster, v1.8.5
  ShowMeMyHeal, v0.6.0
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TradeSkillMaster, vv4.8.14
  TradeSkillMasterAppHelper, vv4.0.5
  WeakAuras, v2.15.4
  WhatsTraining, v1.8.6
  WideQuestLog, v
  WIM, v3.8.2
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=5e8)

**Comment by IrcDirk** [comment]
#83
