### ISSUE TITLE
Missing quest? - "Fuel for Zapping"

### ISSUE THREAD

**Issue by Marineopferman** [IrcDirk/Carbonite-Classic#94]
For some reason I cant get the quest "Fuel for Zapping" to show up when I am questing. Can get every other quest but that one is not existing.

**Comment by IrcDirk** [comment]
Its in Quest DB.

**Comment by IrcDirk** [comment]
U may have low Quest Load Threshold and this quest isnt loaded in DB.

**Comment by Marineopferman** [comment]
I would agree with the low level but the other quest to kill the water elemental's is the same lvl at 55 and shows up on the map just fine.

**Comment by IrcDirk** [comment]
I dont see any 55 lvl quest in your quest log.

**Comment by Marineopferman** [comment]
because I finished all other quest in Feralas, cant really show quest on a map that I already completed.
