### ISSUE TITLE
Quest Tracking is all over the place

### ISSUE THREAD

**Issue by Kadikur** [IrcDirk/Carbonite-Classic#95]
The quest tracker portion of the quest module is creating tracking blobs that make it impossible to find the quest objectives. For example, the blob in Tirisfal Glades to kill 10 scarlet warriors encompasses the entire map instead of just the farm area where they are actually found.

**Comment by IrcDirk** [comment]
No problems on my side with this quest:

!(427)[https://i.imgur.com/yUxFwWH.png]

**Comment by Kadikur** [comment]
I will try uninstalling and reinstalling the addon. Maybe my data got corrupted.

**Comment by Kadikur** [comment]
I tried prior, and the problem persists. I use Twitch to get my addons.
![WoWScrnShot_102419_103206](https://user-images.githubusercontent.com/56934011/67506279-01387200-f64a-11e9-9b2d-7ac01e2a1b8d.jpg)
![WoWScrnShot_102419_103225](https://user-images.githubusercontent.com/56934011/67506294-07c6e980-f64a-11e9-86f6-dd148f1ded91.jpg)

**Comment by IrcDirk** [comment]
WoWHead: https://classic.wowhead.com/quest=367/a-new-plague dots all over place...

**Comment by Kadikur** [comment]
This can be closed because the issue, it appears, is similar to "Quest Data is Incorrect".

**Comment by IrcDirk** [comment]
Yes its very simillar. Some data on wowhead is updated and more accurate then before and some that as u see to quest ID 367 is all over the map ;) I wil do an update from other source than this should be better.
