### ISSUE TITLE
Quest blobs are incorrect

### ISSUE THREAD

**Issue by Kiefy** [IrcDirk/Carbonite-Classic#96]
You closed https://github.com/IrcDirk/Carbonite-Classic/issues/85, blaming wowhead for bad data. but that simply isnt true.  Wowhead is ![good](https://classic.wowhead.com/npc=1211/leper-gnome), carbonite is not.

![quest areas](https://i.imgur.com/WyLNjwx.jpg)

**Comment by IrcDirk** [comment]
Thats becouse WoWHead pushed update to quest db. I got saved theirs data for this quest and it differs to this new.

Im working on new source for quest data. U need to be more patient. Im the only one that is working on this project.

**Comment by Kiefy** [comment]
Sorry, I didnt mean to come off as impatient.  I just wanted to make clear that the previous issue wasn't invalid.

**Comment by IrcDirk** [comment]
Quest Database updated from new source. Check now should be better.
